### ISSUE TITLE
lesson1中的问题

### ISSUE THREAD

**Issue by yinzSE** [nswbmw/N-blog#102]
最终将 app.js 修改为：

```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');

var app = express();

app.set('port', process.env.PORT || 3000);
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

//app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

routes(app);

app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + app.get('port'));
});
```

修改 app.js 之后启动服务器 应该使用 `$ node app.js` 启动服务了把, 不再使用 `$ bin/www` 

但是后面 介绍 supervisor 时候 却是  `$ supervisor ./bin/www`

>注意：每次我们更新代码后，都需要手动停止并重启应用，使用 supervisor 模块可以解决这个问题，每当我们保存修改的文件时，supervisor 都会自动帮我们重启应用。通过：

>$ npm install -g supervisor
安装 supervisor 。使用 supervisor 命令启动 app.js：

>$ supervisor ./bin/www

**Comment by nswbmw** [comment]
已修改 : )
https://github.com/nswbmw/N-blog/wiki/%E7%AC%AC1%E7%AB%A0--%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E5%8D%9A%E5%AE%A2/_compare/13be0b94ef42657c7448063b840d3065c4803650...54f5bff903ea3c6c5b65bafa63358be0c3155cf2
