### ISSUE TITLE
KindEditor 上传图片怎么处理呢

### ISSUE THREAD

**Issue by raclen** [nswbmw/N-blog#103]
请问下，我看了这个https://github.com/nswbmw/N-blog/wiki/%E7%95%AA%E5%A4%96%E7%AF%87%E4%B9%8B%E2%80%94%E2%80%94%E4%BD%BF%E7%94%A8-KindEditor
是在线图片，怎么上传呢

**Comment by djlxiaoshi** [comment]
KindEditor.ready(function(K) {
      editor = K.create('textarea', {
      allowImageUpload : true,
      cssData: 'body {font-family: "微软雅黑"; font-size: 16px}  pre{background:#e5e5e5} img{max-width:100%}',//设置默认字体
      uploadJson: '/uploadImg',//设置action  请求路径  图片上传就会通过这个请求
//          uploadJson: '/ueditor/ue',
      resizeType : 0,   //编辑区域大小禁止改变
      items : [
        'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic',
        'underline', 'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright',
        'insertorderedlist', 'insertunorderedlist', '|', 'emoticons', 'image','code', 'link','fullscreen']
      });
    });

/*增加路由  我这里用了formidable表单处理的插件
json文件里面增加  "formidable": "1.0.16",
*/

var formidable = require('formidable');
app.post('/uploadImg', function(req, res, next) {
		    var form = new formidable.IncomingForm();
		    form.keepExtensions = true;
		    form.uploadDir = __dirname + '/../public/upload';
		    form.parse(req, function (err, fields, files) {
		        if (err) {
		            throw err;
		        }
		        var image = files.imgFile;
		        var path = image.path;
		        path = path.replace(/\\/g, '/');   //替换成标准路径，正则表达式不要用引号
		        var url = '/upload' + path.substr(path.lastIndexOf('/'), path.length);  //linux下是/  windows下是\  解决路径统一问题
		        var info = {
		            "error": 0,
		            "url": url
		        };
		        res.send(info);
		    });
		});


你也可以直接到我的github下面看具体的https://github.com/djlxiaoshi/blog

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
