### ISSUE TITLE
第一章中的Mongodb问题

### ISSUE THREAD

**Issue by fineday009** [nswbmw/N-blog#104]
原文部分：
【连接MongoDB

数据库虽然安装并启动成功了，但我们需要连接数据库后才能使用数据库。怎么才能在 Node.js 中使用 MongoDB 呢？我们使用官方提供的 node-mongodb-native 驱动模块，打开 package.json，在 dependencies 中添加一行：

"mongodb": "1.4.15"
然后运行 npm install 更新依赖的模块，稍等片刻后 mongodb 模块就下载并安装完成了】

在我的windows x64机器上， 在package.json里配置好之后，npm install环节报错：

npm ERR! notarget No compatible version found: mongodb@'>=3.0.8-0 <3.1.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.4","0.9.4-4","0.9.3","0.9.1","0.9.2","0.9.6-7","0.9.6-8","0.9.6-9","0.9.6-10","0.9.6-11","0.9.6-12","0.9.6-13","0.9.6-14","0.9.6-15","0.9.6-16","0.9.6-17","0.9.6-18","0.9.6-19","0.9.6-20","0.9.6-21","0.9.6-22","0.9.6-23","0.9.7","0.9.7-0","0.9.7-1","0.9.7-1.1","0.9.7-1.2","0.9.7-1.3","0.9.7-1.4","0.9.7-2","0.9.7-2-1","0.9.7-2-2","0.9.7-2-3","0.9.7-2-4","0.9.7-2-5","0.9.7-3","0.9.7-3-1","0.9.7-3-2","0.9.7-3-3","0.9.7-3-4","0.9.7-3-5","0.9.8","0.9.8-1","0.9.8-2","0.9.8-3","0.9.8-4","0.9.8-5","0.9.8-6","0.9.8-7","0.9.9","0.9.9-1","0.9.9-2","0.9.9-3","0.9.9-4","0.9.9-5","0.9.9-6","0.9.9-7","0.9.9-8","1.0.0","1.0.1","1.0.2","1.1.0-beta","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.1.8","1.1.9","1.1.10","1.1.11","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","1.2.5","1.2.6","1.2.7","1.2.8","1.2.9","1.2.10","1.2.11","1.2.12","1.2.13","1.2.14","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5","1.3.6","1.3.7","1.3.8","1.3.9","1.3.10","1.3.11","1.3.12","1.3.14","1.3.15","1.3.17","1.3.18","1.3.19","1.4.0-rc2","1.3.20","1.4.0-rc3","1.3.21","1.3.22","1.3.23","1.4.0-rc4","1.4.0-rc5","1.4.0-rc6","1.4.0-rc7","1.4.0-rc8","1.4.0-rc9","1.4.0-rc10","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.4.9","1.4.10","2.0.0-alpha1","1.4.11","1.4.12","1.4.14","1.4.15","1.4.16","1.4.17","2.0.0-alpha2","1.4.18","2.0.0","2.0.1","2.0.2","1.4.19","2.0.3","2.0.4","2.0.5","2.0.6","1.4.20","1.4.22","2.0.7","2.0.8","2.0.9","1.4.23","2.0.10","1.4.24","2.0.11","1.4.25","2.0.12","1.4.26","1.4.27","1.4.28","2.0.13","2.0.14","1.4.29","2.0.15","1.4.30","2.0.16","1.4.31","2.0.17","1.4.32","2.0.18","2.0.19","1.4.33","2.0.20","2.0.21","1.4.34","2.0.22","2.0.23","1.4.35","2.0.24","2.0.25","2.0.26","2.0.27","2.0.28","2.0.29","1.4.36","2.0.30","1.4.37","2.0.31","1.4.38","2.0.32","2.0.33","2.1.0-alpha","2.0.34","2.0.35","2.0.36","2.0.37","2.0.38","2.0.39","1.4.39","2.0.40","2.0.41","2.0.42","2.0.43","2.0.44","2.0.45","2.0.46","2.0.47","2.0.48","2.1.0-rc1","2.0.49","2.0.50","2.1.0","2.0.51","2.1.1","2.0.52"]

Someone help me !!! 谢谢！

**Comment by fineday009** [comment]
我的mongodb是3.0.8版本,按照书上所说已经安装成

**Comment by fineday009** [comment]
运行npm install 报上面的错。

**Comment by fineday009** [comment]
ps：我在mongodb官网下载了压缩版，并按照书上流程走了是没问题的。

就在这最后一步出的问题。

**Comment by JSlife23** [comment]
Failed to load c++ bson extension, using pure JS version
Tue, 22 Dec 2015 15:06:09 GMT express-session deprecated undefined resave option; provide resave option at app.js:17:9
Tue, 22 Dec 2015 15:06:09 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:17:9
Tue, 22 Dec 2015 15:06:09 GMT express-session deprecated req.secret; provide secret option at app.js:17:9

我的报了一个什么C++ extension load失败

**Comment by fineday009** [comment]
书上写的【"mongodb": "1.4.15"】，而我当时填的不是1.4.15， 填的什么版本号记不清了，关键我仿照我本机package.json文件上方的一些写法在版本号前面加了~。

为此查看了官网关于package.json的文档，https://docs.npmjs.com/files/package.json

找到相关说明：
version Must match version exactly
>version Must be greater than version
>=version etc
<version
<=version
~version "Approximately equivalent to version" See semver
^version "Compatible with version" See semver
1.2.x 1.2.0, 1.2.1, etc., but not 1.3.0
http://... See 'URLs as Dependencies' below
* Matches any version
"" (just an empty string) Same as *
version1 - version2 Same as >=version1 <=version2.
range1 || range2 Passes if either range1 or range2 are satisfied.


不知道是不是这个~符号惹的祸，它表示所写版本附近的版本号都会考虑。
后来我在另外一台机器去掉~结果好了。  这章的其他问题也都解决了，只是这个example还是有点粗糙，感觉可以作为node入门。
