### ISSUE TITLE
第一章连接mongodb出现的问题

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#105]
执行npm start时报如下错误
![default](https://cloud.githubusercontent.com/assets/12546897/11911792/b57aedca-a65c-11e5-9b31-7f87bb250630.png)
![2](https://cloud.githubusercontent.com/assets/12546897/11911796/d084f7d2-a65c-11e5-8ee5-c36fcca9dd0f.png)
‘Connection strategy not found‘
package.json
{
  "name": "blog",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "connect-mongo": "^1.0.1",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.3.3",
    "express": "~4.13.1",
    "express-session": "^1.12.1",
    "mongodb": "^2.0.52",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }
}

**Comment by wulanhada** [comment]
我也遇到同样的问题 ，关注中。
{
  "name": "blog",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.3.3",
    "express": "~4.13.1",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0",
    "mongodb": "2.1",
    "express-session": "1.12.1",
    "connect-mongo": "1.0.1"
  }
}

**Comment by githubmann** [comment]
开mongod服务了吗

**Comment by wulanhada** [comment]
开了

**Comment by wulanhada** [comment]
在各种试的过程中发现 
var dbUrl = "mongodb://" + settings.host + "/" + settings.db;

app.use(session({
resave: false,
saveUninitialized: true,
secret: settings.cookieSecret,
key: settings.db,
cookie: {

maxAge: 1000 * 60 * 60 * 24 * 30
},
store: new MongoStore({

url: dbUrl
})
}));
这样就可以正常连接数据库，并运行正常。有人能解释么？

**Comment by githubmann** [comment]
你改了什么

**Comment by wulanhada** [comment]
就把
store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
改成
store: new MongoStore({
    url: "mongodb://" + settings.host + "/" + settings.db
  })
这样就可以正常连接了

**Comment by achewink** [comment]
connect-mongo 有說明如何 new 新的 connection
new MongoStore 裡面包的應該要是個 url
所以應該改放 url 在裡面，如：
new MongoStore: { url: 'your_db_url'}
參考: https://github.com/kcbanner/connect-mongo#create-a-new-connection-from-a-mongodb-connection-string

**Comment by nswbmw** [comment]
最新版 connect-mongo api有变动，wiki中已添加注释说明
