### ISSUE TITLE
请教一下,目前这个项目对于版本依赖的正确配置

### ISSUE THREAD

**Issue by coolzc** [nswbmw/N-blog#106]
对照wiki教程第一章在进行reg注册跳转到主页的过程中，出错。
检查了代码的正确性，也没问题，后来索性将教程里的代码原封不动的复制黏贴，也还是不行。
所以我想可能是版本依赖的问题，看了其他issues的问题也都集中在以下几个库的上面，想问一下大家是否能够提供下能跑起来的依赖，谢谢。
  "dependencies": {
    "express": "4.10.2",
    "body-parser": "1.9.0",
    "cookie-parser": "1.3.3",
    "morgan": "1.3.1",
    "serve-favicon": "2.1.5",
    "ejs": "1.0.0",
    "markdown": "0.5.0",
    "mongodb": "1.4.15",
    "express-session": "1.9.1",
    "connect-flash": "0.1.1",
    "connect-mongo": "0.4.1",
    "multer": "0.1.6"
  }

**Comment by coolzc** [comment]
"express-session" : "~1.12.1",
    "connect-mongo" : "~0.8.1",
    "connect-flash" : "~0.1.1"
修改如上依赖包，然后把以下代码按照以下顺序排列即可,  
app.use(session({
  secret: settings.cookieSecret,
  key: settings.db,//cookie name
  cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},//30 days
  store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
}));

app.use(flash());

routes(app);

**Comment by nswbmw** [comment]
报错信息贴出来？

**Comment by coolzc** [comment]
啊，不好意思，解决了，忘记贴了，因为有一些是我上述代码顺序产生的错误，不过发现"multer": "0.1.6"  第3章 增加文件上传功能用到库版本更新到最新的话，似乎这个库的代码需要改一改，用法变了。(也有可能是我不会用的缘故。。。)

**Comment by nswbmw** [comment]
ok
