### ISSUE TITLE
第一章发表文章报错

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#107]
![default](https://cloud.githubusercontent.com/assets/12546897/11992908/49ea9ac0-aa66-11e5-9dde-17714faa695d.png)
index.js文件
router.get('/post', checkNotLogin);
router.get('/post', function (req, res) {
  res.render('post', { 
    title: '发表',
     user: req.session.user,
     success: req.flash('success').toString(),
      error: req.flash('error').toString()
    });
});

router.post('/post', checkLogin);
router.post('/post', function (req, res) {
    var currentUser = req.session.user,
           post = new Post(req.body.post);

```
post.save(function (err) {
  if (err) {
    req.flash('error', err);
    return res.redirect('/');
  } 
  req.flash('success', '发布成功!');
  res.redirect('/');
});
```

});
index.html文件
<% include header.html %>
<% posts.forEach(function (post, index) { %>
  <p><h2><a href="#"><%= post.title %></a></h2></p>
  <p class="info">
    作者：<a href="#"><%= post.name %></a> | 
    日期：<%= post.time.minute %> | 
  </p>
  <p><% post.post %></p>
  <% }) %>
<% include footer.html %>

**Comment by githubmann** [comment]
贴一下你checkNotLogin的代码

**Comment by githubmann** [comment]
不是router.get('/post', checkNotLogin); 而是router.get('/post', checkLogin)，你试一下

**Comment by hank2015** [comment]
谢谢了，可以发表文章了，是什么原因导致的错误阿？

**Comment by githubmann** [comment]
贴一下你的router.get('/post', checkNotLogin)代码，用markdown格式

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
