### ISSUE TITLE
服务器可以起来，{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by Hibettermeatom** [nswbmw/N-blog#109]
> N-blog@1.0.0 start /home/tblog
> node app

Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
morgan deprecated morgan(options): use morgan("default", options) instead app.js:27:9
morgan deprecated default format: use combined format app.js:27:9
express-session deprecated undefined resave option; provide resave option app.js:36:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:36:9
Express server listening on port 3000

**Comment by vtangdg** [comment]
![image](https://cloud.githubusercontent.com/assets/10526297/12003222/ee2858c6-ab50-11e5-9729-5db32b722812.png)
应该是这里的问题，没有对应的文件

**Comment by chenlocus** [comment]
把/build/Release/bson改成/browser_build/Release/bson就可以运行了。
在我这里已经ok了。
