### ISSUE TITLE
為何買書照步驟做下來..每次都不成功

### ISSUE THREAD

**Issue by jandacreate** [nswbmw/N-blog#110]
出版以前到底有沒有過一次阿?
遇到一堆問題都要上國外網站找答案~
這樣買實體書到底有什麼意義?
根本無法在書裡面學到扎實的技術~
爛透了

**Comment by nswbmw** [comment]
书上的案例的确有点老了，楼主还能上国外的网站自己找到解决方法，不错不错～

**Comment by hank2015** [comment]
无论跟着哪个教程学都都会遇到问题的

**Comment by nateliu** [comment]
如果书上的内容一跑就成功了，跟阅读小说就没有什么区别了。

**Comment by jandacreate** [comment]
書裡自己寫的model都無法實現.那買書要幹嘛??上網學就好.

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
