### ISSUE TITLE
第三章 增加文件上传功能报错

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#111]
![2015-12-29 15-42-31](https://cloud.githubusercontent.com/assets/12546897/12031157/b41aaabc-ae43-11e5-93a4-f6511dc7dbeb.png)
![2015-12-29 15-42-55](https://cloud.githubusercontent.com/assets/12546897/12031167/d8451b02-ae43-11e5-9497-230a97cb536d.png)

**Comment by vtangdg** [comment]
可能是你用的multer的版本的问题，新版本的multer的用法和原来不一样了:
[multer npm](https://www.npmjs.com/package/multer)
[multer github](https://github.com/expressjs/multer) 
用法比如：
```javascript
var multer = require('multer');
var storage = multer.diskStorage({
  destination: './public/images/',
  filename: function (req, file, cb) {
    cb(null, file.originalname);
  }
});
var upload = multer({storage: storage});
router.post('/upload', upload.single('file1'), function (req, res) {
    req.flash('success', '文件上传成功!');
    res.redirect('/upload');
});
```

**Comment by hank2015** [comment]
这是仿照教程写的
app.js:
var multer = require('multer');
index.js:
router.get('/upload', checkLogin);
router.get('/upload', function (req, res) {
  res.render('upload', {
    title: '文件上传',
    user: req.session.user,
    success: req.flash('success').toString(),
    error: req.flash('error').toString()
  });
});
router.post('/upload', checkLogin);
router.post('/upload', function (req, res) {
    req.flash('success', '文件上传成功!');
    res.redirect('/upload');
});

**Comment by SinalVee** [comment]
multer版本问题，教程里用的是0.1.6，最新版的用@vtangdg 说的方式

**Comment by hank2015** [comment]
旧的问题没解决，新的问题又出现了
![2016-01-06 10-11-15](https://cloud.githubusercontent.com/assets/12546897/12133222/26788b2c-b45e-11e5-81e4-3013d9c2519b.png)
![2016-01-06 10-11-44](https://cloud.githubusercontent.com/assets/12546897/12133224/2d72ac50-b45e-11e5-979f-31049fbe6e7c.png)
把multer删除后报这个错

**Comment by SinalVee** [comment]
你这是看教程不仔细啊，router怎么可能会写getAll，getAll是在posts model中写的

**Comment by hank2015** [comment]
把router.get改过来了，新的错误又出现了
![2016-01-06 15-39-46](https://cloud.githubusercontent.com/assets/12546897/12137457/c208c642-b48b-11e5-9450-74f448d2a8ae.png)
这是写的代码:
/* GET index page. */
router.get('/', function (req, res) {
    Post.get(null, function (err, posts) {
      if (err) {
        posts = [];
      }
      res.render('index', { 
      title: '主页',
      user: req.session.user,
      posts: posts,
      success: req.flash('success').toString(),
      error: req.flash('error').toString()
    });
  });
});

**Comment by SinalVee** [comment]
@hank2015 看错误信息，`Post.get is not a function`，说明Post.get有问题，去`models/post.js`里找错，你是不是把`Post.get`写成了`Post.prototype.get`？

**Comment by hank2015** [comment]
是的，我把Post.get写成了Post.getAll了，谢谢你的帮助

**Comment by hank2015** [comment]
点击发表的文章没有反应，不显示内容
![2016-01-07 17-27-46](https://cloud.githubusercontent.com/assets/12546897/12166930/1ebfaf58-b564-11e5-8fe4-6a97c19fa4f3.png)

**Comment by jypblue** [comment]
按照教程上传，发现没有其效果。图片没上传成功，启动使用的supervisor www

**Comment by lrspace** [comment]
我使用multer v1.1.0，把@vtangdg答案中的destination部分稍微修改下就上传成功了


```javascript
var storage = multer.diskStorage({
    destination: function (req,file,cb) {
        cb (null,'./public/images');
    },
    filename: function (req,file,cb) {
        cb (null,file.originalname);
    }
});
```

**Comment by HBXSZ** [comment]
@lrspace 上传图片后能够在images文件夹里看见新上传的图片，怎么在自己的文章里插入图片？看教程上写的[] (/images/1.jpg) 没有用

**Comment by lrspace** [comment]
@HBXSZ images里面有图片的话，在post文章的时候使用markdown语法：
```
![](/images/1.jpg)
```
应该就能插入图片
![2](https://cloud.githubusercontent.com/assets/6268168/13977877/90f0a184-f107-11e5-91b5-fb194d4f3863.jpg)
![image](https://cloud.githubusercontent.com/assets/6268168/13977904/bfb004d8-f107-11e5-8e15-731c77a5b36c.png)

**Comment by HBXSZ** [comment]
@lrspace  搞定了= =自己忘记加前面的感叹号了 囧0.0..

**Comment by ihaichao** [comment]
还有一个很重要的问题，自己摸索了半天才解决。
`upload.single(<NAME>)`中的`<NAME>`要和 upload.ejs 中 `<input type="file" name="<NAME>" ...>`的`<NAME>`保持一致，否则也会导致上传文件失败。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
