### ISSUE TITLE
第6章 启动服务器时报Unexpected token new

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#114]
![2016-01-08 18-13-11](https://cloud.githubusercontent.com/assets/12546897/12195626/8743f21c-b633-11e5-9a56-4554b1eea169.png)
index.js
router.post('/u/:name/:day/:title', function (req, res) {
  var date = new Date(),
         time = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate() + " " +
                     date.getHours() + ":" + (date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes());
  var comment = {
         name: req.body.name,
         email: req.body.email,
         website: req.body.website,
         time: time,
         content: req.body.content
  };
var new Comment = new Comment(req.params.name, req.params.day, req.params.title, comment);
newComment.save(function (err) {
  if (err) {
    req.flash('error', err);
    return res.redirect('back');
  }
  req.flash('success', '留言成功!');
  res.redirect('back');
});  
});

**Comment by la413972057** [comment]
```
var new Comment = new Comment(req.params.name, req.params.day, req.params.title, comment);//var newComment.....你多了个空格
```

**Comment by hank2015** [comment]
好的，谢谢

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
