### ISSUE TITLE
报错"head is not defined"

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#115]
做完番外篇之——使用 _id 查询后，试着发表一篇文章，启动npm start报这个错
![2016-01-12 11-04-26](https://cloud.githubusercontent.com/assets/12546897/12253671/4c49c4de-b91c-11e5-9635-8acd0034a94f.png)
![2016-01-12 11-05-13](https://cloud.githubusercontent.com/assets/12546897/12253685/628fb60e-b91c-11e5-9420-1ec3ab5d1f50.png)

**Comment by hank2015** [comment]
博主，麻烦看一下我的报错"head is not defined"

**Comment by nswbmw** [comment]
贴一下 models/post.js

**Comment by hank2015** [comment]
var ObjectID = require('mongodb').ObjectID;

var mongodb = require('./db');
       markdown = require('markdown').markdown;

function Post (name, title, tags, post) {
	this.name = name;
	this.head = head;
	this.title = title;
	this.tags = tags;
	this.post = post;
}

module.exports = Post;

Post.prototype.save = function(callback) {
	var date = new Date();
	var time = {
		date: date,
		year: date.getFullYear(),
		month: date.getFullYear() + "-" + (date.getMonth() + 1),
		day: date.getFullYear() +"-" + (date.getMonth() + 1) + "-" + date.getDate(),
		minute: date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate() + "" +
		date.getHours() + ":" + (date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes()) 
	}
	var post = {
	       name: this.name,
	       head: this.head,
	       time: time,
	       title: this.title,
	       tags: this.tags,
	       post: this.post,
	       comments: [],
	       reprint_info: {},
	       pv: 0
	};
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.insert(post, {
				safe: true
			}, function (err) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null);
			});
		});
	});
};

Post.getTen = function(name, page, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			var query = {};
			if (name) {
				query.name = name;
			}
			collection.count(query, function (err, total) {
				collection.find(query, {
				    skip: (page - 1)*10,
				    limit: 10
			           }).sort({
				     time: -1
			           }).toArray(function (err, docs) {
				     mongodb.close();
				     if (err) {
					return callback(err);
				     }
				     docs.forEach(function (doc) {
					doc.post = markdown.toHTML(doc.post);
				     })
				     callback(null, docs, total);
			        });
			});
		
		});
	
	});

};

Post.getOne = function(_id, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.findOne({
				"_id": new ObjectID(_id)
			}, function (err, doc) {
			  if (err) {	
				mongodb.close();
				return callback(err);
				}
				if (doc) {
					collection.update({
						"_id": new ObjectID(_id)
					}, {
						$inc: {"pv": 1}
					}, function (err) {
						mongodb.close();
						if (err) {
							return callback(err);
						}
					});
					doc.post = markdown.toHTML(doc.post);
					doc.comments.forEach(function (comment) {
						comment.content = markdown.toHTML(comment.content);
					});
				callback(null, doc);
				}				
			});
		});
	});
};


Post.edit = function(name, day, title, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.findOne({
				"name": name,
				"time.day": day,
				"title": title
			}, function (err, doc) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null, doc);
			});
		});
	});
};

Post.update = function(name, day, title, post, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.update({
				"name": name,
				"time.day": day,
				"title": title
			}, {
				$set: {post: post}
			}, function (err) {
			   mongodb.close();
			   if (err) {
			      return callback(err);
			   }
			   callback(null);				
			});
		});
	});
};

Post.remove = function(name, day, title, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.findOne({
				"name": name,
				"time.day": day,
				"title": title
			},  function (err, doc) {
			if (err) {
                           mongodb.close();
                           return callback(err);
                          }
                          var reprint_form = "";
                          if (doc.reprint_info.reprint_form) {
                          	reprint_form = doc.reprint_info.reprint_form;
                          }
                          if (reprint_form != "") {
                          	collection.update({
                          		"name": reprint_form.name,
                          		"time.day": reprint_form.title
                          	}, {
                          		$pull: {
                          			"reprint_info.reprint_to": {
                          				"name": name,
                          				"day": day,
                          				"title": title
                          			}}
                          		}, function (err) {
                          			if (err) {
                          				mongodb.close();
                          				return callback(err);
                          			}
                          		});
                          	}
                          	collection.remove({
                          		"name": name,
                          		"time.day": day,
                          		"title": title
                          	}, {
                          		w: 1
                          	},function (err) {
                          		mongodb.close();
                          		if (err) {
                          			return callback(err);
                          		}
                          		callback(null);
                          	});                        
			});
		});
	});
};

Post.getArchive = function(callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.find({}, {
				"name": 1,
				"time": 1,
				"title": 1
			}).sort({
				time: -1
			}).toArray(function (err, docs) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null, docs);
			});
		});
	});
};

Post.getTags = function(callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.distinct("tags", function (err, docs) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null, docs);
			});
		});
	});
};

Post.getTag = function(tag, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.find({
				"tags": tag
			}, {
				"name": 1,
				"time": 1,
				"title": 1
			}).sort({
				time: -1
			}).toArray(function (err, docs) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null, docs);
			});
		});
	});
};

Post.search = function(keyword, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			var pattern = new RegExp(keyword, "i");
			collection.find({
				"title": pattern
			}, {
				"name": 1,
				"time": 1,
				"title": 1
			}).sort({
				time: -1
			}).toArray(function (err, docs) {
				mongodb.close();
				if (err) {
					return callback(err);
				}
				callback(null, docs);
			});
		});
	});
};

Post.reprint = function(reprint_form, reprint_to, callback) {
	mongodb.open(function (err, db) {
		if (err) {
			return callback(err);
		}
		db.collection('posts', function (err, collection) {
			if (err) {
				mongodb.close();
				return callback(err);
			}
			collection.findOne({
				"name": reprint_form.name,
				"time.day": reprint_form.day,
				"title": reprint_form.title
			}, function (err, doc) {
				if (err) {
					mongodb.close();
					return callback(err);
				}

				var date = new Date();
				var time = {
					date: date,
					year : date.getFullYear(),
					month : date.getFullYear() + "-" + (date.getMonth() + 1),
					day : date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate(),
					minute : date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate() + "" +
					date.getHours() + ":" + (date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes())
				}
				delete doc._id;

				doc.name = reprint_to.name;
				doc.head = reprint_to.head;
				doc.time = time;
				doc.title = (doc.title.search(/[转载]/) > -1) ? doc.title : "[转载]" + doc.title;
				doc.comments = [];
				doc.reprint_info = {"reprint_form": reprint_form};
				doc.pv = 0;

				collection.update({
					"name": reprint_form.name,
					"time.day": reprint_form.day,
					"title": reprint_form.title
				}, {
					$push: {
						"reprint_info.reprint_to": {
							"name": doc.name,
							"day": time.day,
							"title": doc.title
						}}
					}, function (err) {
						if (err) {
							mongodb.close();
							return callback(err);
						}
					});
				        collection.insert(doc, {
				        	safe: true
				        }, function (err, post) {
				        	mongodb.close();
				        	if (err) {
				        		return callback(err);
				        	}
				        	callback(err, post[0]);
				        });
			        });
		        });
	        });
        };

**Comment by rccoder** [comment]
@hank2015 
```javascript
function Post (name, title, tags, post) {
this.name = name;
this.head = head;
this.title = title;
this.tags = tags;
this.post = post;
}
```

不知道你找到错误没，Post 这是一个构造函数，你的形式参数里面没有`head`

**Comment by hank2015** [comment]
没明白什么意思

**Comment by hank2015** [comment]
this.head = head;
head在哪里定义啊？

**Comment by rccoder** [comment]
呃，少年先好好学习一下`javascript`吧


写成这样应该就可以了
```javascript
function Post (name, head, title, tags, post) {
  this.name = name;
  this.head = head;
  this.title = title;
  this.tags = tags;
  this.post = post;
}
```
