### ISSUE TITLE
番外篇之——使用 Disqus复制生成的代码运行后报错

### ISSUE THREAD

**Issue by hank2015** [nswbmw/N-blog#118]
![2016-01-16 11-26-47](https://cloud.githubusercontent.com/assets/12546897/12370246/9ebd1a1a-bc44-11e5-837b-a5a7747072f2.png)

**Comment by hank2015** [comment]
comment.js
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//blogger2015.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

**Comment by nswbmw** [comment]
粘贴到 comment.ejs 而不是 comment.js
