### ISSUE TITLE
第一章 mongodb Error: Error connecting to database: failed to connect to [127.0.0.1:27017]

### ISSUE THREAD

**Issue by shawushe** [nswbmw/N-blog#121]
数据库一类都按照教程安装并启动， 访问首页遇到这个问题 求指教
Error: Error connecting to database: failed to connect to [127.0.0.1:27017]

**Comment by superarm** [comment]
请检查是否流程出错，或者输入密码出错，可以根据提示码查询问题所在。

**Comment by shawushe** [comment]
已经解决，问题是mogodb版本问题
