### ISSUE TITLE
第15章 增加转载功能和转载统计

### ISSUE THREAD

**Issue by oceandeng** [nswbmw/N-blog#122]
Post.reprint = function(reprint_from, reprint_to, callback){
      ……
     //将转载生成的副本修改后存入数据库，并返回存储后的文档
                collection.insert(doc, {
                    safe: true
                }, function (err, post){
                    mongodb.close();
                    if(err){
                        return callback(err);
                    }
                    **_callback(null, post.ops[0]);**_
                })
}
- nodejs  -v  v5.0.0
-  "mongodb": "^2.1.4",
- mongodb-win32-x86_64-2008plus-ssl-3.2.1-signed.msi
- win7 64位

希望对大家能有帮助

**Comment by tangxiaolang101** [comment]
大神，这是为什么呀？我看到这里困惑了一下午 @oceandeng

**Comment by tangxiaolang101** [comment]
为什么这样写？ @nswbmw @oceandeng

**Comment by Boyceman** [comment]
@tangxiaolang101  你搞懂了么？为什么这样写

**Comment by LCINA** [comment]
@tangxiaolang101 @nswbmw  为什么这么写就可以了

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
