### ISSUE TITLE
第一章的req.flash报错

### ISSUE THREAD

**Issue by chenyan940206** [nswbmw/N-blog#126]
第一章的req.flash报错，
而且我加载了connect-flash
app.use(flash());也放在了app.use(session())之后，请问是什么原因，谢谢指导

**Comment by yaodehaung** [comment]
可以把以參考的第一章  資料
附在上面嗎

**Comment by honeypigs** [comment]
把 session 中的key 改成name 应该就可以了

**Comment by chenyan940206** [comment]
问题已经解决了，谢谢各位了。
代码顺序调整下，然后把"mongodb"&"connect-mongo"版本号更到最新。
