### ISSUE TITLE
第一章  index.js下的app.post('/login')问题

### ISSUE THREAD

**Issue by chenyan940206** [nswbmw/N-blog#128]
在密码错误时和用户不存在的情况下为什么用return res.redirect('/login');
为什么要有return，不加return的话res.redirect直接跳转就报错。
Error: Can't set headers after they are sent.

但是登录成功的res.redirect 就不用加return

**Comment by nswbmw** [comment]
return 是用来终止后面代码运行。最后登陆成功可以加也可以不加return
