### ISSUE TITLE
第一张connect-mongo的初始化需要改，否则报错。

### ISSUE THREAD

**Issue by zangqilong198812** [nswbmw/N-blog#129]
` store: new MongoStore({
    /*db: settings.db,
    host: settings.host,
    port: settings.port*/
    url: 'mongodb://localhost/blog'
  })`

改成url才行

**Comment by sunshineclt** [comment]
同意

**Comment by fumanduo2** [comment]
+1

**Comment by zmh7057** [comment]
原来如此，查了半天，sad

**Comment by nswbmw** [comment]
wiki上修改过来了
