### ISSUE TITLE
请问官网mongodb ZIP版并没有BIN目录

### ISSUE THREAD

**Issue by FatDonkey** [nswbmw/N-blog#131]
问个幼稚的问题，下的ZIP版3.2.4里没有BIN目录，应该从哪创建 blog  数据库

**Comment by yannliao** [comment]
先运行mongod 的daemon  再打开mongo...

**Comment by EasonWang01** [comment]
去Mongodb官網載mongodb套件，安裝後到你安裝的目錄裡即有bin資料夾

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
