### ISSUE TITLE
第一章直接下载你的代码运行报错

### ISSUE THREAD

**Issue by wangcityboy** [nswbmw/N-blog#133]
Failed to load c++ bson extension, using pure JS version
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
Wed, 30 Mar 2016 01:43:15 GMT morgan deprecated morgan(options): use morgan("default", options) instead at app.js:27:9
Wed, 30 Mar 2016 01:43:15 GMT morgan deprecated default format: use combined format at app.js:27:9
Wed, 30 Mar 2016 01:43:15 GMT express-session deprecated undefined resave option; provide resave option at app.js:36:9
Wed, 30 Mar 2016 01:43:15 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:36:9
Express server listening on port 3000

**Comment by Mrlilili** [comment]
npm 组建版本问题，你把你package.json发过来看看

**Comment by zll5131609** [comment]
下载代码，然后执行npm install，成功，再npm start，没有报错，但是在浏览器中访问localhost:3000则报错。
代码没有任何修改，直接下载的master分支。
求解！

E:\nodeWorkSpace\N-blog-master>npm start

> N-blog@1.0.0 start E:\nodeWorkSpace\N-blog-master
> node app

Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
morgan deprecated morgan(options): use morgan("default", options) instead app.js
:27:9
morgan deprecated default format: use combined format app.js:27:9
express-session deprecated undefined resave option; provide resave option app.js
:36:9
express-session deprecated undefined saveUninitialized option; provide saveUnini
tialized option app.js:36:9
Express server listening on port 3000
E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mongodb\l
ib\mongodb\connection\base.js:242
        throw message;
        ^

Error: Error setting TTL index on collection : sessions
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\lib\connect-mon
go.js:161:23
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mo
ngodb\lib\mongodb\db.js:1430:36
    at __executeInsertCommand (E:\nodeWorkSpace\N-blog-master\node_modules\conne
ct-mongo\node_modules\mongodb\lib\mongodb\db.js:1829:12)
    at Db._executeInsertCommand (E:\nodeWorkSpace\N-blog-master\node_modules\con
nect-mongo\node_modules\mongodb\lib\mongodb\db.js:1930:5)
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mo
ngodb\lib\mongodb\db.js:1427:14
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mo
ngodb\lib\mongodb\db.js:1560:7
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mo
ngodb\lib\mongodb\cursor.js:162:16
    at commandHandler (E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo
\node_modules\mongodb\lib\mongodb\cursor.js:706:16)
    at E:\nodeWorkSpace\N-blog-master\node_modules\connect-mongo\node_modules\mo
ngodb\lib\mongodb\db.js:1806:9
    at Server.Base._callHandler (E:\nodeWorkSpace\N-blog-master\node_modules\con
nect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:442:41)

**Comment by hechuanhua** [comment]
版本问题，提示不兼容，要把package.json里面的依赖组件全部更新到最新版就好了

**Comment by jddy** [comment]
E:\github\N-blog>node app.js
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\github\N-blog\node_modules\bson\ext\index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
listening on port 3000

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
