### ISSUE TITLE
MongoDB+Express4+EJS+BootStrap3+Node

### ISSUE THREAD

**Issue by nateliu** [nswbmw/N-blog#134]
跟着教程做了一遍，用Bootstrap重新做了一下布局，很好的教程。谢谢nswbmw的分享

忍不住要吐一下网络：
- gavatar不能用 
- heroku不能用
- mongoh本身就不再支持免费申请了的吧，所以我在mlab上面申请了一个。不过，反应奇慢。建议还是用localhost:27017

[源码地址在这里](https://github.com/nateliu/nblogs/tree/step06bootstrap)

**Comment by isClumsyBird** [comment]
@nateliu 你源码是在一个分支上，而`git clone`是下载的`master`上的，代码压根不全呀！

**Comment by eyeA** [comment]
你好，我也在想用bootstrap来布局下，coding中，向你学习！

**Comment by nateliu** [comment]
step06bootstrap是最后的代码。使用了bower管理前端资源。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
