### ISSUE TITLE
连接池 VERBOSE pool

### ISSUE THREAD

**Issue by ShinyLeee** [nswbmw/N-blog#135]
开启了log日志，最小连接为5，cmd里就会一直跳出VERBOSE冗余连接池，这样情况算是正常的？是因为暂时没用到连接才会跳出来的吗？

**Comment by nswbmw** [comment]
可以把警告日志关掉吧

教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
