### ISSUE TITLE
http://127.0.0.1:3000/ -----------Cannot GET / 

### ISSUE THREAD

**Issue by eyeA** [nswbmw/N-blog#136]
http://127.0.0.1:3000/ -----------Cannot GET / 
您好，我最近一直在学习您的教程

上午在边看教程边注释的时候  出现这样的错误：
http://127.0.0.1:3000/ -----------Cannot GET / 

盼望得到您的回复！
在线等...

**Comment by Mrlilili** [comment]
没有拿到内容，看看你路由那里是怎么样写的

**Comment by eyeA** [comment]
@Mrlilili 问题很奇怪，路由跟教程的一样，我甚至把他的文件直接复制，过来都不管用。
最后把文件覆盖，重复了下添加了下注释的工作，就好了。

**Comment by eyeA** [comment]
问题已经解决，谢谢~~~
