### ISSUE TITLE
加载connect-mongo模块时 出现 SyntaxError: Use of const in strict mode.求解答？

### ISSUE THREAD

**Issue by linweiscanyue** [nswbmw/N-blog#137]
【问题信息】
》问题提示信息：
/home/l/pj/wpj/meanS/blog_1/blog/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.

》问题出现说明：
在配置session的过程中，引用了connect-mongo 模块，在启动 DEBUG=blog:server node www 服务器时，出现上面情况。似乎是在加载该模块时出现了问题；

**问题**：## 想问，这是由模块之间的不兼容引起的吗？还是我的环境搭建有问题，请求大神解答？

【运行环境描述】
》相关版本信息：
     Node.js  : v0.10.37
     express : 4.13.1
     connect-mongo: 1.1.0
     express-session:1.13.0
     mongodb驱动模块:2.1.14
     mongodb数据库：v3.2.4

》安装情况：

```
express ： 安装在  /usr/lib/node_modules/express

自定义目录：/home/l/pj/wpj/meanS/blog_1/blog   
 （express 创建的工程目录都在自定义目录下；）

 connect-mongo:自定义目录的node_modules
 mongodb驱动: 同上；
 express-session: 同上；

 Mongodb数据库服务:
    该工程用到的数据库目录 ： /home/l/pj/wpj/meanS/blog_1/blog_db/db
      整个实验是在Mongod 服务启动时执行的；
      Mongod  --dbpath=/home/l/pj/wpj/meanS/blog_1/blog_db/db
```

【代码调用情况】
》app.js 中引用情况：
    var session = require('express-session');
    var MongoStore = require('connect-mongo')(session);
    var settings = require('./settings');

   app.use(session({
           secret: settings.cookieSecret,
           key: settings.db,//cookie name
           cookie: {maxAge: 1000 \* 60 \* 60 \* 24 \* 30},//30 days
           store: new MongoStore({
                   db: settings.db,
                   host: settings.host,
                   port: settings.port
           })
    }));

**Comment by zhaocy** [comment]
我也遇到了这样的问题，请问你是怎么解决的？
"connect-flash": "*",
    "connect-mongo": "^1.1.0",
    "ejs": "*",
    "express": "^3.4.4",
    "markdown": "*",
    "mongodb": "^2.1.16"

**Comment by Mrwaite** [comment]
var MongoStore = require('connect-mongo')(session);
改为
var MongoStore = require('connect-mongo/es5')(session);

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
