### ISSUE TITLE
Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by amoyzhu** [nswbmw/N-blog#138]
I do Upgrade connect-mongo to  version 0.8.0  then  it work up.

**Comment by a1exlism** [comment]
>参照 https://cnodejs.org/topic/53e1ff41a3df2b8f3114132e
将mongodb和connect-mongo都跟新到最新版本
在package.json修改
"mongodb"：“2.0.42”，
“connect-mongo”:“0.8.2”

**Comment by Shiotsuki** [comment]
@a1exlism 这样做npm会提示invalid是什么意思

**Comment by gzq-studyios** [comment]
以上的方法不行啊，你们解决了吗？

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
