### ISSUE TITLE
运行你的程序出错

### ISSUE THREAD

**Issue by youthchinagirl** [nswbmw/N-blog#139]
运行你的程序出错，npm版本为3.8.3。nodejs版本为5.10.1。pagckage.json 采用你的。update npm packages后运行也出错。
mater分支和express4.0分支运行都出错
 Failed to load c++ bson extension, using pure JS version
morgan deprecated morgan(options): use morgan("default", options) instead app.js:27:9
morgan deprecated default format: use combined format app.js:27:9
express-session deprecated undefined resave option; provide resave option app.js:36:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:36:9

**Comment by zhangjh** [comment]
以上并没有看到有报错信息，只是说某些依赖问题，应该不会影响运行

**Comment by zll5131609** [comment]
我这边也是报了这个错，server起不来
E:\nodeWorkSpace\blog-test\blog>node app
Failed to load c++ bson extension, using pure JS version
express-session deprecated undefined resave option; provide resave option app.js
:65:9
express-session deprecated undefined saveUninitialized option; provide saveUnini
tialized option app.js:65:9

E:\nodeWorkSpace\blog-test\blog>

我的packageJson：
{
  "name": "blog",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node app"
  },
  "dependencies": {
    "body-parser": "1.9.0",
    "cookie-parser": "1.3.3",
    "debug": "~2.2.0",
    "ejs": "1.0.0",
    "express": "4.10.2",
    "morgan": "1.3.1",
    "serve-favicon": "2.1.5",
    "mongodb":"1.4.15",
    "express-session": "1.9.1",
    "connect-mongo": "0.4.1"
  }
}

**Comment by yidongwuxian** [comment]
"scripts": {
    "start": "node app.js"
  },

**Comment by jddy** [comment]
https://github.com/jddy/xiaoqiang/wiki/N-blog-window%E7%8E%AF%E5%A2%83%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3

补充一个出错的问题，请叫我雷锋。

**Comment by XiomgMingCai** [comment]
/Users/xiongmingcai/GitHub/N-blog/package.json
connect-mongo": "0.8.0"
找了好久的报错! 把这个版本修改下


**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
