### ISSUE TITLE
I cannot see flash message on my webpage

### ISSUE THREAD

**Issue by dongyu2015** [nswbmw/N-blog#142]
session 设置好 以后 登录时候出错还有没有用户等需要提示flash message的内容都不能显示。

但是功能可以实现，用户登录成功数据库也可以找到。请问是什么问题。

而且是所有的flash message都不提示。

其中一段代码如下：

app.post('/login', function (req, res) {
    var md5 = crypto.createHash('md5'),
        password = md5.update(req.body.password).digest('hex');
    User.get(req.body.name, function (err, user) {
      if (!user) {
        req.flash('error', 'user not found!');

```
    return res.redirect('/login');
  }
  if (user.password != password) {
    req.flash('error', '密码错误!');
    return res.redirect('/login');
  }
  req.session.user = user;
  req.flash('success', '登陆成功!');
  res.redirect('/');
});
```

  });

**Comment by rccoder** [comment]
@dongyu2015  你的 template 里面是怎么写的？

**Comment by khuntoriia** [comment]
你好，我也遇到了同样的问题，没有报错，但是req.flash没有执行，请问你是怎么解决的呢？

**Comment by dongyu2015** [comment]
重新做了一遍


On Monday, June 20, 2016, khuntoriia <notifications@github.com> wrote:

> 你好，我也遇到了同样的问题，没有报错，但是req.flash没有执行，请问你是怎么解决的呢？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nswbmw/N-blog/issues/142#issuecomment-227080629>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALLu4DQKt86C8gf1r-DHuwO-Av3kkgJRks5qNk_5gaJpZM4IH5U4>
> .
>


-- 
Software Engieer
Phone: 937-286-1709
LinkedIn:https://www.linkedin.com/pub/dongyu-li/89/b04/a83
GitHub:https://github.com/dongyu2015

University of Dayton, Graduate Assistant

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
