### ISSUE TITLE
Cannot POST /posts

### ISSUE THREAD

**Issue by TreeSun** [nswbmw/N-blog#143]
`app.post('/posts', checkLogin);
    app.post('/posts', function (req, res) {
        console.log("数据",res.body);//打印回应信息
        var currentUser = req.session.user,
            post = new Post(
                currentUser.name,
                currentUser.head,
                req.body.title,
                req.body.startDate,
                req.body.endDate,
                req.body.content,//内容
                req.body.money,
                req.body.place
            );
        post.save(function (err) {
            if (err) {
                req.flash('error', err);
                console.log('error', err);//输出错误信息
                return res.redirect('/posts');
            }
            req.flash('success', '发布成功!');
            res.redirect('/');//发表成功跳转到主页
        });
    });
`
页面
`<form action="/posts" method="post" >
                    <input type="text" name="title" placeholder="为游记起一个有趣的名字"/><br />
                    <div class="laydate-box">
                        <span>开始日：</span><input class="laydate-icon" id="start" name="startDate"></input>
                        <span>结束日：</span><input class="laydate-icon" id="end" name="endDate"></input>
                    </div>
                    <input type="text" name="place" placeholder="行走地点"/><i class="fa fa-map-marker"></i><br />
                    <textarea class="form-control" name="content"  rows="20" cols="100"></textarea><br />
                    <input type="text" name="money" placeholder="总花费"/><i class="fa fa-money"></i><br/>
                    <input type="submit" value="发表"  id="publish"/>
                </form>`

为什么post不了啊！

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
