### ISSUE TITLE
希望能更新代碼

### ISSUE THREAD

**Issue by Edenharder** [nswbmw/N-blog#145]
代碼已經很久沒更新了，直接下載運行各種錯誤改不過來，這對小白來說是很痛苦也不一定能解決的。目前能直接用的是[ getElement 的代碼](https://github.com/getElement/blog)，然而他也不維護了。可參見[他的讀書筆記](http://www.w3cfuns.com/house/18621/note/class/id/cc159ad199326caedaaaf48b7cc20116.html)，但太簡略了，也很難看出所以然。

最詳盡的還是這裏，希望能更新代碼。

**Comment by mistkafka** [comment]
@Edenharder 你好！請問你都遇到什麼問題呢？建議使用教程中對應的版本，這樣應該沒問題的！另外，教程這東西其實主要看過程，你看懂了作者要做什麼，推薦了什麼package，你可以自己去嘗試實現對應的功能。

**Comment by Edenharder** [comment]
@mistkafka 謝謝你的回覆！都是和mongod有關的一些問題。

**Comment by gdhzkk** [comment]
@Edenharder  你也可以试试firekylin

**Comment by Edenharder** [comment]
@gdhzkk 謝謝！firekylin有自帶的留言系統嗎？

**Comment by gdhzkk** [comment]
@Edenharder 没有，很简洁的一个博客，基于thinkjs开发的

**Comment by gdhzkk** [comment]
@Edenharder 地址在这https://github.com/75team/firekylin

**Comment by Edenharder** [comment]
@gdhzkk 謝謝，你爲什麼不推薦自己的ourjs呢？

**Comment by gdhzkk** [comment]
@gdhzkk 那不是我的  我收藏的

**Comment by gdhzkk** [comment]
@Edenharder 那是我收藏的

**Comment by gaoxiaosong1113** [comment]
感觉还好，我这边搭建成功了，而且换了样式，就是有些地方报错真心看不懂！！

**Comment by vnexus** [comment]
同样是mongodb出错

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
