### ISSUE TITLE
关于第六章的实现留言功能doc.comments.forEach 报错，不能读取forEach，未定义

### ISSUE THREAD

**Issue by huanshen** [nswbmw/N-blog#147]
如题，显示forEach未定义，不能读取，其他没错的，就是不能转到文章页面去了

**Comment by 23wenyu** [comment]
重置数据库试下？

**Comment by TalkLee** [comment]
像楼上说的重置数据库，我是成功了。 @huanshen

**Comment by Geminiasen** [comment]
确实把数据库清空再重新注册就可以了，不知道是什么原因。

**Comment by Geminiasen** [comment]
我在第9章也遇到了同样的问题，清空数据库后就可以了。每次更新项目代码，原来mongoDB中的json格式的数据与代码跟新后的处理逻辑是不一样的，比如第9章代码中增加了处理tag的逻辑，但是数据库中的数据没有这个字段，当然会出错，清空数据库，重新插入数据就能解决这个问题了。

**Comment by neverlandzl** [comment]
这个问题是因为doc.comments为空，报的错误。
在post.js   doc.comments.forEach(function (comment)前面增加if(doc.comments)判断一下
在comment.ejs  <% post.comments.forEach(function (comment, index) { %>前面增加<% if (post.comments) { %>判断一下
这样就可以解决问题，不必清除数据库，有评论的和没有评论的文章都可以正常打开

**Comment by shawn-jdd** [comment]
如果是直接下载代码的，说明没数据

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
