### ISSUE TITLE
我在第一章注册时遇到这个问题，不知道如何解决

### ISSUE THREAD

**Issue by zzm1220** [nswbmw/N-blog#148]
Error: req.flash() requires sessions
我在第一章注册时会报这个错，应该如何解决呢，求解答，非常感谢

**Comment by XIAOBOY** [comment]
//引入 flash 模块来实现页面通知
var flash = require('connect-flash');//req.flash()使用
app.use(flash());//定义使用 flash 功能

**Comment by cqgsm** [comment]
app.use(require('cookie-session')({
  secret: 'secret'
})) 
app.use(require('flash'))
要放在session下面

**Comment by dengshasha** [comment]
我也遇到这个问题了，其实很简单的，你要把app.use(flash())放在

**Comment by dengshasha** [comment]
我也遇到这个问题了，其实很简单的，你要把app.use(flash())放在
app.use(session({
	secret:settings.cookieSecret,//防止篡改cookie
	key:settings.db,//cookie的名字
	。。。
}))

的后面！！然后就不会报错了

**Comment by dgutyanghs** [comment]
我也遇到了同样问题，将下面代码放在app.js的最上面可以解决：
`var app = express();
app.use(flash());
app.use(session({
    resave:true,
    saveUninitialized:true,
    secret:settings.cookieSecret,
    key:settings.db,
    cookie:{maxAge:1000 * 60 * 24 * 30},
    store:new MongoStore({
        url: 'mongodb://localhost/blog'
    })
}));
`
同为初学者，具体原因不清楚，  希望作者有空指点迷津。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
