### ISSUE TITLE
TypeError: req.flash is not a function

### ISSUE THREAD

**Issue by cqgsm** [nswbmw/N-blog#149]
var flash = require('connect-flash');

app.use(session({
  secret: settings.cookieSecret, //加密sessionid字符串
  key: settings.db,//cookie name
  cookie: {maxAge: 1000 \* 60 \* 60 \* 24 \* 30},//30 days
  store: new MongoStore({
    url: 'mongodb://localhost/blog',
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
}));
app.use(flash());
怎么会报不是个函数呢，求解？

**Comment by cqgsm** [comment]
不好意思啊，太粗心了，这些东西我放到路由下面了，提到上面就ok了

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
