### ISSUE TITLE
cd blog && npm install 之后就一直无法下载完成

### ISSUE THREAD

**Issue by chy996633** [nswbmw/N-blog#151]
fetchMetadata -> network  - |#########################----------------------------------------------------------------------------------------------|
一直在转，不知是什么原因？

**Comment by a578242325** [comment]
按着步骤走 我做到第八章了 没什么问题 
首先你排查下 错误 cd blog 就进入当前文件夹 看看路径

**Comment by chy996633** [comment]
好的，我再试试~谢谢！

**Comment by vnexus** [comment]
应该是墙的问题 可以试试cnpm  google吧

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
