### ISSUE TITLE
nodejs读取mongodb返回数据到前台页面[object object]怎么解决？

### ISSUE THREAD

**Issue by yidongwuxian** [nswbmw/N-blog#152]
在models里的post.js 可以获取到docs
//读取文章及其相关信息
Post.get = function(username, callback) {
  //打开数据库
  mongodb.open(function (err, db) {
    if (err) {
      return callback(err);
    }
    //读取 posts 集合
    db.collection('posts', function(err, collection) {
      if (err) {
        mongodb.close();
        return callback(err);
      }
      var query = {};
      if (username) {
        query.username = username;
      }
      //根据 query 对象查询文章
      collection.find(query).sort({
        time: -1
      }).toArray(function (err, docs) {
        mongodb.close();
        if (err) {
          return callback(err);//失败！返回 err
        }
        //console.log(docs);
        callback(null,docs);//成功！以数组形式返回查询的结果
      });
    });
  });
};

router/index.js

var Post             = require('../models/post.js');

exports.all = function(app){
    app.get( '/', function( req, res ){
        Post.get(null, function(err, posts){
            if(err){
                posts = [];
            }
            res.render( 'issue/index', { 
                title: '首页',
                user: req.session.user,
                posts: posts,
                success: req.flash('success').toString(),
                error: req.flash('error').toString()
            });
        });
    });

在index.ejs首页前台显示<%- post.post %>  报[object Object]的错误，怎么办？
<% include ../common/header.ejs %>
<% posts.forEach(function(post,index){  %>

<p><h2><a href="#"><%= post.title %></a></h2></p>

<p class="info">
    作者：<a href="#"><%= post.username %></a> |
    日期：<%= post.time.minute %>
</p>

<p><%- post.post %></p>

<% }) %>
</article>

**Comment by yidongwuxian** [comment]
@all 这个后来我自己解决了，标注一下。
因为在mongodb的数据是
{
    "_id" : ObjectId("575abd9816fd57a0032c2485"),
    "username" : "wokeyi",
    "time" : {
        "date" : ISODate("2016-06-10T13:16:08.081Z"),
        "year" : 2016,
        "month" : "2016-6",
        "day" : "2016-6-10",
        "minute" : "2016-6-10 21:16"
    },
    "title" : "重新开始",
    "article" : {
        "title" : "重新开始",
        "post" : "努力，交友"
    }
}
在index.ejs应该选下一级，因为post集合里面的“article”下面还有“title”和“post”，而选择<%= post.article %>当然会报“[object Object]”的错误，选择<%= post.article.post %>就对了。

<% include ../common/header.ejs %>
<% posts.forEach(function(post,index){  %>
<p><h2><a href="#"><%= post.title %></a></h2></p>
<p class="info">
	作者：<a href="#"><%= post.username %></a> |
	日期：<%= post.time.minute %>
</p>
<p><%= post.article.post %></p>                  //这里有变化
<% }) %>

**Comment by AzirChen** [comment]
我也遇见过，记得好像清空数据库。

**Comment by AzirChen** [comment]
我也遇见过，貌似清空数据库可以解决。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
