### ISSUE TITLE
使用github第三方登录不太懂整个过程，我照着写了代码可是没有成功的感觉，但也没有报错

### ISSUE THREAD

**Issue by mzzq** [nswbmw/N-blog#154]
使用oAuth协议不是要先跳到第三方服务器上的登录页面吗？我的没有跳，而且点击登陆三个请求后就跳回了自己博客的/index页面，而且通过`failureRedirect:'/login',
    successRedirect:'/artical'`这里修改不起作用

**Comment by mzzq** [comment]
还有三个请求的状态码都是302

**Comment by shawn-jdd** [comment]
貌似这个是我从别人那儿弄来的，没法帮你了

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
