### ISSUE TITLE
学习第一章注册时，遇到了数据库查不到页面传回的数据问题

### ISSUE THREAD

**Issue by dengshasha** [nswbmw/N-blog#155]
我在注册界面注册一个账号，然后页面不会跳转，会仍然停留在注册界面并且清空我输入的数据，我去Mongodb数据库查询的时候也查不到users的数据，不知道是不是根本没有和数据库连上的问题啊？
可是我前面都是照着教程做的，也不知道怎么检测是否连接到数据库了，我是个小白，求指教啊

**Comment by ragrok** [comment]
把代码粘贴复制，有些地方大小写会忽略。我也遇到了这个问题，但是数据库有信息。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
