### ISSUE TITLE
部署HeroKu,链接mongo

### ISSUE THREAD

**Issue by xiDaiDai** [nswbmw/N-blog#156]
改成了：mongoose.createConnection("mongodb://master:master@ds019839.mlab.com:19839/jichao_blog");

为什么总是提示如下错误

E:\web\blog\node_modules\mongoose\node_modules\mongodb\lib\server.js:242
       process.nextTick(function() { throw err; })
                                     ^
Error: connect ECONNREFUSED 127.0.0.1:27017
   at Object.exports._errnoException (util.js:870:11)
   at exports._exceptionWithHostPort (util.js:893:20)
   at TCPConnectWrap.afterConnect [as oncomplete](net.js:1057:14)

**Comment by nswbmw** [comment]
你虽然改了配置，但报错中可以看到仍然连的本地 mongodb 啊

教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
