### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by eyeA** [nswbmw/N-blog#163]
按照教程  https://github.com/nswbmw/N-blog/wiki/%E7%AC%AC1%E7%AB%A0--%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E5%8D%9A%E5%AE%A2
做下来，产生如下错误 ：
TypeError: Cannot read property 'user' of undefined
请问如何解决

**Comment by shawn-jdd** [comment]
你是哪儿出错了
@eyeA

**Comment by eyeA** [comment]
@shawn-jdd 教程第一章节 做到最后 执行node app.js的时候，出错：
TypeError: Cannot read property 'user' of undefined
请问怎么解决呢 ？

**Comment by 2VCl1md** [comment]
D:\blog\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:757
      catch(err) { process.nextTick(function() { throw err}); }
                                                 ^
TypeError: Cannot set property 'user' of undefined.
我也是这样，不知道哪里出错了

**Comment by eyeA** [comment]
@shawn-jdd 你好，问题解决了~~~谢谢回复；
@2VCl1md   你好，请  [参考下这里](https://segmentfault.com/q/1010000006143101)

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
