### ISSUE TITLE
彻底修订计划

### ISSUE THREAD

**Issue by nswbmw** [nswbmw/N-blog#164]
本人多年前写的该教程，代码有不少疏漏或需要优化的地方，鉴于很多初学者依然使用本教程，近期将会彻底翻新一遍。

**Comment by jddy** [comment]
今年雨水多，这大楼值得翻修！

**Comment by wangduanduan** [comment]
以前道路不通，总是坑坑洼洼，然后就走不下去了。
期待新的教学楼。

**Comment by shawn-jdd** [comment]
是的，不过不影响学习思路

**Comment by clementine07** [comment]
正在学习N-blog-express4.x版本 ,,,

**Comment by yidongwuxian** [comment]
磕磕绊绊跟着教程学了2个月，刚学到第5章，各种坑各种不眠之夜呀，期待大楼翻修。

**Comment by cqgsm** [comment]
期待啊，希望大大能加入vuejs 从前端到后端一整套流程，非常感谢大大的教程

**Comment by nswbmw** [comment]
@cqgsm 考虑下

**Comment by cqgsm** [comment]
希望您发布新教超的时候，能够开赞助，非常感谢您

**Comment by 2VCl1md** [comment]
可以，很强势

**Comment by laolu87** [comment]
支持大大，先留个脚印，打算近期有空学习下后端

**Comment by DongShi** [comment]
关注

**Comment by fangxu622** [comment]
新手入门版本太复杂，坑坑洼洼太多，已折磨我好几周，更新教程多久出···号期待

**Comment by 54wall** [comment]
新人刚刚试玩了下，已做到第七章，非常感谢！如果能增加网页美化的入门级指导就更完美了！

**Comment by zongwong** [comment]
跟着学,不错的教程.很适合我这种新手.不得不说现在技术更新太快了,各种API要查,

**Comment by liuestc** [comment]
哈哈  期待加入react啊，虽然我至今整个博客流程还没跑通

**Comment by rotate720deg** [comment]
大神，赶紧更新，我照着你的教程学了两次，每次就卡在各种错误上了，然后老师各种坑，就不了了之了。。。

**Comment by nswbmw** [comment]
done
