### ISSUE TITLE
利用markdown作为编辑器时，引入图片，显示不出来，会报403

### ISSUE THREAD

**Issue by djlxiaoshi** [nswbmw/N-blog#165]
就是我用markdown作为编辑器  直接把简书上面的一篇markdown写的文章copy过来，所有的图片不能显示，报403的错，但是在浏览器中键入图片的链接是可以正常访问得，这个403问题应该怎么解决啊！是浏览器的问题，还是服务器的问题

**Comment by fangxu622** [comment]
正在学习中··兄台可遇到markdown 这个问题？
![5](https://cloud.githubusercontent.com/assets/16681534/17580939/fd82bc88-5fd4-11e6-9e3f-80475732ab57.png)
![6](https://cloud.githubusercontent.com/assets/16681534/17580940/fd82fa4a-5fd4-11e6-8bd0-8ae98517e7eb.png)

**Comment by djlxiaoshi** [comment]
没有遇到啊！由于上面的403问题没有解决，现在已经换成使用kindedit了，不过那个编辑器也不是很好用，又是在对代码的插入，不是很友好。如果以后要是用markdown来写博客，是不是还要有个自己的图床啊，就是感觉在这里不是很方便

**Comment by Kinice** [comment]
建议你们看看markdown的语法是如何编译url的，文档里都有。

**Comment by nswbmw** [comment]
403可能是外链的图片网站做了限制。

 教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
