### ISSUE TITLE
快速刷新会报 process.nextTick(function() { throw err; });错误，怎样解决。有遇见同样问题的吗。

### ISSUE THREAD

**Issue by AzirChen** [nswbmw/N-blog#167]
给同学测试时，快速刷新会报错误，怎样解决啊，还不知道从哪里入手。

**Comment by BO-HAI** [comment]
我遇到了同样的问题，在注册时插入数据不是，collection.insert ，而是collection.insertOne;
我的英文不好，也是让我碰上了，请参考这个：
https://github.com/mongodb/node-mongodb-native/blob/0642f18fd85037522acf2e7560148a8bc5429a8a/docs/content/tutorials/changes-from-1.0.md#L38

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
