### ISSUE TITLE
最大监听数的问题 emitter.setMaxListeners()

### ISSUE THREAD

**Issue by 783010296** [nswbmw/N-blog#169]
我按着你的教材写这个博客的时候，总是会报(node) warning: possible EventEmitter memory leak detected. 11 reconnect listeners added. Use emitter.setMaxListeners() to increase limit.虽然只是警告不是error，但我还是想解决它，我查了下资料，也用了emitter.setMaxListeners()这个方法，但是不起作用，我设置setMaxListeners(20)，博客运行时到10个监听还是报warning，几天了还是没解决，希望可以为我答疑，谢谢。

**Comment by nswbmw** [comment]
是哪个模块报的？

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
