### ISSUE TITLE
mongodb.connect is not a function

### ISSUE THREAD

**Issue by haha214** [nswbmw/N-blog#170]
番外篇之——部署到 Heroku中，按照将 mongodb = require('./db') 修改为 mongodb = require('mongodb').Db，并将所有 mongodb.open(function (err, db) { 修改为 mongodb.connect(settings.url, function (err, db) {之后，提示mongodb.connect is not a function

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
