### ISSUE TITLE
第一章 路由控制出错

### ISSUE THREAD

**Issue by bill-mark** [nswbmw/N-blog#171]
按照教程修改完app.js和index.js后，会提示bin目录下的www  app.set not find

**Comment by gaoxiaosong1113** [comment]
s

**Comment by wang-sai** [comment]
我不会报not find但是会提示app.set is not a function，最后通过查看原来和修改过的文件后，在app.js文件最后要加上module.exports = app;就没事了

**Comment by llccing** [comment]
@wang-sai 按照你说的，改完提示3000端口的已使用，然后将app.js的端口号换为3001，就可以。这样http://localhost:3000/ 端口能访问，http://localhost:3001/ 也能访问。

**Comment by magaofei** [comment]
我也遇到了端口被使用的问题，更好的选择是不用'npm start' 而是使用 'node app.js'

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
