### ISSUE TITLE
错误记录

### ISSUE THREAD

**Issue by puregardenia** [nswbmw/N-blog#173]
跟着文章一点点做下来， 不停地添加功能，有些文档属性是后期加的，会出现好多问题。大多是传递过来的数据中没有的相应的属性，前端模板渲染的时候找不到，或者有一级属性，但是二级或者三级属性没有，所以会报错。比如：

第十五章的 

```
<% if (post.reprint_info.reprint_from) { %>
```

应该改为

```
if (post.reprint_info && post.reprint_info.reprint_from) {
```

另外 第十五章  修改 `post.js`的时候有一个错误
需要把 `post[0]` 改成 `post.ops[0]`

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
