### ISSUE TITLE
第一章在register成功之后，导航显示的是login 和register，但是log in 之后显示的是post,为什么呢

### ISSUE THREAD

**Issue by xiaomei1** [nswbmw/N-blog#178]
ul.nav.navbar-nav.navbar-right
            li
              a(href='/') Home
            if (user)
              li
                a(href='/upload') Upload
              li
                a(href='/post') post
              li
                a(href='/logout') Logout  
            else
              li
                a(href='/login') Login
              li
                a(href='/reg') Register

**Comment by Zaynex** [comment]
https://github.com/Zaynex/expressblog/tree/master/expressblog/lesson1 
您可以参考我写的。今天刚出炉的，希望能帮到您

**Comment by xiaomei1** [comment]
我是用jade模板写的

-

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
