### ISSUE TITLE
第一章中的路由规划这一小节的代码无法正常使用

### ISSUE THREAD

**Issue by napasa** [nswbmw/N-blog#179]
`module.exports = function(app) {
  app.get('/', function (req, res) {
    res.render('index', { title: '主页' });
  });
  app.get('/reg', function (req, res) {
    res.render('reg', { title: '注册' });
  });
  app.post('/reg', function (req, res) {
  });
  app.get('/login', function (req, res) {
    res.render('login', { title: '登录' });
  });
  app.post('/login', function (req, res) {
  });
  app.get('/post', function (req, res) {
    res.render('post', { title: '发表' });
  });
  app.post('/post', function (req, res) {
  });
  app.get('/logout', function (req, res) {
  });
};`

应该改为
`var router = require('express').Router();
    router.get('/', function (req, res) {
        res.render('index', { title: '主页' });
    });
    router.get('/reg', function (req, res) {
        res.render('reg', { title: '注册' });
    });
    router.post('/reg', function (req, res) {
    });
    router.get('/login', function (req, res) {
        res.render('login', { title: '登录' });
    });
    router.post('/login', function (req, res) {
    });
    router.get('/post', function (req, res) {
        res.render('post', { title: '发表' });
    });
    router.post('/post', function (req, res) {
    });
    router.get('/logout', function (req, res) {
    });
module.exports = router`

否则报错:”app.post is not a function“。请问这是为什么。
这是我解决问题时候找到的方法的[链接](http://stackoverflow.com/questions/38758198/app-post-is-not-a-function-express-node)

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
