### ISSUE TITLE
第一章注册和登陆小节中supervisor app.js指令存在错误

### ISSUE THREAD

**Issue by napasa** [nswbmw/N-blog#180]
这是supervisor app.js指令执行后的结果
**Running node-supervisor with
  program 'app.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'
Starting child process with 'node app.js'
Watching directory '/home/yuhongsong/software/node-v6.3.1-linux-x64/nodeProject/blog' for changes.
Press rs for restarting the process.
express-session deprecated undefined resave option; provide resave option app.js:17:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:17:9**
浏览器访问localhost:3000的结果是：
**This site can’t be reached
localhost refused to connect.**
将该指令改为supervisor ./bin/www则为正常。
这是supervisor ./bin/www执行后的结果：
**Running node-supervisor with
  program './bin/www'
  --watch '.'
  --extensions 'node,js,/bin/www'
  --exec 'node'
Starting child process with 'node ./bin/www'
Watching directory '/home/yuhongsong/software/node-v6.3.1-linux-x64/nodeProject/blog' for changes.
Press rs for restarting the process.
express-session deprecated undefined resave option; provide resave option app.js:17:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:17:9**

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
