### ISSUE TITLE
第三章： 文件上传： 命令行启动

### ISSUE THREAD

**Issue by DongShi** [nswbmw/N-blog#181]
文中有提到这么一句

> 注意：假如从桌面启动的博客上传图片时失败，尝试在命令行中从博客根目录下启动。

我碰到了这个问题，我是通过webstorm 配置了node debugger，如果通过debugger启动app的话 upload就不work。 有没有人能解释下 这两种 （vs 命令行）方式有何不同。thanks

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
