### ISSUE TITLE
照着教程走通了一遍，包括教程中的功能。

### ISSUE THREAD

**Issue by yidongwuxian** [nswbmw/N-blog#182]
在实现功能时，一点要先清空数据库，再刷新页面，才能看到正确的结果。
https://github.com/yidongwuxian/kirinblog

**Comment by Lxyour** [comment]
我也按着教程全部走了一遍，我每次是手动给以前的文章加上缺少的字段，不舍得删曾经让我成功的脚印，😁

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。

**Comment by Lxyour** [comment]
@nswbmw 请教一下你的koa分支session不需要添加参数吗？app.use(session()); 我的总是在这里报错

**Comment by nswbmw** [comment]
报啥错？可能写的有问题，参考 https://www.npmjs.com/package/koa-generic-session 的用法
