### ISSUE TITLE
使用Bootstrap优化了下，已经部署到Heroku和Mlab，欢迎fork，非常感谢nswbmw！

### ISSUE THREAD

**Issue by 54wall** [nswbmw/N-blog#183]
一步一步做的，结合百度，项目地址：
https://github.com/54wall/N-blog-WalkingDead
部署的位置：
https://my-walkingdead.herokuapp.com/
在此分享一下！

**Comment by seed-fe** [comment]
非常感谢你关于部署的这个教程，我也是照着这个nswbmw的教程做的，也用bootstrap优化了，到了部署阶段看到mongoHQ不能用了，然后按照你写的部署教程一步步走成功了！

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
