### ISSUE TITLE
文章内容不解析，可能是什么原因

### ISSUE THREAD

**Issue by xiaomei1** [nswbmw/N-blog#184]
`<p> <span style="font-size:18px;"><strong>秋天</strong></span> </p> <p> <ol> <li> <span style="line-height:1.5;">秋季的时候，自然景观最明显的变化在树木上面</span> </li> <li> <span style="line-height:1.5;">城市里会开始清扫大量的落叶，山区则涌进不少观赏红叶的游客们。</span> </li> <li> <span style="line-height:1.5;">秋季，一年四季的第三季，由夏季到冬季的过渡季，</span> </li> <li> <span style="line-height:1.5;">北半球为9至11月，南半球3至5月，天文为秋分到冬至。气象工作者研究物候学标...</span> </li> </ol> </p>`，出现这种效果

**Comment by nswbmw** [comment]
你应该用了`<%= %>`， 使用 `<%- %>` 

教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
