### ISSUE TITLE
err!!!! after npm start,when you visit the localhost:3000,a err happen,then you can't visit it.

### ISSUE THREAD

**Issue by wickedcode01** [nswbmw/N-blog#185]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! N-blog@1.0.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the N-blog@1.0.0 start script 'node app'.
npm ERR! This is most likely a problem with the N-blog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs N-blog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls N-blog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hasee\blog\npm-debug.log

**Comment by nswbmw** [comment]
请参考最新教程，见 [readme](请参考最新教程，见 readme。)。
