### ISSUE TITLE
全局使用mongoose的问题

### ISSUE THREAD

**Issue by skyfore** [nswbmw/N-blog#186]
你好，我在全局使用mongoose，但是在app.js当中的MongoStore是使用的connect-mongo,请问使用mongoose做应该怎么做？

**Comment by shawn-jdd** [comment]
mongoose有一套自己的方法，你上mongoose的网站上看下，可以找到的，connect-mongo只是一个小组件，方便用

**Comment by skyfore** [comment]
好的，谢谢，我去mongoose官网上看看@shawn-jdd
