### ISSUE TITLE
路由放到flash后面，页面无法显示

### ISSUE THREAD

**Issue by gj201314** [nswbmw/N-blog#187]
app.use(cookieParser());

//secret 用来防止篡改 cookie，key 的值为 cookie 的名字，通过设置 cookie 的 maxAge 值设定 cookie 的生存期，
//这里我们设置 cookie 的生存期为 30 天，设置它的 store 参数为 MongoStore 实例，把会话信息存储到数据库中，以避免丢失
app.use(session({
  secret: settings.cookieSecret,
  key: settings.db,//cookie name
  cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},//30 days
  store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
}));

app.use(flash());
//设置public文件夹为存放静态文件的目录
app.use(express.static(path.join(__dirname, 'public')));
//路由控制器
routes(app);

路由放到flash后面，页面无法显示，请问是怎么回事 ？@nswbmw

**Comment by nswbmw** [comment]
> 路由放到flash后面

你想说的应该是前面吧？

教程已更新，请参考最新教程，见 [readme](请参考最新教程，见 readme)。

**Comment by gj201314** [comment]
好的
