### ISSUE TITLE
你好，有问题求教

### ISSUE THREAD

**Issue by shmily1140** [nswbmw/N-blog#193]
我把你的源代码clone下来， npm install之后， 运行node index启动程序， 出现如下错误， 无法解决， 请指教：

![image](https://cloud.githubusercontent.com/assets/6020252/20033294/9ce50f90-a39d-11e6-840b-2fc639a0b4b3.png)

**Comment by nswbmw** [comment]
添加 `--harmony` 参数运行。即： `node --harmony index`

**Comment by shmily1140** [comment]
原来是我ｎｏｄｅ版本太低，不支持ＥＳ６，　升级了一下就好了
