### ISSUE TITLE
一处错误描述

### ISSUE THREAD

**Issue by jinzhuming** [nswbmw/N-blog#194]
https://github.com/nswbmw/N-blog/blob/master/book/4.9%20%E6%96%87%E7%AB%A0.md
4.9.4 文章编辑
现在我们来完成编辑与删除文章的功能。修改 models/routes.js，在 module.exports 对象上添加如下 3 个方法：

models/routes.js
 应该是models/posts.js

**Comment by Dachow** [comment]
我也是，被linux默认源安装的nodejs坑了，版本太低，换成最新的包就好了
