### ISSUE TITLE
4.4功能设计 启动程序报错TypeError：Cannot read propety 'session' of undefined

### ISSUE THREAD

**Issue by zxiaohong** [nswbmw/N-blog#196]
照着教程写完这章的内容 启动程序报错TypeError：Cannot read property 'session' of undefined
找不到错误 是因为 req.session初始状态为空{}吗？

**Comment by nswbmw** [comment]
能把代码提交到你的 GitHub，我看下吗

**Comment by zxiaohong** [comment]
我找到错误了 原因是我把 var checkLogin = require("../minddleware/check").checkLogin;写成了var checkLogin = require("../minddleware/check").checkLogin();在这里就执行了 所以req是undefined 

我太粗心了    谢谢你提供这么好的教程
