### ISSUE TITLE
在4.7注册这节里注册提示错误解决办法

### ISSUE THREAD

**Issue by Zaynex** [nswbmw/N-blog#197]
`Wed, 09 Nov 2016 03:21:39 GMT express-session deprecated undefined resave option; provide resave option at index.js:21:9
Wed, 09 Nov 2016 03:21:39 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:21:9
`
主要问题是缺少两个必填选项
```
resave: false,  
 saveUninitialized: true,  
```

在`index.js`中session中间件完整代码
```
app.use(session({
	//save session_id in cookie
	name: config.session.key,
	//use secret  calculate hash value to  prevent other people from being modified.
	secret: config.session.secret,
	cookie: {
		maxAge: config.session.maxAge
	},
	store: new MongoStore({
		url: config.mongodb
	}),
	resave: false,  
    saveUninitialized: true,  
}));
```
源码部分解释
##### saveUninitialized

Forces a session that is "uninitialized" to be saved to the store.(强制让可以未被初始化的session保存。) A session is
uninitialized when it is new but not modified. Choosing `false` is useful for
implementing login sessions, reducing server storage usage, or complying with
laws that require permission before setting a cookie. Choosing `false` will also
help with race conditions where a client makes multiple parallel requests
without a session.

**The default value is `true`, but using the default has been deprecated, as the
default will change in the future.** Please research into this setting and
choose what is appropriate to your use-case.

因为默认值已经被废弃，所以我们需要手动加上

##### resave

Forces the session to be saved back to the session store, even if the session
was never modified during the request. Depending on your store this may be
necessary, but it can also create race conditions where a client makes two
parallel requests to your server and changes made to the session in one
request may get overwritten when the other request ends, even if it made no
changes (this behavior also depends on what store you're using).

The default value is `true`, but using the default has been deprecated,
as the default will change in the future. Please research into this setting
and choose what is appropriate to your use-case. Typically, you'll want
`false`.
重新保存：强制会话保存即使是未修改的。

**Comment by nswbmw** [comment]
@Zaynex 👍

**Comment by wanguano** [comment]
很有用的文章
