### ISSUE TITLE
博主你觉得node用原生js写好还是typeScript好

### ISSUE THREAD

**Issue by xiaolovecai** [nswbmw/N-blog#198]

**Comment by nswbmw** [comment]
typescript 没用过，所以没法做比较，我个人觉得 es6 的语法就够用了，如 `...args` 和 `=>` 和解构赋值，平行赋值等等都有了，至少没必要用 coffeescript 了

**Comment by nswbmw** [comment]
我看老雷用了，你问下他

**Comment by cody1991** [comment]
+1 看着教程学习 然后基本自己都用es6来写 够了

**Comment by xiaolovecai** [comment]
nodejs做服务器开发,很迫切要解决的的就是类型问题,太宽松了....ES6虽然进步了很多,但是各种判断null undefined “” NaN都是需要统一和解决的,而且因为是单线程,任何一个未知错误出现,都会让应用崩溃...所以只敢用node写一些玩具


Lambda


原始邮件
发件人:唐泽雄notifications@github.com
收件人:nswbmw/N-blogN-blog@noreply.github.com
抄送:xiaos753623217@qq.com; Authorauthor@noreply.github.com
发送时间:2016年11月20日(周日) 17:14
主题:Re: [nswbmw/N-blog] 博主你觉得node用原生js写好还是typeScript好 (#198)


+1 看着教程学习 然后基本自己都用es6来写 够了
