### ISSUE TITLE
4.14.2 测试覆盖率里的 script 在 windows 下出错

### ISSUE THREAD

**Issue by charleneChen** [nswbmw/N-blog#201]
```
"scripts": {
  "test": "node --harmony ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha"
}
```

图片如下：

![image](https://cloud.githubusercontent.com/assets/7545977/20207053/9d3ae592-a81f-11e6-8a19-87f61b06d69c.png)

### 解决办法：

需要修改为:

```
"scripts": {
    "test": "node --harmony ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha"
  }
```

**亲测修改后可以正确运行**

图片如下：

![image](https://cloud.githubusercontent.com/assets/7545977/20207125/1d9a3e7c-a820-11e6-8db3-274e18cc53b6.png)

**Comment by nswbmw** [comment]
`./node_modules/.bin/istanbul` 就是 `./node_modules/istanbul/lib/cli.js`，为何第一个不行，第二个行。。

**Comment by charleneChen** [comment]
<code>./node_modules/.bin/istanbul</code> 不行的原因，觉得是如下图片显示的那个后缀名之顾，目前还没有在 Mac 上查看其后缀名是什么样，所以不是很肯定。如果有其他解释，欢迎指正

![image](https://cloud.githubusercontent.com/assets/7545977/20207602/620af45e-a823-11e6-8b18-da6a75f2135a.png)

-----------

<code>./node_modules/.bin/_mocha</code> 修改为：<code>./node_modules/mocha/bin/_mocha</code>

查了下 github 上的解释如下：

> Usage on Windows
Istanbul assumes that the command passed to it is a JS file (e.g. Jasmine, vows etc.), this is however not true on Windows where npm wrap bin files in a .cmd file. Since Istanbul can not parse .cmd files you need to reference the bin file manually.

**Comment by YourBoB** [comment]
![image](https://cloud.githubusercontent.com/assets/6147980/20777768/0d921da2-b7ce-11e6-8292-3efc833baa53.png)
执行这个test时 总是报这个错呢？ 用 mocha test.js 是可以执行成功的。谢谢

**Comment by nswbmw** [comment]
@YourBoB 你的测试命令是什么，上面报错：`Invalid name: "My First Blog"`

**Comment by YourBoB** [comment]
就是在这个根目录下面执行 npm test, My First Blog 这个是package.json里面的 
![image](https://cloud.githubusercontent.com/assets/6147980/20777955/66579650-b7cf-11e6-86f2-32de4880a0be.png)

**Comment by Jackzhangpan** [comment]
![1489410753 1](https://cloud.githubusercontent.com/assets/22291614/23855739/e220bae8-0831-11e7-9c91-c86df9b7b938.jpg)

已经改为"scripts": {
    "test": "node --harmony ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha"
  }。
为什么还报错？？？？

**Comment by nswbmw** [comment]
json 不合法。。

**Comment by Jackzhangpan** [comment]
ok，package.json中不可以有注释是吧，thank you @nswbmw
