### ISSUE TITLE
请问 req.session.user这个变量保存在哪。。。

### ISSUE THREAD

**Issue by aisansan** [nswbmw/N-blog#202]

**Comment by aisansan** [comment]
好不容易理解 cookie 和session，但是从源码里没看到 user 的信息保存在 cookie 还是session中 ，我刚接触node，有点搞不明白啊

**Comment by nswbmw** [comment]
注册或者登陆成功，会将用户信息写到 req.session：

```
req.session.user = user;
```

express-session 中间件会帮我们把 session 信息写到 mongodb，同时把 session id 返回浏览器

**Comment by aisansan** [comment]
多谢 小星星大哥

**Comment by aisansan** [comment]
小星星大哥，我还是有一点不明白， 我发现mongodb里的sessions 里只存了_id，并没有user，session信息的user 是存在别的地方么


`{
    "_id" : "dJoHXDULxyQhGwDBO4sJ8_2Ab2GO6hTZ",
    "session" : "{\"cookie\":{\"originalMaxAge\":2592000000,\"expires\":\"2016-12-15T02:02:38.095Z\",\"httpOnly\":true,\"path\":\"/\"},\"flash\":{},\"user\":{\"name\":\"admin\",\"gender\":\"f\",\"bio\":\"123\",\"avatar\":\"upload_0dbbab4fc8e12bde1fc0180fe62ea3c3.gif\",\"_id\":\"582a6c99e4a1d5c85827cd3c\"}}",
    "expires" : ISODate("2016-12-15T02:02:38.095Z")
}`

**Comment by nswbmw** [comment]
你再仔细看看。。

**Comment by aisansan** [comment]
我该配眼镜了。。。。抱歉
