### ISSUE TITLE
不好意思，我又来问了

### ISSUE THREAD

**Issue by aisansan** [nswbmw/N-blog#204]
小星星大哥，我还是有一点不明白， 我发现mongodb里的sessions 里只存了_id，并没有user，session信息的user 是存在别的地方么
sessions
{ "_id" : "dJoHXDULxyQhGwDBO4sJ8_2Ab2GO6hTZ", "session" : "{\"cookie\":{\"originalMaxAge\":2592000000,\"expires\":\"2016-12-15T02:02:38.095Z\",\"httpOnly\":true,\"path\":\"/\"},\"flash\":{},\"user\":{\"name\":\"admin\",\"gender\":\"f\",\"bio\":\"123\",\"avatar\":\"upload_0dbbab4fc8e12bde1fc0180fe62ea3c3.gif\",\"_id\":\"582a6c99e4a1d5c85827cd3c\"}}", "expires" : ISODate("2016-12-15T02:02:38.095Z") }

**Comment by aisansan** [comment]
我的眼好瞎。。。

**Comment by nswbmw** [comment]
😆
