### ISSUE TITLE
首次注册页面跳转

### ISSUE THREAD

**Issue by wuyingfeng1992** [nswbmw/N-blog#206]
每次清空数据库第一次注册，注册成功后会跳转不到/posts页面，第二次注册，注册成功后后留在、/signup上但是显示该地址已经重置，过一会才调到/posts页面。我想问下这是什么原因啊

**Comment by nswbmw** [comment]
。。回复晚了抱歉，问题解决了吗，没有的话提交到你的 GitHub 我看下吧

**Comment by ElvisVern** [comment]
代码是没问题的  应该是你哪个地方写错了吧。。

**Comment by Guguzi** [comment]
注册登录之后为什么出现
> events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/public/img/upload_a9a17e4bd9dc9a859feb19140e22132f.png'
    at Error (native)
这样的错误? 是图片上传不成功吗?

**Comment by liangzr** [comment]
@nswbmw 我也出现了同样的问题，看到数据库还是正常的添加，我先继续进行下去，回头再来看 ( 现在找不出原因 )，贴个有问题的版本的地址
  
[bug: 注册提交后跳转到连接已重置](https://github.com/liangzr/nblog/tree/e63023b1630f58d1ddc43aff90ad4db46a570a72)

**Comment by GuoJieLun** [comment]
我也有同样的为题 ,我猜是不是then回调不到

**Comment by muzishuiji** [comment]
@nswbmw 大神，在不啊，我的注册页面一直遇到问题，能不能帮我解决下呢？就是没办法进入注册页面的post方法，然后报错信息是
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\开发工具\node\testbox\myblog\punlic\img\upload_2f4d54fe91aaa8b8cb1b38ec7efafb3e'
    at Error (native)
Program node --harmony index exited with code 1`
求救，怎么办？

**Comment by nswbmw** [comment]
punlic -> public  ???

**Comment by muzishuiji** [comment]
@nswbmw 我对不起你，真的是这个原因，这么愚蠢的问题耽误了你的时间，罪恶！
