### ISSUE TITLE
config-lite 中间件无法引用 default

### ISSUE THREAD

**Issue by OlafCheng** [nswbmw/N-blog#211]
我对路径进行了检查，没有问题，但是中间件却不能引用 default, `NODE_ENV` 我没有进行设置, 所以按照 config-lite 的说明, 应该是直接去引用 `config/default`, 但是却失败了, 请问怎么解决？

错误信息:
```
config-lite load `default` failed
Error: Cannot find module 'default' from '/Users/olafcheng/Programs/Note'
    at Function.module.exports [as sync] (/Users/olafcheng/Programs/Note/node/code/c5/myblog/node_modules/resolve/lib/sync.js:33:11)
    at loadConfig (/Users/olafcheng/Programs/Note/node/code/c5/myblog/node_modules/config-lite/index.js:32:26)
    at Object.<anonymous> (/Users/olafcheng/Programs/Note/node/code/c5/myblog/node_modules/config-lite/index.js:18:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
config-lite load `default` failed
Error: Cannot find module 'default' from '/Users/olafcheng/Programs/Note'
```

用 `process.cwd()` 输出进程目录:
```
console.log("Process path is: " + process.cwd());
// Process path is: /Users/olafcheng/Programs/Note/node/code/c5/myblog
```
用 `process.env.NODE_ENV` 输出和 `config-lite` 有关的环境变量(没定义, 所以按照说明, 是直接读取 default.js):
```
console.log("process.env.NODE_ENV = " + process.env.NODE_ENV);
// process.env.NODE_ENV = undefined
```

有人提示是不是文件权限导致的问题，我把 default.js 的权限改成了 777 仍然不行, 文件路径检查过，是没问题的。

我在 sf.gg 上也提问了这个问题, 问题链接：
https://segmentfault.com/q/1010000007574494/

**Comment by nswbmw** [comment]
有问题的代码能提交到你的 GitHub 我看下一吗

**Comment by hi363138911** [comment]
我和他一样 的错误， 我直接用const config = require('./congfig/default')替换了
const config = require('config-lite')
可以走 － －

**Comment by OlafCheng** [comment]
你好，我把代码提交上来了。

谢谢。

https://github.com/OlafCheng/private-Nblog

**Comment by nswbmw** [comment]
我本地运行没问题

**Comment by OlafCheng** [comment]
好的，谢谢。
那我再试试看怎么解决或者绕过这个问题。

**Comment by duleigiser** [comment]
我也遇到过这个问题，我用vscode在项目的父目录打开文件，cd到项目目录里执行，然后出现了上述问题，我试着把config文件夹放到和项目同级下，就成功了。下次就直接打开项目目录，接没有问题了。

**Comment by duanbowen** [comment]
我看了config-lite里面的代码 好像是 这一句 
var filename = process.env.NODE_ENV || 'default'; // process.env.NODE_ENV的值是等于 production的 但是在config文件夹里面并没有这个 文件 ，最后加载的时候就报错了cannot find了 

config-lite在这里的作用好像是仅仅加载 config文件夹里面的 default.js 
所以我跟楼上的做法一样 将var config = require('config-lite');替换成const config = require('./config/default'); 效果一样

**Comment by nswbmw** [comment]
试试 config@2，之前的冒泡查找配置文件有问题。

**Comment by CodeingShow** [comment]
我也遇到了这个问题，以上的方法都试了，不行。

**Comment by nswbmw** [comment]
@CodeingShow 是 config-lite@2 吗，是的话，你 tree 一下目录我看下

**Comment by CodeingShow** [comment]
"config-lite": "^2.0.0",tree哪一个目录？整个项目目录？

**Comment by nswbmw** [comment]
恩，你项目目录

**Comment by applehub** [comment]
https://github.com/applehub/myblog/files/1195667/list.txt我上传到这里了

**Comment by applehub** [comment]
https://github.com/applehub/myblog/issues/1

**Comment by nswbmw** [comment]
@applehub 看了貌似没有问题，你把代码上提交到你的 myblog 仓库我本机试下

**Comment by applehub** [comment]
已上传至：
https://github.com/applehub/myblog
发现你的完整的项目我能在本机运行，不过开始的时候报错，提示要将mongodb更新到2.2.19或更高的版本，更新后，项目正常运行。但是在按照教程走的过程中，config-lite模块会报错。

**Comment by applehub** [comment]
留言功能点击不了。

**Comment by applehub** [comment]
留言测试成功

**Comment by nswbmw** [comment]
@applehub 细心点啊~

1. default.js 文件名前面多了个空格。。
2. 加上 .gitignore，不要把 node_modules 也 push 上来

**Comment by applehub** [comment]
好的
这种错误，我晕，好难发现啊。非常感谢您。

**Comment by calabash519** [comment]
哈哈，博主感觉好萌，点个赞

**Comment by applehub** [comment]
本萌宠纯属贵圈新宠，前几天才注册账号，看教程学会的git上传项目。那么问题来了：为什么我push的时候只有部分文件上传到了github,详细情况戳：
https://cnodejs.org/topic/5982ec5b07cef83a61770a08#5982ec9d07cef83a61770a09
