### ISSUE TITLE
MongoError: failed to connect to server [localhost:27017] on first connect

### ISSUE THREAD

**Issue by ruofeng086** [nswbmw/N-blog#218]
运行 node --harmony index
报错如下：
`MongoError: failed to connect to server [localhost:27017] on first connect`

mongodb已启动，通过brew 安装 

![image](https://cloud.githubusercontent.com/assets/14192308/20645657/94aa1cb8-b49f-11e6-939b-a4192b124f65.png)

**Comment by nswbmw** [comment]
试下 mongo 命令能连上 mongodb 吗

**Comment by ruofeng086** [comment]
没报错

**Comment by ruofeng086** [comment]
mongo没报错

**Comment by ruofeng086** [comment]
尝试ping下localhost

ping: cannot resolve localhost: Unknown host
修改host文件，添加127.0.0.1 localhost 即可

重启服务即可...

结贴

**Comment by licoby** [comment]
遇到同样的问题，运行 node --harmony index
报错如下：
`MongoError: failed to connect to server [localhost:27017] on first connect`
且运行 mongo 显示错误如下

![image](https://cloud.githubusercontent.com/assets/15437540/20787914/449a1c9e-b7e9-11e6-9567-7549bd31bcc5.png)

可以 ping 通 localhost。求解
