### ISSUE TITLE
分支

### ISSUE THREAD

**Issue by cllgeek** [nswbmw/N-blog#223]
分支上的这
express4.x: express4.x 版，代码进行了重构
koa: koa 版

两个版本呢??? 没发现有啊

**Comment by nswbmw** [comment]
以前写了 koa 版本，重写后 master 就是最新的 express4.x，觉得没必要有 koa 版就删掉那个分支了。koa 的教程可以去看另一篇 https://github.com/nswbmw/N-club

**Comment by cllgeek** [comment]
thank you.
