### ISSUE TITLE
关于config-lite

### ISSUE THREAD

**Issue by skyfore** [nswbmw/N-blog#226]
你好，请问能给个config-lite的链接吗？

**Comment by nswbmw** [comment]
npm 搜下不就知道了吗。。https://github.com/nswbmw/config-lite

**Comment by NetLogoclub** [comment]
看到config－lite里面的解释 By default, require('config-lite') will bubbling find config (or custom) directory from process.cwd().就理解为什么博主一只都是require('config-lite') 而不是require(''../config.default.js“)了
