### ISSUE TITLE
使用bower 安装到本地后，资源依赖问题

### ISSUE THREAD

**Issue by duleigiser** [nswbmw/N-blog#230]
为了部署到远程服务，在header里写入相对路径进行应用静态库文件的时候。
例如访问http://localhost:3000/posts/:postId/edit
本来应该
http://localhost:3000/semantic/dist/semantic.min.css 
变成
`can't  GET http://localhost:3000/posts/semantic/dist/semantic.min.css 
`
找不到资源了额

此时要重新为同样路径下重新写一份header吗？

**Comment by nswbmw** [comment]
资源以 `/` 开头试试

**Comment by duleigiser** [comment]
谢谢，问题解决了！
