### ISSUE TITLE
注册表单提交失败图片上传问题

### ISSUE THREAD

**Issue by yuanwyj** [nswbmw/N-blog#231]
提交注册表单提示失败的时候，系统仍旧会把头像图片保存在服务器，不知道是故意为之还是一个小bug

**Comment by nswbmw** [comment]
这块没管，其实提交表单失败的时候应该把已经上传的头像删掉的

**Comment by yuanwyj** [comment]
我的想法是把表单验证在客户端完成，这样提交到服务器的都是成功的表单，而在服务器验证如何去改善有好的方法吗^_^

**Comment by nswbmw** [comment]
严谨的做法是客户端和服务端都要做验证。后端再提供一个验证用户名是否被注册之类的接口，浏览器中用户在用户名的 input 失去焦点的时候调一下这个接口等等，用 vue, react, angular 都很容易做。
