### ISSUE TITLE
登录时浏览器一直转，后台没响应。

### ISSUE THREAD

**Issue by sdyk-jym** [nswbmw/N-blog#233]
博主你好！
我根据你的教程在学，注册是没问题的，数据库也能看到注册的数据。到了登录阶段，点击登录之后，后台没反应，可能是超时了，然后浏览器显示**localhost 网页无法正常运作**。后台没有出错，在登录的post路由中也答应不出来东西，似乎是没有发送到这个路由上，最后在命令行打印了两行

`POST /signin --ms--`
`POST /signin --ms--`

请问博主，这个会是什么原因导致的呢？

**Comment by sdyk-jym** [comment]
解决了，为啥我这边需要加上 `enctype="multipart/form-data"`，不然一直是pending。
没有要上传文件啊，模仿邮箱也需要加上 `enctype` 吗？
`<form class="col s12" method="post" enctype="multipart/form-data">
          <div class="row">
            <div class="input-field col s12">
              <input id="email" type="email" class="validate" name="email">
              <label for="email">Email</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <input id="password" type="password" class="validate" name="password">
              <label for="password">Password</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12 sub-btn">
              <button class="btn waves-effect waves-light" type="submit">登录<i class="iconfont material-icons right">&#xe603;</i>
              </button>
            </div>
          </div>
        </form>`

**Comment by he5050** [comment]
我也遇到这样了的问题，会会是因为没有引入上传的模块问题
