### ISSUE TITLE
我发现每次重新提交代码到heroku，头像就会全部失效。。

### ISSUE THREAD

**Issue by cody1991** [nswbmw/N-blog#234]
<img width="320" alt="qq20161206-0 2x" src="https://cloud.githubusercontent.com/assets/3488257/20919592/9c7b6584-bbd7-11e6-8ade-42f54aebf8bd.png">

上图看到用户名什么的都还是正确的，可是指向的头像却找不到了。

可是没有重新提交代码前，注册以后，头像什么的都是正常显示

**Comment by nswbmw** [comment]
应该是每次提交代码到 Heroku 覆盖了原来的目录，导致之前的头像的目录为空了（public/img）

**Comment by cody1991** [comment]
```
*

!.gitignore
```

在 public/img 里面有设置这个 .gitignore
