### ISSUE TITLE
req.fields 这个是怎么来的？

### ISSUE THREAD

**Issue by EasonYou** [nswbmw/N-blog#236]
一直好奇这个fields是怎么来的
我所有代码都看了都没看出来
是发表文章时 submit 后title和content自行加载到req.fields里去了么？

还有就是那个plugin，不清楚他的运行机制
执行了addCreatedAt，然后是如何执行plugin内部的两个afterFind和afterFindeOne函数的。。
我log下数据，
afterFind 的reuslts取得的是当前所有文章的数据，
afterFindOne的result是取得当前用户的数据
可是原理是啥搞不清楚

**Comment by duleigiser** [comment]
加了一个处理表单 express-formidable中间件，它会把form表单里的字段放到req.fields中。
你可以打断点，看下请求参数。我一开始没有加这个中间件，一直取不到fields中的值。

**Comment by duleigiser** [comment]
加了一个处理表单 express-formidable中间件，它会把form表单里的字段放到req.fields中。
你可以打断点，看下请求参数。我一开始没有加这个中间件，一直取不到fields中的值。

**Comment by duleigiser** [comment]
加了一个处理表单 express-formidable中间件，它会把form表单里的字段放到req.fields中。
你可以打断点，看下请求参数。我一开始没有加这个中间件，一直取不到fields中的值。

**Comment by duleigiser** [comment]
加了一个处理表单 express-formidable中间件，它会把form表单里的字段放到req.fields中。
你可以打断点，看下请求参数。我一开始没有加这个中间件，一直取不到fields中的值。

**Comment by duleigiser** [comment]
加了一个处理表单 express-formidable中间件，它会把form表单里的字段放到req.fields中。
你可以打断点，看下请求参数。我一开始没有加这个中间件，一直取不到fields中的值。

**Comment by EasonYou** [comment]
@duleigiser 原来是这样！

**Comment by NetLogoclub** [comment]
@duleigiser 我在post里没看到用这个中间件啊？
