### ISSUE TITLE
npm start  直接报错了

### ISSUE THREAD

**Issue by arronf2e** [nswbmw/N-blog#237]
![image](https://cloud.githubusercontent.com/assets/15780058/20968958/c50a85da-bcc1-11e6-8240-9accb45c94d9.png)

**Comment by iheng** [comment]
check your json file  start script

**Comment by arronf2e** [comment]
@iheng  I think it's ok

{
  "name": "一个前端",
  "version": "1.0.0",
  "description": "hello world",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog'"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "config-lite": "^1.5.0",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^1.3.2",
    "ejs": "^2.5.5",
    "express": "^4.14.0",
    "express-formidable": "^1.0.0",
    "express-session": "^1.14.2",
    "express-winston": "^2.1.0",
    "marked": "^0.3.6",
    "moment": "^2.17.1",
    "mongolass": "^2.3.2",
    "objectid-to-timestamp": "^1.3.0",
    "sha1": "^1.1.1",
    "winston": "^2.3.0"
  }
}

can you find some errors -,-

**Comment by yuanwyj** [comment]
数据库服务有没有打开？有没有执行npm install?

**Comment by duleigiser** [comment]
name 包名改成英文，description（描述）里你可以用中文。

**Comment by arronf2e** [comment]
@yuanwyj   NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog' 直接用这条命令就可以跑-，- 
写在scripts，然后npm start就报错

**Comment by arronf2e** [comment]
@duleigiser  改成英文了，还是会报错
![image](https://cloud.githubusercontent.com/assets/15780058/20996132/5fe4ffb2-bd36-11e6-9bfa-b336e1064464.png)

**Comment by arronf2e** [comment]
@duleigiser  我在试着部署到Ucloud，发现 npm i 都不行了，是不是node版本的问题

**Comment by iheng** [comment]
name should Not have space

**Comment by arronf2e** [comment]
@iheng  oh.....谢了

**Comment by iheng** [comment]
试试 node index.js 能不能跑， 能跑的话就是script的问题。
或是换成 cross-env NODE_ENV 试试

**Comment by arronf2e** [comment]
@iheng  现在可以了，就是name这个字段的问题，长见识了，多谢

**Comment by arronf2e** [comment]
@iheng  你试过部署到 Ucloud吗

**Comment by iheng** [comment]
@arronf2e  还没有

**Comment by nswbmw** [comment]
name 中有空格，用 `node index` 是没问题的，用 `npm start` 就会报错，可能是通过 npm 命令启动程序，npm 会自动检查 package.json 的 name 字段是否合法。

**Comment by arronf2e** [comment]
@nswbmw  OK， 明白

**Comment by arronf2e** [comment]
@nswbmw  我部署到UCLOUD上，用pm2已经把进程跑起来了，然后访问外网地址打不开-，-

**Comment by nswbmw** [comment]
登上去看 log

**Comment by arronf2e** [comment]
@nswbmw 
![image](https://cloud.githubusercontent.com/assets/15780058/20999300/9262bc00-bd4e-11e6-9a4d-8e4ac10337d3.png)
第一次接触pm2，不是很懂这错误呢，好像是什么日志中间件报错吗

**Comment by LeoCecilia** [comment]
```
 'NODE_ENV' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myblog@1.0.0 start: `NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myblog@1.0.0 start script 'NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myblog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myblog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myblog
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\少年\AppData\Roaming\npm-cache\_logs\2017-05-26T11_44_19_677Z-debug.log

```
这种错误要怎么弄啊。
