### ISSUE TITLE
findOne  找不见数据

### ISSUE THREAD

**Issue by ijisen** [nswbmw/N-blog#238]
您好，麻烦问下：
models/posts.js  中的： 
    通过文章 id 获取一篇文章   getPostById  中 findOne 查找 找不见数据  换成find就能行；  是不是mongolass 中对findOne 没有封装ObjectId啊？

**Comment by nswbmw** [comment]
Mongolass 做了的，感觉是你哪里写的有问题..

**Comment by zsg857981535** [comment]
我的也找不到

**Comment by nswbmw** [comment]
先确定是不是 MongoDB 有数据，有的话贴代码看看

**Comment by zsg857981535** [comment]
有的{ 
    "_id" : ObjectId("584a50b18c1b540590c69f3e"), 
    "author" : ObjectId("5849168d4ffdfd355ca5fab5"), 
    "title" : "嘿嘿嘿", 
    "content" : "嘿嘿嘿", 
    "pv" : NumberInt(3)
}
{ 
    "_id" : ObjectId("584a591240bfaf43c815d2d5"), 
    "author" : ObjectId("5849168d4ffdfd355ca5fab5"), 
    "title" : "hhaha", 
    "content" : "hahahah", 
    "pv" : NumberInt(9)
}

**Comment by zsg857981535** [comment]
跟楼上说的一样,换成find就可以查询到,不过所有post的数组

**Comment by nswbmw** [comment]
@zsg857981535 @ijisen 代码提交到 GitHub 我看下

**Comment by zsg857981535** [comment]
都是跟着你的教程走的,就是这个部分
  //通过id获取一篇文章
  getPostById: function(postId){
      console.log('通过postId获取文章',postId);
    return Post
            // .findOne({
            //   _id: postId
            // })
            .find({
                _id:postId
             })
            .populate({
              path:'author',model:'User'
            })
            .addCreatedAt()
            .addCommentsCount()
            .contentToHtml()
            .exec();
  },
换成find()是可以的哦

**Comment by Erroi** [comment]
这个是什么原因啊 ？？
Starting child process with 'node --harmony index'
/Users/qiany/Desktop/practice-node/node-blog/index.js:1
(function (exports, require, module, __filename, __dirname) { index.js
                                                                                                      ^

ReferenceError: index is not defined

**Comment by muzishuiji** [comment]
@zsg857981535 我的也是这个问题，数据库里面明明有数据，可是查询的结果就是undefind，你怎么解决的啊？求助！！！

**Comment by LeoCecilia** [comment]
我也是这个问题的，但是我的数据是这样的
``` json
{
    "_id": {
        "$oid": "59267472312f5ca8301a81ad"
    },
    "author": {
        "$oid": "5924f5e08b2405b1e8bd1378"
    },
    "title": "我真的愛你",
    "content": "阿斯頓發射點發生",
    "pv": 1
}
```
想问一下你们最后是怎么解决

**Comment by nswbmw** [comment]
@LeoCecilia $oid 和 ObjectId 是等价的，见：https://docs.mongodb.com/manual/reference/mongodb-extended-json/#oid

**Comment by LeoCecilia** [comment]
哦哦，我搞好啦，不过也是使用find来获取数据的，后来我无法渲染出那些post数据，然后上网找了一下怎么去调试promise，后来发现原来chrome55+是可以调试promise，后来发现传回来的数据中post应该是result[0][0];然后就能正确渲染啦
