### ISSUE TITLE
index().exec

### ISSUE THREAD

**Issue by elva2596** [nswbmw/N-blog#242]
`exports.User.index({ name: 1 }, { unique: true }).exec();// 根据用户名找到用户，用户名全局唯一`
您好，这里我不是很懂，源码中index就是ensureIndex,但是后面加了个exec这是为什么呢？这个exec不是加在query后面吗？？？

**Comment by nswbmw** [comment]
exports.User 就是 Mongolass 中的 Model，User.index 其实就是 query，所以需要加上 `.exec`，index 其实就是 mongodb 中 ensureIndex 的别名，见：https://github.com/mongolass/mongolass/blob/master/lib/model.js#L23
