### ISSUE TITLE
请问mongoglass里插件plugin里的两个函数的流程是什么

### ISSUE THREAD

**Issue by EasonYou** [nswbmw/N-blog#244]
```
Post.plugin('contentToHtml', {
  afterFind: function (posts) {
    return posts.map(function (post) {
      post.content = marked(post.content);
      return post;
    });
  },
  afterFindOne: function (post) {
    if (post) {
      post.content = marked(post.content);
    }
    return post;
  }
});
```
类似这个，getPostById和getPosts都调用的是.contentToHtml()
可是一个跑afterFind，一个跑afterFindOne....
这个真的难懂....
到底是什么一个流程？

**Comment by nswbmw** [comment]
你自己都说明白了啊，findOne.contentToHtml() 会调用 afterFindOne，find.contentToHtml() 会调用 afterFind。也就是说，在定义一个 plugin 的时候，需要指定哪些操作会调用此 plugin，上例你需要在 findOne 和 find 后调用，那么就得定义 afterFindOne 和 afterFind 这两个钩子函数。而且，就只有两种前缀：

1. beforeXXX: 在查询之前调用，参数为 query 参数
2. afterXXX: 在查询之后调用，参数为查询的结果

**Comment by EasonYou** [comment]
明白了！很感谢
