### ISSUE TITLE
路由到/signup会出现302，重定向到/

### ISSUE THREAD

**Issue by JSkeeper** [nswbmw/N-blog#246]
response header 会带回来一个 location:/
十分不解，谢谢。

**Comment by nswbmw** [comment]
res.redirect 会设置 response 的 header 的 Location..这有啥不解的？

**Comment by JSkeeper** [comment]
呃，昨晚上可能supervisor代码更新出了问题。
明明没有设置redirect还是重定向了。

**Comment by cpprookie** [comment]
我也经历了这个问题，刚发现问题在哪。给以后的朋友看吧。

我是在
```
routes.get('/', checkNotLogin, function(req, res, next) {
  res.render('signup');
})
```
这里出现了问题，因为地址栏里输`lcoalhost:3000/signup` 总是自动重定向到 `lcoalhost:3000/posts`
做了一下几步排查 
- 打开控制台，发现`signup`请求是被处理了的，只是被重定向到根目录去
- 去掉权限控制的 `checkNotLogin` ，去掉 `res.render('signup')` 而更改为 `res.send('XXX')` ，发现在正确的路径下输出了正确的信息。
- 检查 check.js ，发现 `checkNotLogin()`中的 
```
if(req.session.user) {
   return res.redirect('back');
}
```
被我错写为
```
if(!req.session.user) {
   return res.redirect('back');
}
```
所以一直重定向 23333，问题解决。
