### ISSUE TITLE
请问存储头像路径不对怎么解决?

### ISSUE THREAD

**Issue by zsg857981535** [nswbmw/N-blog#250]
{ 
    "_id" : ObjectId("584b836f56e8994430f5ec99"), 
    "name" : "DaGuo2", 
    "password" : "215822f5429d30b97bf7b4e6f51916c70283447d", 
    "gender" : "m", 
    "bio" : "666", 
    "avatar" : "D:\\nodejs\\myblog\\public\\img\\upload_bfdb6fc232ff60f8dd737d37cb197824.jpg"
}

**Comment by nswbmw** [comment]
没看出哪里不对了..详细点

**Comment by zsg857981535** [comment]
<img class="avatar" src="/img/D:\nodejs\myblog\public\img\upload_1605122d5ccb7b6ee45e669a6c766b95.jpg">

**Comment by zsg857981535** [comment]
这样的:

<img class="avatar" src="/img/D:\nodejs\myblog\public\img\upload_1605122d5ccb7b6ee45e669a6c766b95.jpg">

**Comment by zsg857981535** [comment]
'<img class="avatar" src="/img/D:\nodejs\myblog\public\img\upload_1605122d5ccb7b6ee45e669a6c766b95.jpg">''

**Comment by zsg857981535** [comment]
src="/img/D:\nodejs\myblog\public\img\upload_1605122d5ccb7b6ee45e669a6c766b95.jpg

**Comment by zsg857981535** [comment]
存储的是绝对路径,

**Comment by nswbmw** [comment]
avatar 取得是 `req.files.avatar.path.split(path.sep).pop()`，windows 下应该没有问题，你看些是不是哪里写错了

**Comment by zsg857981535** [comment]
就是这么写的呢

**Comment by yiuyiu** [comment]
我也是这儿有点问题 按照up主这么来的，然后点击注册那边是这样的
![](http://ww4.sinaimg.cn/large/75c66144gw1fawa2mub20j20i4037aav.jpg)

**Comment by janrone** [comment]
@yiuyiu  你提前把 public\img 目录创建好没

**Comment by DoneSpeak** [comment]
@zsg857981535 src="/img/D:\nodejs\myblog\public\img\upload_1605122d5ccb7b6ee45e669a6c766b95.jpg 这个路径可以读取到图片的吗？？？？应该保存相对于img下的路径吧

**Comment by v-haijiang9999** [comment]
原来这样，没有创建img文件，尴尬！！

**Comment by Yevvb** [comment]
尴尬！！
