### ISSUE TITLE
楼主，你的注册或者登录成功之后的跳转时有问题的？？

### ISSUE THREAD

**Issue by YuKaiChan** [nswbmw/N-blog#254]
你的源代码在登录或者注册都是跳出res.redirect('/posts') 这个是不对的，是应该跳到该用户的主页res.redirect('/posts/user')

**Comment by nswbmw** [comment]
可以，你觉得跳到哪合适就跳到哪。。主页或者用户页都无所谓，这是产品设计上的问题

**Comment by YuKaiChan** [comment]
不对啊，假如是产品设计的问题，那么我刚刚注册了一个用户，来到该用户的个人主页，那么这个posts参数是不存在，你的原代带的页面上没有做成判断啊

**Comment by YuKaiChan** [comment]
不对啊，假如是产品设计的问题，那么我刚刚注册了一个用户，点击个人主页来到该用户的个人主页，那么这个posts参数是不存在，你的原代码的页面上没有做成判断啊，在posts.ejs上就开始forEach遍历了，一个新的新注册的用户他的文章是空的，怎么可以forEach

**Comment by nswbmw** [comment]
没发表过文章 posts 是 [] 啊，[]. forEach 会报错吗？

**Comment by YuKaiChan** [comment]
不会，
