### ISSUE TITLE
models/posts.js getPosts 方法 query 为空错误

### ISSUE THREAD

**Issue by Guguzi** [nswbmw/N-blog#259]
> Error at Model.find (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/mongolass/lib/query.js:107:16) at Object.getPosts (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/models/posts.js:67:6) at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/routes/posts.js:16:13 at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5) at next (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/route.js:131:13) at Route.dispatch (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5) at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:277:22 at Function.process_params (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:330:12) at next (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:271:10) at Function.handle (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:176:3) at router (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:46:12) at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:312:13) at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:280:7 at Function.process_params (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:330:12)

find(query) 这个方法有问题么?

**Comment by nswbmw** [comment]
信息太少了，贴一下 models/posts.js:67:6

**Comment by Guguzi** [comment]
>   getPosts: function getPosts(author) {
    var query = {};
    if (author) {
      query.author = author;
    }
    return Post
    .find(query)
    .populate({ path: 'author', model: 'User' })
    .sort({ _id: -1 })
    .addCreatedAt()
    .addCommentsCount()
    .contentToHtml()
    .exec();
  },

find(query) 是67 行

**Comment by nswbmw** [comment]
打印下错误信息，你把 .exec(); 改成 .exec().catch(e => console.log(e)) 看看

**Comment by Guguzi** [comment]
> /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/views/posts.ejs:3 1| <%- include('header') %> 2| >> 3| <% posts.forEach(function (post) { %> 4| <%- include('components/post-content', { post: post }) %> 5| <% }) %> 6| Cannot read property 'forEach' of undefined

TypeError: /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/views/posts.ejs:3 1| <%- include('header') %> 2| >> 3| <% posts.forEach(function (post) { %> 4| <%- include('components/post-content', { post: post }) %> 5| <% }) %> 6| Cannot read property 'forEach' of undefined at eval (eval at compile (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/ejs/lib/ejs.js:481:12), <anonymous>:12:13) at returnedFn (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/ejs/lib/ejs.js:512:17) at View.exports.renderFile [as engine] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/ejs/lib/ejs.js:364:31) at View.render (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/view.js:126:8) at tryRender (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/application.js:639:10) at EventEmitter.render (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/application.js:591:3) at ServerResponse.render (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/response.js:960:7) at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/routes/posts.js:18:11 at tryCatcher (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/promise.js:510:31) at Promise._settlePromise (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/promise.js:567:18) at Promise._settlePromise0 (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/promise.js:612:10) at Promise._settlePromises (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/promise.js:691:18) at Async._drainQueue (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/async.js:138:16) at Async._drainQueues (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/async.js:148:10) at Immediate.Async.drainQueues (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/bluebird/js/release/async.js:17:14)
信息是这样的

**Comment by Guguzi** [comment]
>  Error
    at Model.find (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/mongolass/lib/query.js:107:16)
    at Object.getPosts (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/models/posts.js:67:6)
    at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/routes/posts.js:16:13
    at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5)
    at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:312:13)
    at /Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/liuhongbo/Desktop/MyFirstBlog/GuguziBlog/node_modules/express/lib/router/index.js:330:12)

信息是这样的

**Comment by nswbmw** [comment]
把你代码 push 到你的 GitHub 我看下吧

**Comment by Guguzi** [comment]
我提交了, 麻烦你看一下, 到底是哪儿的问题, 困扰我好久了 @nswbmw

**Comment by nswbmw** [comment]
@Guguzi lib/mongo.js 21行：

```
item.create_at = moment(objectidToTimestamp(item.id)).format('YYYY-MM-DD HH:mm');
```

item.id -> item._id

敲代码要细心啊
