### ISSUE TITLE
请问heroku 部署失败是什么情况？

### ISSUE THREAD

**Issue by q8322564** [nswbmw/N-blog#261]
![1482304077 1](https://cloud.githubusercontent.com/assets/19646853/21380312/4cbc2cf4-c78f-11e6-9947-f2aa52229e35.png)

**Comment by gaoxiaosong1113** [comment]
我也试过了  在heroku上使用pm2部署启动不了，不知道是什么原因，然后直接启动node app了~~

**Comment by q8322564** [comment]
感谢回答，我最后也是用node app启动的，之前是因为终端上没有安装pm2，我后来将它加到了依赖里面，服务器不再报这个错误了，但是pm2又开始反复重启，不知道为什么，最终又是使用的node app启动的应用。

**Comment by gaoxiaosong1113** [comment]
我试了，在本地用pm2可以启动服务，经过这半个月的测试，也没发现进程断掉的情况，就放心使了

**Comment by nswbmw** [comment]
https://github.com/nswbmw/N-blog/commit/2a6aa3ba9f678757c26cd84eb9a2288cc36c4064
