### ISSUE TITLE
about req.fields

### ISSUE THREAD

**Issue by Spades-S** [nswbmw/N-blog#262]
看了您写的blog的源码，有点疑惑，如何将请求内容挂到req.fields?如果您有空的话，能解答下吗？谢谢

**Comment by Spades-S** [comment]
找到了express-formidable 对form做了解析，将请求内容挂载到了req.fields上

**Comment by nswbmw** [comment]
看一下 express-formidable

**Comment by Spades-S** [comment]
好的，谢谢啦 @nswbmw

**Comment by NetLogoclub** [comment]
@nswbmw  @Spades-S  express-formidable 是管理文件上传的，我想问一下，req.fields能够获得里面name，password那些值，是不是因为这个在表单里，而request就能够获得表单数据，谢谢
