### ISSUE TITLE
部署到UCloud 无法登录主机

### ISSUE THREAD

**Issue by rookielzy** [nswbmw/N-blog#263]
密码输入正确，重置了密码还是不行。
![image](https://cloud.githubusercontent.com/assets/9986800/21467613/4f68ae44-ca2f-11e6-9ccd-a3385e3d4065.png)
一直出现这种情况，实在不知道如何解决。
希望能解答一下，多谢！

**Comment by canvs** [comment]
用本地ssh连。。
