### ISSUE TITLE
mongolass.plugin 应该是 new mongolass().plugin

### ISSUE THREAD

**Issue by yangwenhaowenhe** [nswbmw/N-blog#264]
![gw7mgdcl yd 0kg 7v70sx](https://cloud.githubusercontent.com/assets/19327261/21591438/d6b8d30e-d13e-11e6-948a-12f7ae7b41ab.png)

**Comment by nswbmw** [comment]
Are you sure? 说说为啥

**Comment by nswbmw** [comment]
我猜你的意思是 mongolass 没有定义（从代码中看）？但上面我写的是 “添加如下代码”，即在原来的代码基础上添加的，之前是有：

```
var Mongolass = require('mongolass');
var mongolass = new Mongolass();
mongolass.connect(config.mongodb);
```
