### ISSUE TITLE
关于app.set('view engine', 'ejs')　抛出No default engine was specified and no extension was provided异常

### ISSUE THREAD

**Issue by flightgong** [nswbmw/N-blog#265]
使用
　　app.set('views', path.join(__dirname, 'views'));// 设置存放模板文件的目录
　　app.set('view engine', 'ejs');// 设置模板引擎为 ejs
抛出异常　No default engine was specified and no extension was provided.

参考
http://stackoverflow.com/questions/23595282/error-no-default-engine-was-specified-and-no-extension-was-provided/23596000

修改为
　　app.engine('html', require('ejs').renderFile);
　　app.set('view engine', 'html');
　　同时users.ejs改为users.html　运行成功

求问原因或者因为某些设置错误

**Comment by nswbmw** [comment]
你 Express 版本多少？我看那个给的链接的问题是 2014年的了

**Comment by flightgong** [comment]
版本为4.14.0

**Comment by nswbmw** [comment]
你把有问题的代码提交到你的 GitHub 我看下吧

**Comment by flightgong** [comment]
感谢大神, 问题解决了，是因为node版本，原来版本0.12, update到最新版本，问题解决
