### ISSUE TITLE
supervisor 体验不好

### ISSUE THREAD

**Issue by changchengqin** [nswbmw/N-blog#266]
supervisor 体验很不好,有没有类似于热部署之类的方案?

**Comment by nswbmw** [comment]
supervisor 体验不好怎么讲？你所说的热部署具体想怎么个部署法

**Comment by yun313350095** [comment]
哪里不好啊..我觉得还是不错的

**Comment by changchengqin** [comment]
1、每次修改一个文件，都是重新启动http服务器
2、我所说的热部署类似于：修改一个文件，不用重新启动http服务器，而是只更新修改的这个文件.

**Comment by nswbmw** [comment]
1. supervisor 只推荐在开发环境下用，没让你在线上用。。
2. 这种技术有（substack 写过一个，我找不到了，你搜搜），但没人会在 production 环境下用，可能有一些副作用吧。。`pm2 gracefulReload` 就足够了。

**Comment by changchengqin** [comment]
就是在 开发环境 使用.

**Comment by nswbmw** [comment]
那这样都满足不了你吗。。

**Comment by trylovetom** [comment]
你可以用nodemon
