### ISSUE TITLE
3.3.1 ejs出现错误。

### ISSUE THREAD

**Issue by Hillkinsh** [nswbmw/N-blog#270]
按照教程，本应该是下面的结果：

![image](https://cloud.githubusercontent.com/assets/16912205/21719271/c2a01b68-d457-11e6-93ae-b86711db7e68.png)
可是，我的显示结果为：
![image](https://cloud.githubusercontent.com/assets/16912205/21719321/15df9f60-d458-11e6-904e-8bfd453ab8d6.png)
所以该怎么解决呢？？

**Comment by nswbmw** [comment]
1. 检查是否设置了 app.set('view engine', 'ejs');
2. 检查 views 目录下是否有 users.ejs

**Comment by Hillkinsh** [comment]
谢谢博主的提醒。如果真的马虎如此，我也定当无脸提问。
我在stackoverflow上找到了答案：ejs全局安装不好用，又重新装了一遍非全局的。

**Comment by nswbmw** [comment]
@Hillkinsh 解决了吗，解决了就 close 吧
