### ISSUE TITLE
博主，部署问题你看一下。

### ISSUE THREAD

**Issue by Hillkinsh** [nswbmw/N-blog#272]
在云主机上。这样是部署成功了吧？
![image](https://cloud.githubusercontent.com/assets/16912205/21885735/f28514c8-d8f3-11e6-9703-c480f4cefb6d.png)
但是在
![image](https://cloud.githubusercontent.com/assets/16912205/21885752/0b3f2c60-d8f4-11e6-86d9-15c3100c763d.png)
打开却不行
![image](https://cloud.githubusercontent.com/assets/16912205/21885828/5bc628aa-d8f4-11e6-8316-b487b6f83b3d.png)
所以，是哪里的问题呢？

**Comment by nswbmw** [comment]
你起的端口是80吗

**Comment by Hillkinsh** [comment]
是的。这是我按照你说的做的
![image](https://cloud.githubusercontent.com/assets/16912205/21886632/a0e42b3c-d8f7-11e6-9e1f-e7c6d9b04218.png)

**Comment by nswbmw** [comment]
1. 检查安全组是否开放 80 端口
2. 有时候 linux 不允许占用 80 端口，可以监听 1024 以后的端口，然后用 nginx 反向代理
