### ISSUE TITLE
4.5页面设计完成之后，就报错user is not defined，实在解决不了，求博主帮忙看看

### ISSUE THREAD

**Issue by daxiongz** [nswbmw/N-blog#273]
![image](https://cloud.githubusercontent.com/assets/19296863/21889264/095b16de-d903-11e6-939c-3d7ac13b0055.png)
user 已经按照教程在index.js文件设置过了
![image](https://cloud.githubusercontent.com/assets/19296863/21889339/6cf1a08c-d903-11e6-965f-998e2c28626e.png)

**Comment by GuoJieLun** [comment]
朋友,你的router(app)放错位置了,应该是放到第55行.

**Comment by daxiongz** [comment]
谢谢，是我太马虎了
