### ISSUE TITLE
你好,博主. 关于文章详情页用_id来做查询条件的问题

### ISSUE THREAD

**Issue by GuoJieLun** [nswbmw/N-blog#274]
查看文章详情页通过用 _id做主键,用Mongolass请问要做么做,用Mongolass.Types.ObjectId()会报错. 
`   // 通过文章 id 获取一篇文章
    getPostById: function getPostById(postId) {

        return Post

            .find({ _id: postId })

            .populate({ path: '_id', model: 'User' })

            .addCreatedAt()

            .contentToHtml()

            .exec();
    }`

**Comment by nswbmw** [comment]
> 用Mongolass.Types.ObjectId()会报错.

把你出错的代码提交到你的 GitHub 我看下原因，我这复现不了。

**Comment by GuoJieLun** [comment]
问题解决了,是我这边的npm install插件的问题,我把你的pakage.json复制过去之后 重新install就可以了.
