### ISSUE TITLE
部署到heroku失败

### ISSUE THREAD

**Issue by huang303513** [nswbmw/N-blog#275]
我部署到heroku失败。我感觉是4.15里面的某句话我没有理解导致的。

`停止程序，然后以 production 配置启动程序:

NODE_ENV=production supervisor --harmony index

    注意：Windows 用户安装 cross-env，使用：

    cross-env NODE_ENV=production supervisor --harmony index
`

上面这一句话是如何设置啊？

**Comment by nswbmw** [comment]
```
npm i cross-env -g
```

**Comment by nswbmw** [comment]
https://github.com/nswbmw/N-blog/commit/2a6aa3ba9f678757c26cd84eb9a2288cc36c4064
