### ISSUE TITLE
关于教程中4.14里测试代码的不合理之处(test/signup.js)

### ISSUE THREAD

**Issue by fatbone008** [nswbmw/N-blog#277]
afterEach(function (done) {
      // 清空 users 表
      User.remove({})
        .exec()
        .then(function () {
          done();
        })
        .catch(done);
    });

每测试完后，User表都被清空了，下次访问该系统时，浏览器保留的Cookie中还有User信息。这时候会导致报错：渲染Posts.ejs中posts为undefined。因为浏览器从session中获取的User信息，在数据库中已经找不到了。所以建议此处改为：

afterEach(function (done) {
            // 清空 users 表
            User.remove({name:'aaa'})
                .exec()
                .then(function () {
                    done();
                })
                .catch(done);
        });

既然为了测试，插入了该数据，那么测试结束后，只需删除该数据即可，对吧？

**Comment by nswbmw** [comment]
嗯嗯，我改下
