### ISSUE TITLE
关于静态文件引入的错误

### ISSUE THREAD

**Issue by elva2596** [nswbmw/N-blog#279]
`app.use(express.static(path.join(__dirname,'public')));` 
博主按照你的教程这里设置正确，如果url是http://localhost:3000/posts ，则静态文件引入没有问题。
但是如果url变成:http://localhost:3000/posts/create/,则静态文件引入出错。

`GET http://localhost:3000/posts/create/css/dist/semantic.min.css 
localhost/:10 GET http://localhost:3000/posts/create/css/style.css 
localhost/:11 GET http://localhost:3000/posts/create/js/jquery-3.1.1.js 
localhost/:12 GET http://localhost:3000/posts/create/css/dist/semantic.min.js 
(index):86 Uncaught ReferenceError: $ is not defined
    at (index):86
(anonymous) @ (index):86
(index):65 GET http://localhost:3000/img/upload_86be837e961e493daa0b9b43b219e32b.jpg/ 404 (Not Found`

这是我的错误代码地址：[https://github.com/elva2596/my-blog/tree/master/myblog](url)

**Comment by LeoCecilia** [comment]
想问一下，问题最后是怎么解决的
