### ISSUE TITLE
关于第3章文件上传功能出现问题，可是看不懂，求提示？

### ISSUE THREAD

**Issue by kingzyl** [nswbmw/N-blog#28]
400 Error: ENOENT, open 'C:\Users\k\Desktop\public\images\5044-srk0ov'
一上传文件有时候前台报错，有时候前台一直处于获取状态，后台报这错，这是为什么啊？

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
