### ISSUE TITLE
关于插件系统

### ISSUE THREAD

**Issue by elva2596** [nswbmw/N-blog#281]
博主，一直跟着你的教程做，不懂的地方也去查了源码。但是本人水平有限，关于Mongolass中的插件系统有些不是很懂，能否解释一下？
```
Post.plugin(”addCommentsCount”, {
  afterFind: function (posts) {
    return Promise.all(posts.map(function (post) {
      return CommentModel
              .getCommentsCount(post._id)
              .then(function (commentsCount) {
                  post.commentsCount = commentsCount;
                                return post;
               });
        }));
  },
  afterFindOne: function (post) {
    if (post) {
      return CommentModel.getCommentsCount(post._id).then(function (count) {
        post.commentsCount = count;
        return post;
      });
    }
    return post;
  }
});

// 将 post 的 content 从 markdown 转换成 html
Post.plugin(“contentToHtml“, {
  afterFind: function (posts) {
    return posts.map(function (post) {
      post.content = marked(post.content);
      return post;
    });
  },
  afterFindOne: function (post) {
    if (post) {
      post.content = marked(post.content);
    }
    return post;
  }
});
```

问题1：自定义插件必须是按照
`Mongolass.plugin("插件名字"，{
      after(before)Find：function(args){
             return somrthing
       }
})`
比如afterFind函数的返回值有类型限制吗？
另外最上面那段代码为什么一定要加一个Promise.all把promise对象组成的数组转换为一个新的promise对象
但是下面的afterFind函数返回的就可以是一个数组，这是为什么呢？？？
问题2：关于链式调用，调用插件之后比如.addCommentsCount()之后返回的是query实例吗？

**Comment by nswbmw** [comment]
才看到。。这个 cnode 解释过了吧，那我关咯。Mongolass 可以看下我写的一篇文章：[从零开始写一个 Node.js 的 MongoDB 驱动库](https://zhuanlan.zhihu.com/p/24308524)

**Comment by ghCarol** [comment]
大大，我也有一样的疑惑：最上面那段代码为什么一定要加一个Promise.all把promise对象组成的数组转换为一个新的promise对象？然后我看您的回复，在cnode社区没查到您说的解释呀？

**Comment by nswbmw** [comment]
@ghCarol 插件函数只要保证执行后返回一个 porimise 即可，不管是 async 函数还是普通函数（执行后返回一个 promise）

**Comment by ghCarol** [comment]
可是下面的afterFind函数返回的不是数组吗，不是promise对象呀？

**Comment by nswbmw** [comment]
yield不用了，用的 async/await
