### ISSUE TITLE
4.4 Can't launch.

### ISSUE THREAD

**Issue by Ericglh** [nswbmw/N-blog#282]
提问方式：

1. 请先从错误栈自己定位问题，尝试亲自解决问题
2. 解决不了再去历史 isuue 里查看是否有相似的问题
3. 最后，提交新的 issue，并将错误代码提交到你的 GitHub，我抽空会帮你调试

不好的提问方式：

1. 只有标题，没有描述
2. 描述不清楚

**Comment by Ericglh** [comment]
Router.use() requires middleware function but got a Object

**Comment by gitlubtaotao** [comment]
谢谢你的指点。

從我的 iPhone 傳送
