### ISSUE TITLE
express-formidable导致post请求报错

### ISSUE THREAD

**Issue by douglasvegas** [nswbmw/N-blog#284]
> app.use(formidable({
> uploadDir: path.join(__dirname, 'public/upload/img'),// 上传文件目录
> keepExtensions: true// 保留后缀
> }))

这段代码后，同一个url，连着刷新两次就会报这样的错误：
`can't set headers after they are sent`
去掉这段代码，就ok了。

https://segmentfault.com/q/1010000008004591

**Comment by nswbmw** [comment]
> 同一个url

比如？做到哪一步了？

最好把代码提交到 GitHub，我抽空会帮你看下

**Comment by douglasvegas** [comment]
在使用formidable时只要post  /user我直接返回json会报错。
代码如下：

```
// post /user
router.post('/', function(req, res, next) {
    var user = {
      name: 'testname',
      phone: 13011110000,
      gender: 'm',
      age  : 21
    }
    //这样就会报错
    res.json({
      msg: 'test success'
    })

    //新建一个用户 这样正确
    UserModel.createAccount(user).then(function (result) {
      return res.json(result)
    }).catch(function (err) {
      console.log(err)
    })
})
```

**Comment by nswbmw** [comment]
因为你调用了两次 res.json 啊。。为什么要加：

```
res.json({
  msg: 'test success'
})
```

**Comment by douglasvegas** [comment]
因为我想做成接口。
那这样怎么改呢？


发自网易邮箱大师
在2017年01月25日 11:52，nswbmw 写道：

因为你调用了两次 res.json 啊。。为什么要加：

res.json({
  msg: 'test success'
})

**Comment by nswbmw** [comment]
根据 request 的 accept 头决定返回什么样的数据。
比如是： accept: aaplication/json，就用

```
res.json({
  msg: 'test success'
})
```

如果是：accept: text/html，就返回页面。

**Comment by douglasvegas** [comment]
thank you.我试试


发自网易邮箱大师
在2017年01月25日 12:08，nswbmw 写道：

根据 request 的 accept 头决定返回什么样的数据。
比如是： accept: aaplication/json，就用

res.json({
  msg: 'test success'
})


如果是：accept: text/html，就返回页面。

**Comment by douglasvegas** [comment]
不好意思、我还想问一下
为什么把formidable去掉就不存在这个问题。。。

**Comment by X140Yu** [comment]
@douglasvegas 
我也遇到了这个问题，改成用 body-parser 就没有问题了

**Comment by douglasvegas** [comment]
感觉还是express-formidable的问题啊、 @X140Yu 有代码看看么、不用formidable图片上传你用的啥

**Comment by nswbmw** [comment]
我抽空去掉 koa-formidable 用 multer 吧。。

**Comment by douglasvegas** [comment]
@nswbmw 是express-formidable😄、这个你用的时候没有报错过吗？

**Comment by ZJH9Rondo** [comment]
@nswbmw 我参照这个Pr 在我本地的node_modules 中更改了对应包的代码，这个错误就完全消失了，所以我觉得既然这个教程就已经写完了，就没必要在引用别的包折腾解释了，直接在READEME上加个说明更好，这样新来的看这个的记忆也能更深刻，毕竟，坑也是要踩的(为什么会出现这个错误，哪些情况会重写响应头之类就会去学习理解相关知识)，在此，感谢git教程，我在学习期间最后添加了收藏功能，加了爬虫(个人需要),最后，优化了路由设计(前辈当时写的是不是太急了)，最后贴上链接，分别是关于我做的，还有这个Pr的链接,放我的希望前辈能指点指点，晚辈准大三，还在爬坑

仓库：https://github.com/ZJH9Rondo/Blog-Node

express-formidable的BUG修复链接:　https://github.com/noraesae/express-formidable/pull/10/commits/d7b3a03cdf13879000f140c20e25598d428bad1d
