### ISSUE TITLE
session of undefined

### ISSUE THREAD

**Issue by a1029563229** [nswbmw/N-blog#286]
教程中 check.js
req.session.user
session报错undefined
已经加载了session组件 后面全部复制过来也不行

**Comment by nswbmw** [comment]
把你的代码提交到你的 GitHub 我看下吧

**Comment by csyezheng** [comment]
同样会出现这个错误，按照教程到4.4结束的时候会出现Cannot read property 'session' of undefined

**Comment by OleileiA** [comment]
我的情况是可以取到session，但是session中的user属性为undefined，我之前的注册和登录页的路由中都写了req.session.user  = user;现在每一个请求都被咱们自定义的中间件拦截了，我还没找到问题所在呢。

**Comment by OleileiA** [comment]
我的问题解决了，是跨域session重置的问题。所以保存的属性全都变成undefined。

**Comment by ChangeLeon** [comment]
咋解决的啊？

**Comment by yokipuppy** [comment]
我也碰到这个问题，请问怎么解决~~ @nswbmw @ChangeLeon @a1029563229 @csyezheng

**Comment by a1029563229** [comment]
我是因为打错了单词，所以导致了这个错误，现在问题解决了 你们可以直接复制代码试试，应该可以修复

**Comment by yokipuppy** [comment]
感谢回复，我应该也是敲错了，检查好久没检查到，才问你们，谢谢，已复制源代码已解决
