### ISSUE TITLE
想问下nswbmw大神、express-formidable

### ISSUE THREAD

**Issue by qinxiaojie8** [nswbmw/N-blog#289]
1：（文件命名）express-formidable怎么给文件重命名
2：（路径选择）怎么把同一个form表单中的多个文件存储进不同的文件夹中？

（15年夏天、我学过大神的本链接的旧版《一个简单的博客》、倒是会用那种

```
    destination: function (req, file, cb){
        cb(null, './public/work')
    },
    filename: function (req, file, cb){
        cb(null, req.session.user.account+".jpg")/
    }
```

也在网上找了formidable的单文件命名及存储路径的选择、可是都感觉比较麻烦、特来向求助）

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了
`var imgs = req.files.imgs1.path.split(path.sep).pop();`

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了
`router.post('/', checkNotLogin, function(req, res, next) {

  var avatar = req.files.avatar.path.split(path.sep).pop();
.
.
.`

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了

`router.post('/', checkNotLogin, function(req, res, next) {

        var avatar = req.files.avatar.path.split(path.sep).pop();
}
.
.
`

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了
`router.post('/', checkNotLogin, function(req, res, next) {

    var avatar = req.files.avatar.path.split(path.sep).pop();
}`

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了

```
router.post('/', checkNotLogin, function(req, res, next) {
var avatar = req.files.avatar.path.split(path.sep).pop();
}
```

**Comment by qinxiaojie8** [comment]
我是想着、能不能在这里动动手脚、给把文件名和路径给改了

```
router.post('/', checkNotLogin, function(req, res, next) {

     var avatar = req.files.avatar.path.split(path.sep).pop();

}
```

**Comment by nswbmw** [comment]
1. 貌似只能用 `fs.rename` 了。见：[https://www.npmjs.com/package/formidable#formidableincomingform](https://www.npmjs.com/package/formidable#formidableincomingform) 和 [http://stackoverflow.com/questions/8359902/how-to-rename-files-parsed-by-formidable](http://stackoverflow.com/questions/8359902/how-to-rename-files-parsed-by-formidable)
2. 这个也不行。只能在代码里判断下（比如 mime type），用 `fs.rename`

**Comment by qinxiaojie8** [comment]
好，谢谢大神，有点激动和大神沟通
