### ISSUE TITLE
楼主你好，谢谢你的教程。但是现在这样的话，比如当页面一直刷新的话，很快就会发生事件监听器超过11个的警告了。路由器在注册监听方法的时候应该怎么把不需要的监听器去掉呢？或者是我的想法有问题吗？谢谢

### ISSUE THREAD

**Issue by useliuqing** [nswbmw/N-blog#290]
提问方式：

1. 请先从错误栈自己定位问题，尝试亲自解决问题
2. 解决不了再去历史 isuue 里查看是否有相似的问题
3. 最后，提交新的 issue，并将错误代码提交到你的 GitHub，我抽空会帮你调试

不好的提问方式：

1. 只有标题，没有描述
2. 描述不清楚

**Comment by nswbmw** [comment]
事件监听器超过11个的警告是 express-formidable 报的吧，试试替换成 multer
