### ISSUE TITLE
博主，为啥不考虑弄个个人站点完整实现下呢？

### ISSUE THREAD

**Issue by doubleflying** [nswbmw/N-blog#291]
可以弄个国外的LiNode主机性价比不错的，本人也在尝试用Node去实现个个人站点，包括博客功能，目前刚搭建好了基本功能，除了留言。地址是这个：http://www.doublefly.cc  还在开发阶段，看到你的这篇分享很希望能结合着改改，如果博主能够搞个可以公开访问的个人站点我觉得效果应该会更好！

**Comment by nswbmw** [comment]
这个博客教程是简单的面向初学者的，也没有分页，归档之类的。还有就是个人兴趣不大。。写文章的话就放到知乎专栏里了。
