### ISSUE TITLE
MLab链接不成功

### ISSUE THREAD

**Issue by SeongBrave** [nswbmw/N-blog#293]
博主您好，一下是我申请的MLab数据服务
![image](https://cloud.githubusercontent.com/assets/10784393/22767270/3b796bc6-eeb5-11e6-87e8-86128166ac23.png)
但是z在我本地测试链接的时候显示一下错误：
![image](https://cloud.githubusercontent.com/assets/10784393/22767297/6e2a6c46-eeb5-11e6-9477-36ec34a55737.png)
 难道是因为我本地安装的mongodb的版本与服务器的3.2.12 的版本不一样导致的吗？

**Comment by linmodev** [comment]
在新建数据库后要在User里创建一个数据库用户

**Comment by SeongBrave** [comment]
@linmodev  恩恩，多谢了，昨天发现这个问题了

**Comment by LukerSpringtree** [comment]
@SeongBrave  为什么我点不了 注册页面最新的 I aceept 那个单选框啊.
我连 MLab都注册不了.
求教一下,

**Comment by SeongBrave** [comment]
@LukerSpringtree 界面打不开？你用代理打开试试
