### ISSUE TITLE
跳转首页时无法获取author

### ISSUE THREAD

**Issue by zyb284629791** [nswbmw/N-blog#294]
博主你好，我在首页跳转的代码里面始终无法获取到author。
var author = req.query.author; 这行代码req.query是个空对象，我理解的是这里要从地址栏或者其他地方获取参数，但是看您在文章中写的直接访问localhost:3000/posts，我按照这个方法并不能成功跳转页面。麻烦帮忙解释一下。谢谢!

**Comment by nswbmw** [comment]
跳转到首页的的确没有 author，这个 author 是从页面里跳转过来的，比如 post-content.ejs:5。而且 models/posts.js:62 是做了判断的，没有 author（即没有限定作者）返回全站文章，有 author 返回这个用户的文章。
