### ISSUE TITLE
BodyParser vs Formidable

### ISSUE THREAD

**Issue by trylovetom** [nswbmw/N-blog#296]
您好，我有買您寫的書，書中是使用BodyParser與Multer來處理form-data。想請教下，新版本採用Formidable的原因，分析一下利與弊，謝謝。

**Comment by nswbmw** [comment]
formidable 和 multer 可以上传文件，而 bodyParser 不能，选择 formidable 的原因是用起来比 multer 简单。。

**Comment by trylovetom** [comment]
感謝您，這麼晚還回覆小弟的問題。
