### ISSUE TITLE
部署到了UCloud，但是服务器上出现了这个问题（express-session），导致网站打不开

### ISSUE THREAD

**Issue by camellieeee** [nswbmw/N-blog#297]
<img width="820" alt="error" src="https://cloud.githubusercontent.com/assets/18331008/22897156/9f74c35e-f25d-11e6-8d1f-0278fbbc4404.png">

好像是express-session 的问题，issues里面有人提及过，试着改过，但是最终还是没有明白问题所在，以及如何解决

**Comment by nswbmw** [comment]
去 UCloud 上，创建 logs 目录试试
```bash
mkdir log
```

**Comment by xianfei689** [comment]
我也遇到了同样的问题  已经有logs目录还是有问题

**Comment by xianfei689** [comment]
![Uploading image.png…]()

**Comment by camellieeee** [comment]
@xianfei689 我的已经解决了，在工程目录的上级目录新建logs

**Comment by xianfei689** [comment]
@camellieeee  你还会报那个错误么  我新建了  好像还是不行  是不是要重启啊

**Comment by camellieeee** [comment]
@xianfei689 你的外网地址是115.238.43.242还是120.132.12.117啊？ 运行下  ssh root@你的外网地址  试试

**Comment by xianfei689** [comment]
@camellieeee   
部署的时候报这个错

[root@10-25-17-146 logs]# vim myblog-error-0.log 
Fri, 17 Feb 2017 06:17:57 GMT express-session deprecated undefined resave option; provide resave option at index.js:22:9
Fr,s-session deprecated undefined resave option 17 Feb 2017 06:17:57 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:22:9

**Comment by nswbmw** [comment]
这是警告，不是报错

**Comment by xianfei689** [comment]
@camellieeee 

具体是这样的 : 
 
[root@10-25-17-146 myblog]# npm start

> myblog@1.0.0 start /root/myblog
>  NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog'

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /root/myblog/index.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ myblog   │ 0  │ fork │ 1189 │ online │ 0       │ 0s     │ 42% │ 13.7 MB   │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[root@10-25-17-146 myblog]# pm2 logs
[TAILING] Tailing last 10 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 10 lines:
PM2        | 2017-02-17 14:17:56: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2017-02-17 14:17:56: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2017-02-17 14:17:56: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2017-02-17 14:17:56: Application log path : /root/.pm2/logs
PM2        | 2017-02-17 14:17:56: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2017-02-17 14:17:56: Concurrent actions   : 2
PM2        | 2017-02-17 14:17:56: SIGTERM timeout      : 1600
PM2        | 2017-02-17 14:17:56: ===============================================================================
PM2        | 2017-02-17 14:17:56: Starting execution sequence in -fork mode- for app name:myblog id:0
PM2        | 2017-02-17 14:17:56: App name:myblog id:0 online

/root/.pm2/logs/myblog-error-0.log last 10 lines:
0|myblog   | Fri, 17 Feb 2017 06:17:57 GMT express-session deprecated undefined resave option; provide resave option at index.js:22:9
0|myblog   | Fri, 17 Feb 2017 06:17:57 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:22:9

/root/.pm2/logs/myblog-out-0.log last 10 lines:
0|myblog   | myblog listening on port 80

[STREAMING] Now streaming realtime logs for [all] processes
^C
[root@10-25-17-146 myblog]# ^C
[root@10-25-17-146 myblog]# cd ..
[root@10-25-17-146 ~]# cd ..
[root@10-25-17-146 /]# ls
bin   data  etc   lib    logs        media  opt   root  selinux  swapfile  tmp  var
boot  dev   home  lib64  lost+found  mnt    proc  sbin  srv      sys       usr
[root@10-25-17-146 /]# cd root/.pm2/logs/myblog-error-0.log 
-bash: cd: root/.pm2/logs/myblog-error-0.log: Not a directory
[root@10-25-17-146 /]# cd root/
[root@10-25-17-146 ~]# ls
logs  myblog  tmp
[root@10-25-17-146 ~]# cd .pm2
[root@10-25-17-146 .pm2]# cd logs/
[root@10-25-17-146 logs]# vim myblog-error-0.log 
Fri, 17 Feb 2017 06:17:57 GMT express-session deprecated undefined resave option; provide resave option at index.js:22:9
Fr,s-session deprecated undefined resave option 17 Feb 2017 06:17:57 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:22:9

**Comment by xianfei689** [comment]
@nswbmw : 楼主大大:  

有空可以帮忙看下我的代码

**Comment by temool** [comment]
我在本地也遇到了这个情况，意思是express-session 不能用了吗？

**Comment by nswbmw** [comment]
参考最新教程
