### ISSUE TITLE
新手，实在是看不懂 result.ops[0] ，这个ops是哪里来的

### ISSUE THREAD

**Issue by leonbaichi** [nswbmw/N-blog#304]
博主，您好！感谢您的教程！受益良多！

 PostModel.create(post)
    .then(function (result) {
      // 此 post 是插入 mongodb 后的值，包含 _id
      post = result.ops[0];    //这里看不懂了！！！！！！！
      req.flash('success', '发表成功');
      // 发表成功后跳转到该文章页
      res.redirect(`/posts/${post._id}`);
    })
    .catch(next);
});

新手，实在是看不懂 result.ops[0] ，这个ops是哪里来的？您能说的详细点吗？
十分感谢！

**Comment by nswbmw** [comment]
打印下 result 看看就知道了

**Comment by Jackzhangpan** [comment]
我也不懂，请问打印出来是什么？不知道怎么打印 @nswbmw @leonbaichi
