### ISSUE TITLE
这个问题只会占用你一分钟不到！

### ISSUE THREAD

**Issue by ranchoopenwrt** [nswbmw/N-blog#309]
首先 感觉博主分享！

问题：看不懂下面语句
期望解答：知道对应的api和配置项的资料位置
语句：
      User.index({ name: 1 }, { unique: true }).exec();
主要想知道 像index exec()和 里面的配置项  name: 1  unique: true ，是哪个库的api 是您自己写的mangolass吗？还是···？

**Comment by nswbmw** [comment]
.index 是 .ensureIndex 的 alias，见：https://github.com/mongolass/mongolass/blob/master/lib/model.js#L24

Mongolass 的 Model 相当于 mongodb 的 collection，见我知乎上[一篇文章](https://zhuanlan.zhihu.com/p/24308524)。

**Comment by ranchoopenwrt** [comment]
好的 谢谢 我先把你的文章通读一遍~ 谢谢分享！
