### ISSUE TITLE
上傳文章還能多加圖片這方面的問題

### ISSUE THREAD

**Issue by TranquilityDev** [nswbmw/N-blog#311]
您好, 想請教關於上傳文章還能多加圖片這方面的問題, 不知要怎麼增加這功能

我嘗試在routes/post.js
`router.post('/', checkLogin, function(req, res, next) {
var form = new formidable.IncomingForm()
form.uploadDir = path.join(__dirname, 'public/uploads');
.....`
但是不管怎麼上傳都會跑到 public/img

能請教大神這方面要怎麼修改才能完整達成 "文章+圖片" 
謝謝

**Comment by nswbmw** [comment]
参考下 cnode，这个教程只涉及到 markdown
