### ISSUE TITLE
“更新一篇文章” 的路由好像写错了

### ISSUE THREAD

**Issue by Angewell** [nswbmw/N-blog#314]
你好，博主！先感谢博主的分享，特别特别到位，膜拜一下！

在routes/posts.js里，“更新一篇文章”这里的路径跟上边“更新文章页”的路径重了，都是 `'/:postId/edit'`

`// POST /posts/:postId/edit 更新一篇文章
router.post('/:postId/edit', checkLogin, function(req, res, next) {`

我改成了

`// POST /posts/:postId/update 更新一篇文章
router.post('/:postId/update', checkLogin, function(req, res, next) {`

并把 views/edit.ejs中
`<form class="ui form segment" method="post" action="/posts/<%= post._id %>/edit">`
改成了
`<form class="ui form segment" method="post" action="/posts/<%= post._id %>/update">`

这样做下来就可以完成整个流程了。

**Comment by nswbmw** [comment]
能具体指出那个地方吗？

**Comment by Angewell** [comment]
先道歉，对不起博主，新手看错了。
在routes/posts.js里，89行跟109行。
实在不好意思，两个请求方法不同，一个是get，一个是post，我一开始以为是一样呢。原谅我这个小白，不过拜读之后，受益匪浅。已支持博主开源，666
