### ISSUE TITLE
MongoError: failed to connect to server [localhost:27017] on first connect

### ISSUE THREAD

**Issue by dmy147** [nswbmw/N-blog#315]
按照教程 使用`node --harmony index`时报错
![image](https://cloud.githubusercontent.com/assets/20147371/23543164/e57d70a4-002b-11e7-811e-72ac2e0565f1.png)
单独使用`mongo`命令也不可以
![image](https://cloud.githubusercontent.com/assets/20147371/23543197/177995ba-002c-11e7-8c8e-35ea402bfe43.png)
希望大大能够指点下

**Comment by nswbmw** [comment]
mongodb 起了吗

**Comment by FrancisShi** [comment]
mongod起了`➜  ~ mongo
MongoDB shell version v3.4.3
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.3`
但是还是报上面的错误

**Comment by MBearo** [comment]
@FrancisShi 是不是发错人了？

**Comment by FrancisShi** [comment]
@MBearo 木有呀。这个问题解决了嘛

**Comment by pihat** [comment]
应该是没起来，把路径换成纯英文的，而且应该还要给mongodb指定一个存放数据的目录，并且有读写权限

**Comment by HydeSong** [comment]
到底怎么弄啊？ 是不是没有建数据库啊

**Comment by Maxiaoxiang** [comment]
1. 到Mongo安装目录下，例如：D:\mongoDB\bin\，查看版本确保安装成功`mongo --version`
2. 在D盘根目录新建文件夹`MongoDBData`输入`mongod --dbpath D:MongoDBData`启动MongoDB
3. 打开浏览器，输入`http://localhost:27017`，如果能看到如下所示文字表示启动成功
`It looks like you are trying to access MongoDB over HTTP on the native driver port.`
希望对你有帮助

**Comment by suweiz19890921** [comment]
我也遇到这个问题了，求解答 
![snip20170606_114](https://cloud.githubusercontent.com/assets/17306517/26819462/84745246-4ad1-11e7-8c83-ccc6863e6ff3.png)

**Comment by jiayouzhao** [comment]
1. 博客根目录建立db文件夹
2. 运行mongodb .找到mongodb文件下面的bin文件，路径写博客地址   

    ![mongodb](https://user-images.githubusercontent.com/21123714/26910857-10061108-4c3c-11e7-9e2b-4a0af43b5a5f.png)
3. supervisor --harmony index

**Comment by 302wanger** [comment]
这个报错原因就是mongodb没跑起来。
我的是Mac电脑
1. 打开终端
2. brew install mongodb
3. mkdir -p /data/db
4. sudo mongod （用管理员模式运行，才能正常运行。这个要单独打开一个终端）
5. 输入密码，运行成功
