### ISSUE TITLE
提交注册的表单报错 

### ISSUE THREAD

**Issue by leinov** [nswbmw/N-blog#322]
提问方式：
![image](https://cloud.githubusercontent.com/assets/6204210/23645994/d6460bf2-0349-11e7-9119-a3395b672137.png)

**Comment by Alyipce** [comment]
我和你曾经碰到相同的问题，后来发现问题出在index.js文件中 写出了一段代码：
//处理表单以及文件上传的中间件
app.use(require('express-formidable')({
	uploadDir:path.join(__dirname,'public/img'),
	keepExtensions:true
}));
你看下你的有没有写错

**Comment by zwchao** [comment]
![issues](https://cloud.githubusercontent.com/assets/23334478/25062851/b0863b26-2207-11e7-9110-8da11bdd8d29.png)
同遇到这种情况，查看了index.js 文件的相关代码，并没有出错。

**Comment by JobbyM** [comment]
@zwchao 我也遇到这个问题了，不过是由于在signup.ejs 中
```
<form action="" class="ui form segment" method="post" enctype="multipart/form-data">
```
中的`enctype="multipart/form-data"` 书写错误导致的，你可以检查一下是否这里有问题。
