### ISSUE TITLE
最后部署后，访问我的公网ip却得到一个默认的网站欢迎页面

### ISSUE THREAD

**Issue by hackjus** [nswbmw/N-blog#323]
![a](https://cloud.githubusercontent.com/assets/19831373/23695050/4e4e7d9a-0418-11e7-9ba2-cb2f223c1917.png)
其他的都是按照提示安装 的，用的是腾讯云的centos
新手没有部署过这种东西，求解答！

**Comment by OOnnnOO** [comment]
要删除默认主页？系统中有安装其他的WEB服务器程序吧？

可以先试一下将程序运行在3000端口，然后通过ip:3000看是否可以访问网站呢

**Comment by nswbmw** [comment]
1. 尝试将配置 port 改为 80
2. Nginx 反向代理
