### ISSUE TITLE
option expires is invalid

### ISSUE THREAD

**Issue by NotGeekAtAll** [nswbmw/N-blog#331]
一直照着敲，写完路由后启动服务器出现这个问题，
![4dbc5ab0-56b5-46c1-b3be-c252757d423f](https://cloud.githubusercontent.com/assets/16792509/24001773/00ed9abc-0a9a-11e7-9ead-eff1ab4c98ad.png)
好像是cookie的过期时间问题，也没查出解决了

**Comment by nswbmw** [comment]
看看你 index.js 中的 maxAge 设置的对吗

**Comment by NotGeekAtAll** [comment]
@nswbmw 我把maxAge写的字符串，谢谢了
