### ISSUE TITLE
注册页面点击提交按钮显示无法访问

### ISSUE THREAD

**Issue by muzishuiji** [nswbmw/N-blog#332]
@nswbmw  注册页面点击提交按钮显示无法访问

我就是按照您的代码里面那样写的，登录页面就可以正常运行，但是注册页面一点击注册按钮就报错，我在post方法的最开始打印一段字符串，都不行，似乎这个函数都没有被执行，始终找不到原因
报错信息是这样的：
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\开发工具\node\testbox\myblog\punlic\img\upload_3a313abd550dd4f20ef0dc26898fec6c'
    at Error (native)
Program node --harmony index exited with code 1`
一直找不到原因，好捉急。求大神指教。

**Comment by nswbmw** [comment]
https://github.com/nswbmw/N-blog/issues/206
