### ISSUE TITLE
文章创建成功但是没有跳转到文章页

### ISSUE THREAD

**Issue by muzishuiji** [nswbmw/N-blog#333]
@nswbmw ，博主你好，
creat成功以后根据id查找这个文章，数据库里面是有这个id的，但是查找的结果result[0]显示的是undefind，这个函数这样写有错误吗？您的那个写法打印出来的post._id是${post._id},所以我改成这样，打印出来的post._id是58cb665a2d222a1ce03c3edf，数据库里也有这条数据，但是找不到是为啥？
`PostModel.create(post)
        .then(function(result) {
            //此post是插入mongodb后的值，包含_id
            post = result.ops[0];
            req.flash('success', '发表成功');
            res.redirect('/posts/' + post._id);
        })
        .catch(next);`

**Comment by muzishuiji** [comment]
@nswbmw  博主，和他们遇到的一样，我换成find就可以找到了，但是有报错
报错信息
`[ { _id: 58cb882c9ec2311c583c2a46,
    author: 58cb65112985cb268408ec1f,
    title: '东方红',
    content: '个性化',
    pv: 0 } ]
[ { _id: 58cb882c9ec2311c583c2a46,
    author: 58cb65112985cb268408ec1f,
    title: '东方红',
    content: '<p>个性化</p>\n',
    pv: 0,
    created_at: '2017-03-17 14:54' } ]
Error: Failed to lookup view "post" in views directory "D:\开发工具\node\testbox\myblog\views"
    at EventEmitter.render (D:\开发工具\node\testbox\myblog\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (D:\开发工具\node\testbox\myblog\node_modules\express\lib\response.js:966:7)
    at D:\开发工具\node\testbox\myblog\routes\posts.js:68:17`
求指导！！万分感谢

**Comment by day-dreamerTo** [comment]
是不是findOne({_id:postId})写成了findOne({id:postId})；'_'忘了...

**Comment by day-dreamerTo** [comment]
是不是findOne({id:postId})写成了findOne({id:postId})；''忘了... @muzishuiji

**Comment by muzishuiji** [comment]
@day-dreamerTo 你说的那两个不是一样的吗？

**Comment by day-dreamerTo** [comment]
抱歉啊，我写错了，应该是   findOne({_id:postId})写成了findOne({id:postId}),前面的多了个  @'_'，下划线 @muzishuiji

**Comment by muzishuiji** [comment]
@day-dreamerTo  应该不是，因为换fibd就可以找到了

**Comment by day-dreamerTo** [comment]
哦哦，我这边是这么个原因 @muzishuiji

**Comment by LeoCecilia** [comment]
@muzishuiji，想请问一下你最后是怎么解决的，我也遇到了这个问题
``` error
Error: Failed to lookup view "post" in views directory "F:\nBlog\views"
    at EventEmitter.render (F:\nBlog\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (F:\nBlog\node_modules\express\lib\response.js:971:7)
    at F:\nBlog\routes\posts.js:74:9
```

**Comment by LeoCecilia** [comment]
啊，我發現了是什麽問題了，因爲我并沒有在views目錄下創建post.ejs文件，不知道你是不是也是這個問題@muzishuiji
