### ISSUE TITLE
博主 要是想添加博客管理员的话应该从哪儿入手

### ISSUE THREAD

**Issue by zhoujinhai** [nswbmw/N-blog#337]

**Comment by zhoujinhai** [comment]
可以查看所有用户 可以查看和删除文章及留言

**Comment by nswbmw** [comment]
简单点的话，user 加个 isAdmin 字段，ejs 里判断 user.isAdmin 显示是否有删除文章和留言的 button，当然，这个操作也是要验证是否是 admin。
