### ISSUE TITLE
在windows 部署遇到的问题  

### ISSUE THREAD

**Issue by dongwenxu** [nswbmw/N-blog#338]
cross-env安装上了 在命令行上运行 cross-env NODE_ENV=production supervisor --harmony index  时报错

'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by Iszzh** [comment]
兄弟，你的问题解决没有？我也遇到同样的问题，也安装了cross-env

**Comment by family2hu** [comment]
是否全局安装？

**Comment by nswbmw** [comment]
windows 下全局安装 cross-env

```sh
npm i cross-env -g
```
