### ISSUE TITLE
supervisor: command not found

### ISSUE THREAD

**Issue by hobartSimple** [nswbmw/N-blog#341]
windows
supervisor 装了 但是 执行supervisor --harmony index 报supervisor: command not found

**Comment by nswbmw** [comment]
是全局装的吗

**Comment by zzw918** [comment]
supervisor 不需要全局安装。
也许是没有安装成功？

**Comment by huoguangxuan** [comment]
我也遇到了类似的问题，不过解决了。要到安装目录看一下supervisor命令的名字是不是supervisor，我的安装完是node-supervisor index 命令

**Comment by AChaoZJU** [comment]
最好发下你安装后的信息提示截图。
