### ISSUE TITLE
博主 请问一下查询文章的时候怎么限制数量

### ISSUE THREAD

**Issue by zhoujinhai** [nswbmw/N-blog#343]
router.get('/', function(req, res, next) {
  var author=req.query.author;

  PostModel.getPosts(author)
	  .then(function (posts){
         res.render('posts',{
		   posts:posts
		 });
       })
	  .catch(next);
});

**Comment by zhoujinhai** [comment]
用limit(number)的时候显示未定义
PostModel.getPosts(author).limit(4)
.then(function (posts){
res.render('posts',{
posts:posts
});
})
.catch(next);
});

**Comment by zhoujinhai** [comment]
知道了 谢谢

**Comment by nswbmw** [comment]
可以加到 query 里，如：limit。然后 find().limit(xxx).exec()
