### ISSUE TITLE
老大 如何对文章实现排序

### ISSUE THREAD

**Issue by zhoujinhai** [nswbmw/N-blog#346]
我想通过点击按日期排序或者按用户名排序按钮 实现内容重排  应该从哪儿入手

**Comment by nswbmw** [comment]
url 里加 query 参数如：

```
http://localhost:3000/posts?sort=xxx
```

sort 可以是：date|-date|author|-author

后端收到 req.query.sort，Post.find().sort({ xxx: 1|-1 }).exec()，别忘了加索引

**Comment by zhoujinhai** [comment]
谢谢

**Comment by zhoujinhai** [comment]
老大  我设url为http://localhost:3000/users/lists?sort=name，但用户列表排序不行啊

//查看普通用户
router.get('/lists',checkLogin,function(req,res,next){
   var xxx=req.query.sort;//按sort排序
   var page=Number(req.query.page||1);//当前页 默认为第1页
   var limit=10;//每页显示数量
   var skip=(page-1)*limit;//第i页跳过的数量

   
   User.count().then(function(count){
	   //计算总页数
	   pages=Math.ceil(count/limit);
	   //取值不能超过pages,不能小于1
           page=Math.min(pages,page);
	   page=Math.max(page,1);

           User.find().sort({xxx:1}).limit(limit).skip(skip).addCreatedAt()
	        .then(function(users){
		       res.render('list-users',{
		          users:users,
			  pages:pages,
                         page:page
		  });
       }) 
     })
     .catch(next);
});
