### ISSUE TITLE
3.3节，访问http://localhost:3000/users/haha 提示Cannot GET /users/haha

### ISSUE THREAD

**Issue by wangmeijian** [nswbmw/N-blog#347]
访问localhost:3000/users反而可以，参数name = users，貌似路由只匹配根目录下的index里的路径，routes/users.js里的/:name没有起作用，代码提交至[我的git](https://github.com/wangmeijian/myblog)，如果有空麻烦帮忙看看，谢谢

**Comment by nswbmw** [comment]
index.js 里用 app.use 替代 app.get 试试。。

**Comment by wangmeijian** [comment]
好尴尬
