### ISSUE TITLE
config-lite 使用最新v2版本的时候引入时需要传入(__dirname)

### ISSUE THREAD

**Issue by Yevvb** [nswbmw/N-blog#348]
启动时 config.session.key 一直报错：

`TypeError: cannot read property 'key' of undefined`

查看 [config-lite](www.npmjs.com/package/config-lite) 包说明时发现：

> in v2,you should specify `config_basedir` directory for bubbling find config file.

使用方式改为： `var config = require('config-lite')(__dirname);`

问题产生的根源是依赖模块的版本变更造成的，npm 下载依赖时并未指定依赖的版本。

**Comment by nswbmw** [comment]
My bad，我更新下教程

**Comment by LiamShao** [comment]
修改后还是报这个错怎么回事TypeError: Cannot read property 'key' of undefined
