### ISSUE TITLE
mongolass插入数据的 create方法的实现 未找到

### ISSUE THREAD

**Issue by duanbowen** [nswbmw/N-blog#349]
##  请问mongolass在向mongodb插入一个用户的create 方法是如何实现的(User.create(user).exec();)？
     在mongolass  一直没找到插入用户时候 User.create(user).exec() 这一句话里面的create 方法的实现

![Uploading QK{{10FO90X@W3D0VCV7345.png…]()

我找到这里  mongolass 模块里面的model.js 的部分代码 
```js
class Model {
  constructor(name, schema, db, opts) {
    this._db = db;
    this._schema = schema;
    this._name = name;
    this._collName = inflected.pluralize(name).toLowerCase();
    this._opts = opts;
    this._plugins = {};

    this._connect();
    Query.bindQuery(this, mongodb.Collection);

    //alias 我找到这里 然后没办法继续下去了 一直没看到插入用户时候 User.create(user).exec() 这一句话里面的create 方法的实现
    this.create = this.insert;
    this.index = this.ensureIndex;

    _.defaults(this._plugins, this._db._plugins);
  }

```

**Comment by nswbmw** [comment]
create 是 insert 的别名，index 是 ensureIndex 的别名。就是上面的代码，参考官方的 api：http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#insert

**Comment by duanbowen** [comment]
哈哈 看到了谢谢博主 very much！
