### ISSUE TITLE
你好，关于gitbook中populate的用法不解。

### ISSUE THREAD

**Issue by benny201** [nswbmw/N-blog#350]
首先谢谢博主的gitbook让我学到了很多东西。
其中有个问题是查阅了资料之后我也不是很懂博主的populate的用法：
如下（我改用成了mongoose）：
博主创建了user和post的model，在设置schema的时候并没有设置关联"例如ref：xxx"，但是在getPost中直接用populate提取了关联的user数据，
return Post
      .find(query)
      .populate({ path: 'author',  model: 'User' })
      .sort({ _id: -1 });
虽然成功了，但是我不知道为什么不做关联也可以通过直接搜user这个model就能找到对应的文档，博主能解析一下吗，谢谢！

**Comment by nswbmw** [comment]
Mongolass 和 Mongoose 不一样。Mongolass 指定 model : 'User'，就会关联 users 了。不用 ref

**Comment by AnthonyYY** [comment]
@benny201 一开始也没弄明白这个populate的。
其实每个post文档的author字段存储的是对应user文档的_id，每次查询出post文档结果之后，对所有的post文档，通过其author字段对应的_id去查询相对应的user文档信息，重新赋值到anthor字段里。这个实现在nswbmw大神自己写的模块里[mongolass-plugin-populate](https://github.com/mongolass/mongolass-plugin-populate/blob/master/index.js)

**Comment by yourenA** [comment]
@AnthonyYY 请问一下哪里定义有author与user文档的_id对应
