### ISSUE TITLE
想使用mongoose实现monglass的插件

### ISSUE THREAD

**Issue by jokingGao** [nswbmw/N-blog#359]
博主您好，
新手刚刚开始学习nodejs， 现在想使用mongoose实现monglass插件一样的功能。 能够在每次query之后加上一个临时的commentsCount的property在post上，模仿着网上写了一个，但是发现始终添加不上。网上也没有搜到相关的资料，希望博主能够帮忙看看， 多谢了

var postSchema = new Schema({
    author: {type: Schema.Types.ObjectId},
    content: String,
    title: String,
    view: Number
});

var addCommentsCount = function(schema) {
    schema.post('find', function(posts) {
        return Promise.all(posts.map(function(post){
            return commentModel.getCommentsCount(post._id).then(function(commentsCount) {
                post.commentsCount = commentsCount;
                //console.log(post);
                return post;
            });
        })); 
    });
    schema.post('findOne', function(post) {
        if (post) {
            return commentModel.getCommentsCount(post._id).then(function(commentsCount) {
                post.commentsCount = commentsCount;
                return post;
            });
        }
        return post;
    });
}
postSchema.plugin(addCommentsCount);
var post = mongoose.model("Post", postSchema);

**Comment by nswbmw** [comment]
参考 models/posts.js
