### ISSUE TITLE
部署时使用CentOS安装nodejs时出错

### ISSUE THREAD

**Issue by shengwanlin** [nswbmw/N-blog#362]
按照教程的命令安装nodejs时

npm i pm2 -g #安装 pm2   

这一步出现错误

如下：

[root@10-9-188-64 ~]# sudo npm i npm -g
npm WARN npm npm does not support Node.js v0.10.48
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'

Thanks!

**Comment by nswbmw** [comment]
`sudo npm i npm -g` ?

**Comment by shengwanlin** [comment]
已经加了 sudo 还是报错.

**Comment by shengwanlin** [comment]
pm2 、 n  也不能安装

**Comment by shengwanlin** [comment]
解决了, 方法是使用以下命令 

curl -sL https://rpm.nodesource.com/setup_6.x | bash -

然后再执行安装 nodejs , 这样就会安装 6.x 版本的 nodejs. 
其他版本请参考  https://github.com/nodesource/distributions
