### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by AliceYuling** [nswbmw/N-blog#368]
博主你好， 谢谢分享， 有个问题想请教下， 按照您的代码， 每次跳转到下个页面时，都会报如下错误：
Error: Can't set headers after they are sent
请问这是什么原因引起的报错呢？在网上看了很多解释但是也没解决

**Comment by Htgs** [comment]
res.send()和res.render()不要同时用

**Comment by jczzq** [comment]
怎么说？
