### ISSUE TITLE
部署到heroku最后一步出现问题

### ISSUE THREAD

**Issue by usherwong** [nswbmw/N-blog#37]
部署到heroku之前的最后一步，在ssh目录创建文件config，
Host heroku.com
User yourName
Hostname 107.21.95.3
PreferredAuthentications publickey
IdentityFile ~/.ssh/id_rsa
port 22

第四行  publickey需要自己到heroku去申请吗，去申请key的时候，提示的创建key目录没有key文件。

git push heroku master
出现问题是： permission denied（publickey）
could not read from remote repository

**Comment by nateliu** [comment]
heroku现在不允许163邮箱注册了，访问也慢的要死，有没有国内类似服务的啊？heroku伤不起。

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
