### ISSUE TITLE
res.redirect(`/posts/${post._id}`);

### ISSUE THREAD

**Issue by caistrong** [nswbmw/N-blog#372]
我用webstrom开发的时候这行出现了错误。
提示是javascript新版本不支持这个语法。

把它改成了
res.redirect('/posts/'+post_id);
解决了这个问题。

我是javascript小白。对这个问题不明所以。
po主的教程很棒，这个问题希望能帮助po主把教程变得更为完美。

**Comment by muwenzi** [comment]
@caistrong 按道理这个代码是没问题的，你先确定这是wb的提示错误，还是程序真正错误，影不影响程序的正常工作。检查一下wb的配置的问题，webstrom -> language ->javascript -> 选择es6试试

**Comment by nswbmw** [comment]
@caistrong 你 node 版本多少，教程开头明确表明node@6了啊。。\`\`在node@4就可以用了
