### ISSUE TITLE
部署到heroku之后，登录和注册页面都对，但是posts页面返回Internal Server Error，这咋办

### ISSUE THREAD

**Issue by freebreaker** [nswbmw/N-blog#374]
![image](https://cloud.githubusercontent.com/assets/23466885/26711711/f22d7e10-4794-11e7-82e1-1cac3fb00db3.png)

**Comment by freebreaker** [comment]
[链接地址](https://dadablog.herokuapp.com/signin)

**Comment by nswbmw** [comment]
看 heroku log

**Comment by freebreaker** [comment]
![image](https://cloud.githubusercontent.com/assets/23466885/26712907/2a7c0848-479c-11e7-8d78-b9a159c55f0c.png)
这是要更新吗

**Comment by freebreaker** [comment]
大神求助求助！！ 一天也没找出原因来

**Comment by nswbmw** [comment]
heroku log 不全。。关键报错信息没出来。你看有没有参数显示更多行的，或者类似于 tail -f 的

**Comment by freebreaker** [comment]
显示mongolass error 可是我完全按照教程来的啊...

**Comment by freebreaker** [comment]
![image](https://cloud.githubusercontent.com/assets/23466885/26771817/263ac47c-49f4-11e7-8e18-bd5479abf392.png)

**Comment by nswbmw** [comment]
看报错是 ensureIndex 有问题，在 /app/lib/mongo.js:24 行
