### ISSUE TITLE
登录的时候发现一个错误

### ISSUE THREAD

**Issue by pengloo53** [nswbmw/N-blog#381]
```js
checkNotLogin: function checkNotLogin(req, res, next) {
    if (req.session.user) {
      req.flash('error', '已登录');
      return res.redirect('back');   //返回之前的页面
    }
    next();
  }
```

在登录页面使用了这个中间件，如下代码：

```js
// GET /signin 登录页
router.get('/', checkNotLogin, function(req, res, next) {
  res.render('signin');
});
```

当点击登录的时候，登录成功会跳转到主页，此时session已经存在，如果这个时候我再访问`/login`，返回登录页之前，会先执行`checkNotLogin`中间件，于是会返回`res.redirect('back')`，重定向到上一页，最后又渲染登录，这样会出现返回多个页面。浏览器报错：

![default](https://user-images.githubusercontent.com/5508125/27002846-feae8442-4e1d-11e7-9ab2-9d7ba2c41b2c.png)

**Comment by nswbmw** [comment]
checkNotLogin 调用了  `return res.redirect('back');`，而不是 `next()`，所以不会执行到 `res.render('signin');`，safari 报错是多次重定向，你还得查下应该是其他原因。

**Comment by pengloo53** [comment]
嗯，我再找找其他原因，谢了

**Comment by pengloo53** [comment]
还是不明白具体原因，但是找到了问题具体所在，还是登陆这块，当session已经存在的时候，再执行`POST /login`登陆操作（当然session已经存在，不可能再进入login页面，但是可以提前打开两个登陆页面复现这种操作，点击登陆，另外一个页面再点击登陆就会报错），后台日志显示：

```
POST /login 302 1.831 ms - 98
GET /login 302 1.262 ms - 98
GET /login 302 1.529 ms - 98
GET /login 302 0.896 ms - 98
GET /login 302 3.034 ms - 98
GET /login 302 1.545 ms - 98
GET /login 302 1.234 ms - 98
GET /login 302 0.769 ms - 98
GET /login 302 1.163 ms - 98
GET /login 302 2.225 ms - 98
GET /login 302 2.018 ms - 98
GET /login 302 0.962 ms - 98
GET /login 302 1.009 ms - 98
GET /login 302 1.371 ms - 98
GET /login 302 2.131 ms - 98
GET /login 302 1.136 ms - 98
GET /login 302 3.123 ms - 98
GET /login 302 1.042 ms - 98
GET /login 302 0.677 ms - 98
GET /login 302 1.445 ms - 98
GET /login 302 1.855 ms - 98
```

浏览器还是多次重定向错误，不知道啥原因，求助~

**Comment by nswbmw** [comment]
这种情况的确会这样。。把checkNotLogin改成：

```
return res.redirect('/posts');
```

避免这个问题。正常一个网页情况下不会出现这种情况

**Comment by pengloo53** [comment]
还是不明白为什么会出现这个问题？跟浏览器返回有关系？
