### ISSUE TITLE
axios异步请求后，页面偶尔报错Can't set headers after they are sent。

### ISSUE THREAD

**Issue by se7en-1992** [nswbmw/N-blog#383]
简单的先描述下业务，新闻列表页面，因为公司要做seo的。我们是java后台，用node做中间层，所以我在node层用axios渲染到模版（ejs）上。但是这个页面多刷新几次就会出现404，报错信息如下：

![default](https://user-images.githubusercontent.com/19768530/27268074-b7bfe3dc-54df-11e7-93bb-602967b8c67e.png)

其他页面怎么都不会报错。就axios异步请求的页面会报错。我试过好多方法区改变还是解决不了，比如axios自带的.then  再比如promise.then  还有async。

![axios then](https://user-images.githubusercontent.com/19768530/27268084-ced1ccde-54df-11e7-96cf-2ef6d2bdd557.png)

![promise then](https://user-images.githubusercontent.com/19768530/27268247-01ad76ca-54e1-11e7-8a23-0b0a96a19144.png)

![async](https://user-images.githubusercontent.com/19768530/27268358-a90876fe-54e1-11e7-80f7-cea3c501c176.png)

图中的api是对axios的一个封装 下面是代码：
![api1](https://user-images.githubusercontent.com/19768530/27268369-bc006df2-54e1-11e7-9ca9-1f7fe20c1ae6.png)
![api2](https://user-images.githubusercontent.com/19768530/27268370-bc132118-54e1-11e7-82a3-1797aebe9ec4.png)
![api3](https://user-images.githubusercontent.com/19768530/27268371-bc13c244-54e1-11e7-89dd-e1e5f1afb68b.png)

最后附上入口文件。求大佬帮解决下 ，真的很急。
![appjs1](https://user-images.githubusercontent.com/19768530/27268449-1b3a1d0e-54e2-11e7-9746-28cad3c9355a.png)
![appjs2](https://user-images.githubusercontent.com/19768530/27268450-1b635750-54e2-11e7-8b5a-188250c4b82d.png)

**Comment by nswbmw** [comment]
routeCenter 啥内容？

**Comment by se7en-1992** [comment]
![in1](https://user-images.githubusercontent.com/19768530/27269358-bc9d0d90-54e8-11e7-87a0-41500e764a10.png)
这是route下面的index.js

**Comment by se7en-1992** [comment]
@nswbmw

**Comment by se7en-1992** [comment]
大佬，有空吗？可以看看哪里出错了吗

**Comment by se7en-1992** [comment]
已解决
