### ISSUE TITLE
文件拖拽上传

### ISSUE THREAD

**Issue by liuxinqiong** [nswbmw/N-blog#384]
您好：
我最近想做一个文件拖拽上传的功能，最常见的使用场景就是发表博客的时候可能需要插入图片，直接拖到文本域实现ajax上传，且自动生成markdown语法格式，比如一开始是uploading-->\!\[](xxxx.jpg)，使用`connect-multiparty`配合`fs`已经实现这个功能，但是您是使用的`express-formidable`这个中间件实现的，但是这个中间件只要是file类型的就给我上传了，我想知道有没有什么办法知道他上传的状态值，比如上传中，上传完成，甚至上传进度呢？
搜索引擎查到`express-formidable`资源有限，博主可否提供点资源或者点明一下实现思路呢？谢谢

**Comment by nswbmw** [comment]
没做过拖拽上传，你可以看下可能有相关的 JQuery 插件，或者参考 cnode。
