### ISSUE TITLE
supervisor --harmony index  报错    node --harmony index   也报错

### ISSUE THREAD

**Issue by pengrongjie** [nswbmw/N-blog#385]
按你的文档一步一步来的
![image](https://user-images.githubusercontent.com/25662399/27845506-95870f18-6162-11e7-8665-8d5e07bb76f9.png)

![image](https://user-images.githubusercontent.com/25662399/27845511-9ce2f024-6162-11e7-802a-d8baf95b37ff.png)

**Comment by nswbmw** [comment]
mongodb 没启动吧，报错很明显啊..

**Comment by calabash519** [comment]
我跟上面一样，但是mongodb启动过了，问题不知道出在哪里

**Comment by KeeganRen** [comment]
@nswbmw 启动了，但还是报错

**Comment by nswbmw** [comment]
@KeeganRen 试下用 mongo 命令可以进入 mongo shell 吗
