### ISSUE TITLE
启动时 config.session.key 一直报错

### ISSUE THREAD

**Issue by LiamShao** [nswbmw/N-blog#388]
TypeError: cannot read property 'key' of undefined
使用方式改为 var config = require('config-lite')(__dirname);之后还是出错

**Comment by nswbmw** [comment]
在 app.js 打印 `console.log(config)` 看看

**Comment by zxhycxq** [comment]
@LiamShao  请问你是如何解决的，我的是  `  "config-lite": "2.1.0",`按照之前issues里面的更改还是会报错
