### ISSUE TITLE
mongodb问题

### ISSUE THREAD

**Issue by Siriuser** [nswbmw/N-blog#39]
你好，我的Mongodb部署在其他服务器上 运行代码出现Error connecting to database 错误，settings.js我已经改了，工程能够正常启动，查看Mongodb，名称叫blog的db也已经自动创建了，就是在访问首页的时候报这个错误。能帮帮我么

**Comment by shawushe** [comment]
Error: Error connecting to database: failed to connect to [127.0.0.1:27017]  我访问首页遇到这个报错，求指教

**Comment by nswbmw** [comment]
1.  检查mongodb是否启动，以及是否有权限认证
2. 可能是 connect-mongo 版本的问题，升到最新，改下配置
