### ISSUE TITLE
关于重复响应问题

### ISSUE THREAD

**Issue by ZJH9Rondo** [nswbmw/N-blog#391]
# 老问题，issue里面有，但是没有明确的解决办法，去过stackoverflow，找到些解决办法，但是没能完全解决
*  问题描述 Error: Can't set headers after they are sent.
 > 每次页面跳转，会出现此类错误，但是代码看了即便都没发现有重复响应的操作，下附路由代码链接 ，望前辈帮忙看看

* Ps: 现在的重复响应问题直接导致AJax被重复响应返回非正常结果

```
   https://github.com/ZJH9Rondo/Blog-Node/blob/master/routes/posts.js
```

**Comment by ZJH9Rondo** [comment]
已解决，并提交了 request

**Comment by nswbmw** [comment]
感觉像是 express-formidable 的 bug... https://github.com/noraesae/express-formidable/pull/10

**Comment by ZJH9Rondo** [comment]
两天才定位到错误，就是那个包的bug，好改吗？

**Comment by nswbmw** [comment]
有人提 pr 了，作者并不活跃，没有 merge..
