### ISSUE TITLE
部署error 日志问题

### ISSUE THREAD

**Issue by haocaokai** [nswbmw/N-blog#399]
不太明白，麻烦帮忙看下，谢谢了，代码已经push到库里了
![image](https://user-images.githubusercontent.com/16473565/28866357-4e797170-77a5-11e7-87fa-d9a93888cabb.png)

**Comment by nswbmw** [comment]
截图信息不全，上面的报错信息呢

**Comment by haocaokai** [comment]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x...
       Downloading and installing node 6.11.2...
       Using default npm version: 3.10.10
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules (exists - skipping)
       - bower_components (not cached - skipping)
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       config-lite@2.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/config-lite
       chalk@1.1.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/chalk
       ansi-styles@2.2.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ansi-styles
       escape-string-regexp@1.0.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/escape-string-regexp
       has-ansi@2.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/has-ansi
       ansi-regex@2.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ansi-regex
       strip-ansi@3.0.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/strip-ansi
       supports-color@2.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/supports-color
       js-yaml@3.9.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/js-yaml
       argparse@1.0.9 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/argparse
       sprintf-js@1.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/sprintf-js
       esprima@4.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/esprima
       lodash@4.17.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/lodash
       optimist@0.6.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/optimist
       minimist@0.0.10 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/minimist
       wordwrap@0.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/wordwrap
       resolve@1.3.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/resolve
       path-parse@1.0.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/path-parse
       connect-flash@0.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/connect-flash
       connect-mongo@1.3.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/connect-mongo
       bluebird@3.5.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/bluebird
       mongodb@2.2.30 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongodb
       es6-promise@3.2.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/es6-promise
       mongodb-core@2.1.14 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongodb-core
       bson@1.0.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/bson
       require_optional@1.0.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/require_optional
       resolve-from@2.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/resolve-from
       semver@5.4.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/semver
       readable-stream@2.2.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/readable-stream
       buffer-shims@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/buffer-shims
       core-util-is@1.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/core-util-is
       inherits@2.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/inherits
       isarray@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/isarray
       process-nextick-args@1.0.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/process-nextick-args
       string_decoder@1.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/string_decoder
       safe-buffer@5.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/safe-buffer
       util-deprecate@1.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/util-deprecate
       ejs@2.5.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ejs
       express@4.14.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express
       accepts@1.3.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/accepts
       mime-types@2.1.16 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mime-types
       mime-db@1.29.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mime-db
       negotiator@0.6.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/negotiator
       array-flatten@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/array-flatten
       content-disposition@0.5.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/content-disposition
       content-type@1.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/content-type
       cookie@0.3.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/cookie
       cookie-signature@1.0.6 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/cookie-signature
       debug@2.2.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/debug
       ms@0.7.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ms
       depd@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/depd
       encodeurl@1.0.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/encodeurl
       escape-html@1.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/escape-html
       etag@1.7.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/etag
       finalhandler@0.5.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/finalhandler
       on-finished@2.3.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/on-finished
       ee-first@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ee-first
       statuses@1.3.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/statuses
       unpipe@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/unpipe
       fresh@0.3.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/fresh
       merge-descriptors@1.0.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/merge-descriptors
       methods@1.1.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/methods
       parseurl@1.3.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/parseurl
       path-to-regexp@0.1.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/path-to-regexp
       proxy-addr@1.1.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/proxy-addr
       forwarded@0.1.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/forwarded
       ipaddr.js@1.4.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/ipaddr.js
       qs@6.2.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/qs
       range-parser@1.2.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/range-parser
       send@0.14.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/send
       destroy@1.0.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/destroy
       http-errors@1.5.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/http-errors
       setprototypeof@1.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/setprototypeof
       mime@1.3.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mime
       serve-static@1.11.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/serve-static
       send@0.14.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/serve-static/node_modules/send
       ms@0.7.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/serve-static/node_modules/ms
       type-is@1.6.15 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/type-is
       media-typer@0.3.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/media-typer
       utils-merge@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/utils-merge
       vary@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/vary
       express-formidable@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-formidable
       formidable@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/formidable
       express-session@1.15.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-session
       crc@3.4.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/crc
       debug@2.6.8 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-session/node_modules/debug
       ms@2.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-session/node_modules/ms
       on-headers@1.0.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/on-headers
       uid-safe@2.1.4 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/uid-safe
       random-bytes@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/random-bytes
       express-winston@2.4.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-winston
       chalk@0.4.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-winston/node_modules/chalk
       ansi-styles@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-winston/node_modules/ansi-styles
       has-color@0.1.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/has-color
       strip-ansi@0.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-winston/node_modules/strip-ansi
       lodash@4.11.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/express-winston/node_modules/lodash
       marked@0.3.6 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/marked
       moment@2.18.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/moment
       mongolass@2.4.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass
       another-json-schema@2.1.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/another-json-schema
       is-buffer@1.1.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/is-buffer
       co@4.6.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/co
       debug@2.6.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/debug
       ms@0.7.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/ms
       inflected@1.1.7 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/inflected
       mongodb@2.2.25 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/mongodb
       mongodb-core@2.1.9 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/mongodb-core
       readable-stream@2.1.5 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/readable-stream
       string_decoder@0.10.31 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass/node_modules/string_decoder
       mongolass-plugin-populate@0.2.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass-plugin-populate
       lodash@4.15.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/mongolass-plugin-populate/node_modules/lodash
       validator@7.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/validator
       objectid-to-timestamp@1.3.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/objectid-to-timestamp
       sha1@1.1.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/sha1
       charenc@0.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/charenc
       crypt@0.0.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/crypt
       winston@2.3.1 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/winston
       async@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/async
       colors@1.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/colors
       cycle@1.0.3 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/cycle
       eyes@0.1.8 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/eyes
       isstream@0.1.2 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/isstream
       stack-trace@0.0.10 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0/node_modules/stack-trace
       Installing any new modules (package.json)
       - ms@2.0.0 node_modules/express-session/node_modules/ms
       - debug@2.6.8 node_modules/express-session/node_modules/debug
       myblog@1.0.0 /tmp/build_d76884189a7e42aecef09f7c3c359253/haocaokai-myblog-a6c76a0
       ├── ejs@2.5.2
       ├─┬ express-session@1.14.2
       │ └── crc@3.4.1
       ├── express-winston@2.0.0
       ├── moment@2.15.2
       ├─┬ mongolass@2.4.1
       │ ├── bluebird@3.4.6
       │ ├── debug@2.3.3
       │ ├── lodash@4.17.2
       │ ├─┬ mongodb@2.2.14
       │ │ └── mongodb-core@2.1.1
       │ └── validator@6.2.0
       └─┬ winston@2.2.0
       └── pkginfo@0.3.1
       
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 22.8M
-----> Launching...
       Released v5
       https://ck-blog.herokuapp.com/ deployed to Heroku


以上是所有日志，不过我不是通过命令行部署的，我是直接push到github上，然后用heroku连接git库部署的
