### ISSUE TITLE
关于注册登录

### ISSUE THREAD

**Issue by elva2596** [nswbmw/N-blog#400]
您好，关于注册登录的问题：
这个项目是多人博客，也就是可以多人注册登录使用，那么问题来了：我现在10个人注册了账号，我现在10个人想同时登录，但是session保存到数据库中，并且sessions集合中始终只有一个文档，并且req.session.user = user也限制了每次只能有一个人登录。博主是故意设计成这样的吗？本人接触注册登录原理不是很深，若想实现基于cookie-session的多人登录如何实现？？？？

**Comment by nswbmw** [comment]
你试过吗，试过后再考虑下。给你点提示：注册多个账号后，去 mongodb 看看 sessions 这个集合有几条数据

**Comment by elva2596** [comment]
我试了一下。没有办法在同一台电脑注册多个账号。每次如果想注册新的账号就得登出，因此session集合里总是一个文档。是我哪里出了问题吗？？？

**Comment by elva2596** [comment]
我刚刚开了两个浏览器，一个chrome一个ff，session集合中有了两个文档。博主你看是不是这个意思：一个客户端(即浏览器)使用一个cookie.由于两个浏览器存储cookie的文件夹不一样，相当于我再两个电脑上注册。这样就实现了多用户同时登录。那么也就是说在同一个电脑的同一个浏览器上，基于session是无法同时登录的。因为后一个登录的会覆盖前一个登录的session信息。

**Comment by nswbmw** [comment]
@elva2596 是的
