### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by gostfather** [nswbmw/N-blog#402]
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-08-29T11_46_23_027Z-debug.log

不是很理解什么意思

**Comment by nswbmw** [comment]
你给的信息量太少啦

**Comment by gostfather** [comment]
我是按着你的步骤来，在测试的步骤，装好模块，修改json里面的内容，npm test后报了上面那两个错。我放在github上了有空去看看呗 大佬

**Comment by nswbmw** [comment]
👌

**Comment by gostfather** [comment]
然后呢我下了你的项目试了一试
![9 y3x 5bvpq 0ni1 q6q4e7](https://user-images.githubusercontent.com/29191934/29820354-c74f5b58-8cf6-11e7-82fc-54c1cc683d9f.png)
![xk uef 0 lmnlar i 5](https://user-images.githubusercontent.com/29191934/29820361-ce9d6332-8cf6-11e7-87dc-7e36b8105ffb.png)
很奇怪也不能用是我项目没启动么》

**Comment by nswbmw** [comment]
package.json 里的 name 不要用中文

**Comment by gostfather** [comment]
我去不能用中文还不能用空格！
但是改过来后
报了一个少模块的错误。。
![k208odlitw2u5j bv i](https://user-images.githubusercontent.com/29191934/29820687-e5a97542-8cf7-11e7-8153-f4fae42c4f21.png)

**Comment by nswbmw** [comment]
`npm i` 之

**Comment by gostfather** [comment]
我把package.json 替换成你的就可以了。可能漏了什么东西。。谢谢大佬
