### ISSUE TITLE
无法找到这个模块  mongolass-plugin-populate 谢谢啊！！！

### ISSUE THREAD

**Issue by Tell-Dong** [nswbmw/N-blog#403]
具体的问题描述：报错的截图：

![u3eih7c9y 05 5hm m90o](https://user-images.githubusercontent.com/30956858/30802728-0a7f3352-a21a-11e7-916d-ed09b5c4a5d8.png)

找不到模块 但是对应的地方有啊!!!!!!!!!!!!!!
查了好多  不知道啥原因了 
博主 能不能帮忙看看！！！
谢谢啦！！！

排查了一下 这个地方有错误，不知道哪里错了 ，刚学，很菜！！！

这里不需要引入 那个模块啊！！1
/*
 * mongolass 操作 mongodb 进行增删改查
 *
 * 连接数据库
 */

var config = require('config-lite')(__dirname);
var Mongolass = require('mongolass');
var mongolass = new Mongolass();
mongolass.connect(config.mongodb);

// 存储用户的名称、密码（加密后的）、头像、性别和个人简介
// Mongolass 中的 model 相当于 mongodb 中的 collection
// Mongolass 的 schema 的用法

exports.User = mongolass.model('User', {
  name: { type: 'string' },
  password: { type: 'string' },
  avatar: { type: 'string' },
  gender: { type: 'string', enum: ['m', 'f', 'x'] },
  bio: { type: 'string' }
});
// 根据用户名找到用户，用户名全局唯一
// 生成并导出了 User 这个 model，同时设置了 name 的唯一索引，保证用户名是不重复的。
exports.User.index({ name: 1 }, { unique: true }).exec();

**Comment by nswbmw** [comment]
可能装包的时候没装完中断过吧。删掉 node_modules，重新 npm i 应该就好了

**Comment by Tell-Dong** [comment]
解决了   全部走了一遍  谢谢啊博主！ 从博主这学到了不少东西 还接触到了mongodb 恶补了一番  有些地方还是有不懂的，但是只能慢慢理解 多看看， 博主轮子造的真心的好  ，  啥时候能像博主一样。。。。
 预祝自己面试顺利通过， 有点啰嗦了！  嘿嘿

**Comment by nswbmw** [comment]
@Tell-Dong 加油喔~
