### ISSUE TITLE
关于改造升级

### ISSUE THREAD

**Issue by huang303513** [nswbmw/N-blog#409]
我把你这个代码改造升级一下，放在github了。具体详情https://cnodejs.org/topic/5a041edd275684445195a999

**Comment by nswbmw** [comment]
👍

今天刚重新梳理了一遍教程：

1. 使用了部分 es6 特性
2. 使用 ESLint（standard）

我的想法是不能一口吃成个胖子，如果初学者用会了 Promise 再去用 async/await 是很容易的。而上来就用 async/await 他可能连 Promise 基础都掌握不好

**Comment by huang303513** [comment]
反正就是谢谢大佬，我觉得你这个教程很好。广度、深度、各方面都维持在一个菜鸟既能实现也能个发面都涉及到。一个非常好的入门教程。
