### ISSUE TITLE
config-lite找不到配置，set NODE_ENV=prod后报错。

### ISSUE THREAD

**Issue by jc784999074** [nswbmw/N-blog#412]
您好，遇到一个奇怪的问题。
![image](https://user-images.githubusercontent.com/20136135/32775595-d914762e-c96a-11e7-86a4-05ec12d16f85.png)
![image](https://user-images.githubusercontent.com/20136135/32775623-ebe37cf0-c96a-11e7-833e-601472f489d8.png)

**Comment by jc784999074** [comment]
直接node  index.js启动没问题，但是加了set NODE_ENV=prod会报错。
prod.js是default.js拷贝出来的

**Comment by nswbmw** [comment]
你有没有看到 "prod "...多了个空格。我猜应该改成：

```sh
set NODE_ENV="prod" && node index.js
```

**Comment by jc784999074** [comment]
.....以为要加空格分割命令。
多谢解答
