### ISSUE TITLE
处理404页面时出现错误Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by CarolSum** [nswbmw/N-blog#416]
为何会有这种错误？求大大们解惑下~

**Comment by CarolSum** [comment]
已解决：res.headersSent 改为 res._headerSent

**Comment by 12454j** [comment]
Not solved streaming is not the answer

**Comment by 12454j** [comment]
404 errors  don't help either

**Comment by mlinge** [comment]
本人也遇到了，但不只是404的时候，所有页面请求都存在这个问题
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)

**Comment by mlinge** [comment]
我也遇到了，但不只是404的时候，所有页面请求都存在这个问题
Error: Can't set headers after they are sent.
at validateHeader (_http_outgoing.js:494:11)
at ServerResponse.setHeader (_http_outgoing.js:501:3)

**Comment by mlinge** [comment]
我也遇到了，但不只是404的时候，而是所有页面请求都存在这个问题
Error: Can't set headers after they are sent.
at validateHeader (_http_outgoing.js:494:11)
at ServerResponse.setHeader (_http_outgoing.js:501:3)

**Comment by CarolSum** [comment]
@mlinge 页面跳转逻辑你是怎么写的

**Comment by mlinge** [comment]
我是在Webstorm下创建一个Express的node工程，然后按照博客文章的内容进行编码（只有小部分代码不一样）。

**Comment by mlinge** [comment]
@CarolSum 我是在Webstorm下创建一个Express的node工程，然后按照博客文章的内容进行编码（只有app和www文件中的部分代码不一样）

**Comment by mlinge** [comment]
@CarolSum 好奇怪，莫名其妙的刚才那个问题没有了，缺出现了下面这个情况，POST请求提交不了，居然内存泄漏，没有反应。
(node:13980) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 field listeners added. Use emitter.setMaxListeners() to increase limit
(node:13980) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 file listeners added. Use emitter.setMaxListeners() to increase limit
(node:13980) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:13980) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by notmaster** [comment]
@mlinge 是express-formidable的bug，不用上传，多刷新几次页面就会报错，你把处理上传的代码注销了，就不会报错了（以下就是这段代码）
// 处理表单及文件上传的中间件
app.use(require('express-formidable')({
  uploadDir: path.join(__dirname, 'public/img'), // 上传文件目录
  keepExtensions: true// 保留后缀
}))

express-formidable的作者不活跃，没有修复，如何解决这个bug，参考：https://github.com/utatti/express-formidable/pull/10

**Comment by notmaster** [comment]
@mlinge 将express-formidable替换为multer
https://github.com/nswbmw/N-blog/issues/290
