### ISSUE TITLE
4.14 pm2指令相关

### ISSUE THREAD

**Issue by linhongyu97** [nswbmw/N-blog#419]
作者在正文中写的pm2，package.json里修改方法如下：
"scripts": {
  "test": "nyc --reporter=html --reporter=text mocha",
  "start": "NODE_ENV=production pm2 start index.js --name 'myblog'"
}
我用自己的win10系统尝试了下，会出现“NODE_ENV 不是内部或外部命令，也不是可运行的程序，或者批处理文件”错误，经过查询了解到问题在于：合并两条命令的脚本没法不被cmd支持（这种操作在powershell中不被支持，在cmd中也不被支持，这是Mac中bash或Linux的shell中的独特操作）

因此，如果是在cmd下进行需要改成：
"scripts": {
  "test": "nyc --reporter=html --reporter=text mocha",
  "start": "set NODE_ENV=production && pm2 start index.js --name 'myblog'"
}

**Comment by nearxu** [comment]
楼主，按照你的改了，npm start 为什么我的cmd一直弹窗，

**Comment by mafeifan** [comment]
造成的原因是操作系统设置环境变量的关键字不一样。推荐使用 cross-env。

**Comment by nswbmw** [comment]
7ee88f65dbf03d17d
