### ISSUE TITLE
npm start，输入localhost:3000不能打开页面

### ISSUE THREAD

**Issue by suoz** [nswbmw/N-blog#421]
1. 将代码拉取下来
2. npm install
3. npm start
4. url中输入localhost:3000
但是页面打不开??

**Comment by nswbmw** [comment]
1. 看看控制台有啥报错吗
2. 试试 127.0.0.1:3000

**Comment by nearxu** [comment]
![image](https://user-images.githubusercontent.com/18578033/33837472-5fe6000c-dec7-11e7-98f2-dc8346e253bd.png)

**Comment by nearxu** [comment]
麻烦楼主看看出现什么问题了？

**Comment by nswbmw** [comment]
先用 `node index.js` 启动，回头我修改下教程，windows 用户需要改一下:

```sh
npm install --save-dev cross-env
cross-env NODE_ENV=production pm2 start index.js --name "myblog"
```

**Comment by Benjaminbai** [comment]
我也遇到相同到问题
![image](https://user-images.githubusercontent.com/23426556/98672586-fe153e80-2390-11eb-85eb-394547bbf351.png)
打不开localhost：3000，也没报错
