### ISSUE TITLE
mongolass 好像要在能运行ES7李

### ISSUE THREAD

**Issue by dumuchenglin123** [nswbmw/N-blog#435]
提问方式：

1. 请先从错误栈自己定位问题，尝试亲自解决问题
2. 解决不了再去历史 isuue 里查看是否有相似的问题
3. 最后，提交新的 issue，并将错误代码提交到你的 GitHub，我抽空会帮你调试

不好的提问方式：

1. 只有标题，没有描述
2. 描述不清楚

**Comment by dumuchenglin123** [comment]
因为我node环境是node 6 的，我想更新版本，我尝试了n 包管理器，来升级，但始终报这错误：
Error: invalid version 9.4.0 ，不知道如何解决，网上查了半天也没什么有效的方法，请问大神用什么更新的？

**Comment by nswbmw** [comment]
你可以直接从官网下载安装包覆盖安装。建议下载 v8.9.4

**Comment by hadesvip** [comment]
sudo npm install -g n

在 2018-02-01 09:56:52，"nswbmw" <notifications@github.com> 写道：


你可以直接从官网下载安装包覆盖安装。建议下载 v8.9.4

**Comment by dumuchenglin123** [comment]
好了，我下了nvm 改了环境变量，node版本切换过来了，谢谢各位

**Comment by gitzzh111** [comment]
强烈建议使用nvm版本控制器管理node，你可以装多个版本的node，使用 如nvm use v6.9.6 命令切换node版本。
