### ISSUE TITLE
4.14.2 测试覆盖率 小节 window下配置问题

### ISSUE THREAD

**Issue by ghostcode** [nswbmw/N-blog#436]
测试覆盖率那一小节有个小问题：https://github.com/nswbmw/N-blog/blob/master/book/4.14%20%E6%B5%8B%E8%AF%95.md#4142-%E6%B5%8B%E8%AF%95%E8%A6%86%E7%9B%96%E7%8E%87 ，

 在 windows 平台下：

 ```"test": "istanbul cover _mocha"```

 得改成 :

```"test": "istanbul cover node_modules/mocha/bin/_mocha"```

这里有个相关的issue：https://github.com/gotwarlost/istanbul/issues/90。

**Comment by nswbmw** [comment]
https://github.com/nswbmw/N-blog/commit/39269a73a6cae07075b31a0dc6d0925c12dde48c
