### ISSUE TITLE
throw new Error<Connection strategy not found>

### ISSUE THREAD

**Issue by cdpv587** [nswbmw/N-blog#437]
我查了一下说是new MongoStore({
         url:config.mongodb  
})

就是这个url有问题   初学不太会解决

**Comment by nswbmw** [comment]
1. 看错误栈
2. 搜索引擎
3. 相关模块文档

**Comment by cdpv587** [comment]
在指导下找到问题了，大佬可以给个联系方式吗

**Comment by nswbmw** [comment]
try搜索引擎😆
