### ISSUE TITLE
npm start fail on Windows 7 sytsem

### ISSUE THREAD

**Issue by yongli3** [nswbmw/N-blog#438]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myblog@1.0.0 start: `NODE_ENV=production pm2 start index.js --name 'myblog'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myblog@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

10 silly lifecycle myblog@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'NODE_ENV=production pm2 start index.js --name \'myblog\'' ]
11 silly lifecycle myblog@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle myblog@1.0.0~start: Failed to exec start script
13 verbose stack Error: myblog@1.0.0 start: `NODE_ENV=production pm2 start index.js --name 'myblog'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid myblog@1.0.0
15 verbose cwd C:\proj\N-blog
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error myblog@1.0.0 start: `NODE_ENV=production pm2 start index.js --name 'myblog'`
22 error Exit status 1
23 error Failed at the myblog@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nswbmw** [comment]
用 cross-env

**Comment by nswbmw** [comment]
7ee88f65dbf03d17d
