### ISSUE TITLE
连接mLab数据库后，页面注册后无法跳转问题

### ISSUE THREAD

**Issue by Ziqing9797** [nswbmw/N-blog#439]
博主我连接mLab成功了。但是注册完用户成以后，不能跳转到主页/posts页面下，会显示无法访问此网站。查看mLab数据库中collections里面面，用户的数据是写进去了的。在本地调试不存在这个问题能够跳转。请问是怎么回事不知到从哪里找错。

**Comment by nswbmw** [comment]
既然数据写成功了，就在写成功后打log，看看走到哪一步出问题了
