### ISSUE TITLE
2.2节的关于exports 和 module.exports截图是否有错

### ISSUE THREAD

**Issue by lubyxu** [nswbmw/N-blog#442]
楼主你好，我在看2.2节的时候，关于exports的截图，为什么返回的是module，而不是module.exports的截图一直很迷惑。于是查了一下node的文档。发现文档返回和你的文档截图有出入：https://nodejs.org/api/modules.html#modules_exports_shortcut。

**Comment by lubyxu** [comment]
哦！忘记说了！文档写的很赞！非常适合小白的我学习node，顺便补习关于js的其他的基础知识！！！

**Comment by nswbmw** [comment]
返回 module 不就知道 module.exports 了吗~官方可能也觉得那样写不太清楚，后来又更新了，教程截图也更新了~
