### ISSUE TITLE
使用deleteOne无法删除文章与留言，看过#432提问后还是没有解决掉

### ISSUE THREAD

**Issue by lupanpan** [nswbmw/N-blog#443]
我是个小白，求救一下 o(╥﹏╥)o ~~~

使用 ‘deleteOne’ 无法删除文章与留言，提示删除成功，打断点调试后，发现可以走通没有报错，但是数据没有被删除掉。之前看过这篇提问 https://github.com/nswbmw/N-blog/issues/432 后，修改为remove可以删除留言，但是无法删除文章。

### 开发环境

mongolass版本：3.1.5
MongoDB版本：3.4.9
node版本：4.9.4

项目github地址为：https://github.com/lupanpan/node-myblog

### 出错代码如下

models/posts.js
```
  // 通过文章 id 删除一篇文章
  delPostById: function delPostById (postId, author) {
    return Post.deleteOne({ author: author, _id: postId })
      .exec()
      .then(function (res) {
        // 文章删除后，再删除该文章下的所有留言
        if (res.result.ok && res.result.n > 0) {
          return CommentModel.delCommentById(postId)
        }
      })
  }
}

```

models/comments.js
```

  // 通过留言 id 删除一个留言
  delCommentById: function delCommentById (commentId) {
    return Comment.deleteOne({ _id: commentId }).exec()
  }
```

**Comment by nswbmw** [comment]
升级 Mongolass 版本到最新试试

**Comment by lupanpan** [comment]
你好，感谢百忙之中帮我解决我问题，升级了 Mongolass 到 4.2.0 版本，但是使用 deleteOne，还是无法删除，使用remove可以删除

**Comment by NetPeng** [comment]
comments.js中的delCommentById是根据留言id删除一个留言，删除文章deleteOne中调用删除的留言应该是删除真个留言，根据postid来删除，所以不应该是继续调用上面的delCommentById，而是应该用一个方法delCommentsBypostId

**Comment by lupanpan** [comment]
@NetPeng 感谢你帮我指出了错误，想问一下你的项目使用的deleteOne能删除掉吗 ？你的Mongolass与MongoDB的版本是多少呢？

**Comment by NetPeng** [comment]
Mongolass@4.1.3
MongoDB@3.4.10

**Comment by nswbmw** [comment]
@lupanpan 调好了吗？没有的话你把 GitHub 代码更新到最新我再看下

**Comment by lupanpan** [comment]
@nswbmw 还没有调好，代码上传为最新的了，github地址为：https://github.com/lupanpan/node-myblog，谢谢大神

**Comment by nswbmw** [comment]
不好意思回复晚了。我 MongoDB@3.4 Mongolass@4.2.1 无法复现这个问题。。你升级下 MongoDB 试一下？

**Comment by lupanpan** [comment]
@nswbmw @NetPeng 非常感谢大神们的帮忙，辛苦你们了。
鼓捣了这几天，mongodb升级为3.4.10，在我的电脑上还是不能删除，还是没有找到原因，不知道是不是因为window系统的原因。
不过我把项目发布到了阿里云，系统是 CentOS 6.8 64位，安装的也是mongodb 3.4.10 版本，删除没问题。
