### ISSUE TITLE
异步删除上传的头像 处报错

### ISSUE THREAD

**Issue by FishWaitingCat** [nswbmw/N-blog#454]
请问博主如下报错怎么回事呀，谢谢您

把 fs.unlink(req.files.avatar.path) 删掉即可正常运行
报错内容
`"stack": [
    "TypeError [ERR_INVALID_CALLBACK]: Callback must be a function",
    "    at makeCallback (fs.js:135:11)",
    "    at Object.unlink (fs.js:903:14)",
    "    at /Users/kaihu/Documents/CUGB525/routes/signup.js:68:8",
    "    at Layer.handle [as handle_request] (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)",
    "    at next (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/route.js:137:13)",
    "    at checkNotLogin (/Users/kaihu/Documents/CUGB525/middlewares/check.js:23:5)",
    "    at Layer.handle [as handle_request] (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)",
    "    at next (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/route.js:137:13)",
    "    at Route.dispatch (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/route.js:112:3)",
    "    at Layer.handle [as handle_request] (/Users/kaihu/Documents/CUGB525/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)"
  ]`

**Comment by nswbmw** [comment]
提示非常明确了吧，fs.unlink 需要 callback，或者你用 fs.unlinkSync

**Comment by skyue** [comment]
我用fs.unlink也报错了，缺回调函数，unlinkSync是正常的。不过想请问下，用unlink要怎么改呢？
