### ISSUE TITLE
Model 引入后，打印为 {} 空的情况

### ISSUE THREAD

**Issue by Shawn211** [nswbmw/N-blog#458]
N神，打扰了，小白请教一个问题：
在 models/users 下进行 PostModel 的引入，如下
const PostModel = require('../models/posts')

再 console.log(PostModel) 能输出正确，如下
{ create: [Function: create],
  getPostById: [Function: getPostById],
  getPosts: [Function: getPosts],
  incPv: [Function: incPv],
  getRawPostById: [Function: getRawPostById],
  delPostById: [Function: delPostById] }

然而在 models/comments 下进行 PostModel 的引入，再console.log(PostModel) 会返回 {}
请问这是为什么呢

**Comment by nswbmw** [comment]
循环引用了，参考：https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_cycles

**Comment by Shawn211** [comment]
了解！感谢~
