### ISSUE TITLE
注册页面跳转

### ISSUE THREAD

**Issue by hahazqa** [nswbmw/N-blog#468]
每次注册，注册成功后会跳转不到/posts页面，在/signup上但是显示该地址已经重置，我想问下这是什么原因啊

**Comment by hahazqa** [comment]
找的问题了。。。。

**Comment by P4X666** [comment]
楼主，能分享一下怎么解决的吗？我现在也是这个问题

**Comment by P4X666** [comment]
我去，posts.ejs中我用了HTML的注释了，是我偷懒了，对不起
<%- include('header') %>


这是主页

<%- include('footer') %>

**Comment by P4X666** [comment]
对不起，是我偷懒了，ejs中用了html的注释
`<%- include('header') %>

这是主页
<%- include('footer') %>`
