### ISSUE TITLE
pm2进程开启后无反应

### ISSUE THREAD

**Issue by FishWaitingCat** [nswbmw/N-blog#474]
您好！
我将修改后的项目挂载到了阿里云学生服务器上，但总存在一个问题想请教您：
pm2进程开启或重启后一切正常，所有功能正常使用，但一段时间（几个小时候），再次打开网页就没有反应了，必须得重启pm2，想请问是何种原因造成的呢？
烦请赐教！
感谢！

**Comment by FishWaitingCat** [comment]
已尝试升级pm2等，但都找不到原因

**Comment by cnAlan** [comment]
你是？

**Comment by llh1187** [comment]
你好，大佬可以帮忙看下吗#483
