### ISSUE TITLE
注册时， 提示Callback must be a function 的解决方案

### ISSUE THREAD

**Issue by tx321-4** [nswbmw/N-blog#477]
fs.unlink 语法格式 已经更改，
  fs.unlink(req.files.avatar.path) ===>

fs.unlink(req.files.avatar.path, function (err) {
      if (err) {
        return console.error(err);
      }
      console.log('文件删除成功！');
    });

**Comment by llh1187** [comment]
老哥还是不行哦。

**Comment by tx321-4** [comment]
你看一下 node.js 的版本是不是有问题

**Comment by llh1187** [comment]
https://github.com/nswbmw/N-blog/issues/454
按照里面用户nswbmw给出的解决办法也不行。我的版本是v12.13.1

**Comment by llh1187** [comment]
老哥你应该是一开始是密码位数不够或者别的小错误，所以出现了这个问题，然后你就增加了一个回调函数，但是增加之后，你注册的时候符合规定，所以没有经过fs.unlink这个函数处理，你可以登出，重新注册一下试试。

**Comment by tx321-4** [comment]
好的 ，那我删掉这个评论，避免误导人
