### ISSUE TITLE
async的修改问题

### ISSUE THREAD

**Issue by zeffon** [nswbmw/N-blog#58]
教程以修改本地数据库操作作为范例，不过对于远程数据库对于我就有点麻烦，不知要怎么改？纠结mongodb和db的作用域。请大神帮帮忙！
教程例子：（本地数据库）
async.waterfall([
    function (cb) {
      mongodb.open(function (err, db) {
        cb(err, db);
      });
    },
    function (db, cb) {
      db.collection('users', function (err, collection) {
        cb(err, collection);
      });
    },
    function (collection, cb) {
      collection.insert(user, {
        safe: true
      }, function (err, user) {
        cb(err, user);
      });
    }
  ], function (err, user) {
    mongodb.close();
    callback(err, user[0]);
  });

-----------------实际问题：远程数据库------------------
mongodb.connect(settings.url, function (err, db){
        if(err){
            db.close();
            return callback(err);
        }
        db.collection('users', function (err,collection) {
            if(err){
                db.close();
                return callback(err);
            }
            collection.findOne({
                name:name
            }, function (err,user) {
                db.close();
                if(err){
                    return callback(err);
                }
                callback(null,user);
            })
        })
    })

**Comment by nswbmw** [comment]
本地数据库和远程数据库没区别啊。。
