### ISSUE TITLE
删除doc的_id

### ISSUE THREAD

**Issue by zeffon** [nswbmw/N-blog#60]
在 mongoose下，执行delete doc._id，结果是doc的_id原封不动依旧在。求何解？

exports.reprint = function (req, res) {

    var fromId = req.params.id;
    var toName = req.session.user.name;

    Post.findById(fromId, function (err, doc) {
        if(err){
            req.flash('error', err);
        }
        delete doc._id;
。。。。。。

**Comment by nswbmw** [comment]
这里的 doc 是 mongoose 包装过的对象，如果用 Promise 的调用方式，加上 `.lean()`
