### ISSUE TITLE
部署到heroku后访问不了

### ISSUE THREAD

**Issue by cc17** [nswbmw/N-blog#62]
求问，我已经成功部署代码到heroku，显示build成功。但是页面访问时访问不了，http://h2h.herokuapp.com/  求帮忙。谢谢

**Comment by llp0574** [comment]
你好，请问你这个问题是怎么解决的，我也是bulid成功，但是启动不了服务，我的Procfile启动命令是npm start，控制面板里面的web npm start也是勾选了的。

**Comment by nswbmw** [comment]
heroku 国内访问慢。。
