### ISSUE TITLE
大牛，如果如何在JS和EJS中互相访问对方的变量？

### ISSUE THREAD

**Issue by zacard-orc** [nswbmw/N-blog#63]
RT
比方说外部JS或者内部<script>标签内访问 ejs渲染的变量如<%= AAAA%>，或者在EJS中<% %>访问JS的变量，语法是怎么样的？请赐教

**Comment by nswbmw** [comment]
无法做到互相访问，只能做到 ejs 可以访问 js 的。但你可以看下 co-ejs
