### ISSUE TITLE
做到用settings的时候死活起不来

### ISSUE THREAD

**Issue by z121388038** [nswbmw/N-blog#64]
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var session = require('express-session');
var MongoStore = require('connect-mongo')(session);
var settings = require('settings');
var flash = require('connect-flash');

var routes = require('./routes/index');

var app = express();

app.set('port', process.env.PORT || 3000);
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
//app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(flash());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use(session({
    secret: settings.cookieSecret,
    key: settings.db,//cookie name
    cookie: {maxAge: 1000 \* 60 \* 60 \* 24 \* 30},//30 days
    store: new MongoStore({
        db: settings.db,
        host: settings.host,
        port: settings.port
    })
}));

routes(app);

app.listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
});

**Comment by jianHuaRen2008** [comment]
![image](https://cloud.githubusercontent.com/assets/8731084/5741705/c3fcd8ce-9c47-11e4-999e-d0c9fa75ccb8.png)
我的也是在这里 会报这个警告吧 但是程序是能运行起来 不知为何报这个错
