### ISSUE TITLE
每次都要drop database

### ISSUE THREAD

**Issue by funkyLover** [nswbmw/N-blog#74]
为什么第一次`node app`能正常打开
但是每次关闭服务之后再次`node app`就会报如下错误
![2015-04-11 11 50 49](https://cloud.githubusercontent.com/assets/5418228/7100135/4f23d384-e041-11e4-86b8-fd10241d1427.png)
然后每次都要把blog数据库删掉
这时重新打开就不会报错了,这时什么原因你?

**Comment by CommanderXL** [comment]
应该是mongodb版本问题。你在Package里面安装mongodb的最近的版本再试试。

**Comment by funkyLover** [comment]
@CommanderXL 谢谢
