### ISSUE TITLE
在第六章添加留言功能的时候comments存不到数据库

### ISSUE THREAD

**Issue by CommanderXL** [nswbmw/N-blog#77]
再第五章的时候，添加删除功能和编辑功能都没什么问题。

在Post.getOne函数里面：
<pre><code>
if(doc){
    doc.post=markdown.toHTML(doc.post);
    doc.comments.forEach(function(comment){     //这个地方会报错说forEach是未定义的方法
            comment.content=markdown.toHTML(comment.content);
})
}

如果我在doc.post=markdown.toHTML(doc.post);前面加上console.log(doc);

里面未出现comments的内容
</code>
</pre>

这就说明：评论内容comments好像存不进数据库。

到底是哪个地方出了问题~~~。

**Comment by CommanderXL** [comment]
@nswbmw   求解答。

**Comment by nswbmw** [comment]
清空数据库，重启程序再试试

**Comment by CommanderXL** [comment]
@nswbmw  好吧。还真的是这个问题。
