### ISSUE TITLE
第十四章添加头像数据库里的head键的值为null。

### ISSUE THREAD

**Issue by CommanderXL** [nswbmw/N-blog#78]
<pre>
<code>
app.post("/post",function(req,res){
    var currentUser=req.session.user;    //我在数据库里查看,这个地方session里user里面并没有定义head的键值，数据库显示为null。
})

应该在app.post("/reg',function(req,res){
....   
var newUser=new User({
        name:name,
        password:password,
        email:req.body.email,
        head:head                         //在教程里面好像没有这个修改的步骤。我觉得问题是出在这个地方
})
....
})

</code>
<pre>

**Comment by CommanderXL** [comment]
@nswbmw

**Comment by CommanderXL** [comment]
gravatar被墙了，只能挂vpn了么？

**Comment by nswbmw** [comment]
qujing, hongxing, shadowsocksx...

**Comment by CommanderXL** [comment]
我一开始说的那个问题对么- -  ？？

**Comment by nswbmw** [comment]
有存 head，见 https://github.com/nswbmw/N-blog/wiki/%E7%AC%AC14%E7%AB%A0--%E5%A2%9E%E5%8A%A0%E5%A4%B4%E5%83%8F#%E6%B7%BB%E5%8A%A0%E5%B7%B2%E6%B3%A8%E5%86%8C%E7%94%A8%E6%88%B7%E7%9A%84%E5%A4%B4%E5%83%8F

>然后将 User.prototype.save 内的:

```
var user = {
    name: this.name,
    password: this.password,
    email: this.email
};
```

>修改为:

```
var md5 = crypto.createHash('md5'),
    email_MD5 = md5.update(this.email.toLowerCase()).digest('hex'),
    head = "http://www.gravatar.com/avatar/" + email_MD5 + "?s=48";
//要存入数据库的用户信息文档
var user = {
    name: this.name,
    password: this.password,
    email: this.email,
    head: head
};
```

**Comment by CommanderXL** [comment]
你说的这个地方是需要修改的。

但是在
<pre>
<code>
app.post("/post",function(){
    var currentUser=req.session.user;    
    //这个地方的session里面user和数据库里面的users并不相同。
   //修改了存入数据库的head键值，但是session里面并没修改
   
   var post=new Post(currentUser.name,currentUser.head,req.body.title,req.body.post,tags);
   //因此存入数据库里的currentUser.head为undefined.
  post.save(function(){
       ........
  })
})
</code>
</pre>

**Comment by nswbmw** [comment]
> 修改了存入数据库的head键值，但是session里面并没修改

是肯定的，除非你登出再重新登录，难道你手动修改数据库的？在 `app.post('/login')`  成功后会将 `req.session.user = user;`，为什么 `app.post("/post")` 取到的 `req.session.user` 和 “数据库里面的users并不相同”？

**Comment by nswbmw** [comment]
额，我知道了，你清下数据库，重新注册遍就好了。因为之前数据库没有 head 这个字段。导致取出来是 null。

**Comment by CommanderXL** [comment]
对啊。我说的就是这个问题也。不过gravator被墙了，图片挂了。

**Comment by CommanderXL** [comment]
第十五章 添加转载功能 实现不了..出现不了 “转载”的按钮~

**Comment by toby20130333** [comment]
http://www.gravatar.com/avatar/40498e48e69a0f9c54a5b8776ec8441d?s=72 这个就是根据邮箱生成的链接 拿不到头像啊 头像都是默认的logo 是怎么回事 亲

**Comment by CommanderXL** [comment]
链接被墙了

**Comment by toby20130333** [comment]
不是的，我的邮箱没有申请gravatar头像导致的

**Comment by timmyLan** [comment]
我的解决方法：
修改/models/user.js
`User.prototype.save = function(callback){...}`中的成功的callback回调参数
原：`callback(null , user[0]);`
修改为: `callback(null , user['ops'][0]);`

希望可以帮到你 :)
