### ISSUE TITLE
MongoDB 版本问题

### ISSUE THREAD

**Issue by Sirormy** [nswbmw/N-blog#82]
作者使用的 Mongo 版本是2.6 ，我用的最新的 3.0.3。如果你也遇到跟我一样的问题，可以参考下。

接着说，我配到Sessions那块，访问首页报错了，我是这样做的：
找到 blog/node_modules/mongodb/lib/db.js ，给这种语句加了一行打印：

``` js
if(err){
   // 我加的
   console.log(err);
   throw new xxx
}
```

然后启动之后，报错信息打出来了

> { [MongoError: driver is incompatible with this server version] name: 'MongoError' }
> 那么问题来了，驱动版本应该是多少？

我回头看了一下作者的 package.json 中依赖，

> "mongodb": "1.4.15"
> "connect-mongo": "0.4.1"

不用想，改了这俩肯定好使了，
去npm 一趟，找了一下 最新的 connect-mongo 0.8.1，mongodb 2.0.33，

再启动，OK

**Comment by CeleryCup** [comment]
刚遇到这个问题，请问一下throw new xxx 是什么意思？

**Comment by CommanderXL** [comment]
有些可能存在版本升级以后写法改变的问题。尽量用最新的版本吧

**Comment by Sirormy** [comment]
throw new Error(xx) , 抛的异常，高版本bug也多，2.6比较稳定，3.0升级之后差异很大

**Comment by nateliu** [comment]
为何如此纠结，直接npm install xxxx --save 安装最新的吧。

**Comment by jddy** [comment]
Last version:
"koa-mongo": "0.5.0",
"mongodb": "~2.2.4"

**Comment by shawn-jdd** [comment]
我的竟然没错

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
