### ISSUE TITLE
第4章 调用post.get方法

### ISSUE THREAD

**Issue by jiang1983** [nswbmw/N-blog#85]
post.get的参数name实际上应该是一个用户list{}，而不是从url里面提取的变量，在url里面的name实际上应该是post.name.name，这样才会是字符串。否则按照博主写的post.name 应该是个object，在ejs模板里面是无法显示成字符串的，实际上显示的是Objec object.

对于变量的类型有些乱，导致了后面调试出问题，不知道大家按照题主的写法能够写到第四章还完整运行的吗？

目前来看第一章没什么问题，后面题主是否代码和博客不是一起写的导致很多不一致的地方？

down下lz的完整代码，总是出现cannot get /之类的问题，请问如何解决？

**Comment by CommanderXL** [comment]
可能会出现你说的那种情况。随着你写的过程中你应该能发现这些小失误，自己改过来就好。

**Comment by jiang1983** [comment]
新学的JavaScript，想问一下json数据类型的问题。
var query={}
var name={}
query.name=name
为什么达不到我想要的效果呢？
我希望达到这种效果query={"name":{}}

**Comment by CommanderXL** [comment]
把query的属性名换成别的，不要和name一样。

**Comment by yinzSE** [comment]
@jiang1983 
![image](https://cloud.githubusercontent.com/assets/12208108/11014909/cfdb3268-8584-11e5-9bf2-6870fe43b5ff.png)

**Comment by eyeA** [comment]
同样的  Cannot GET /  问题

如果有回复 请艾特下我 

万分感谢！

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
