### ISSUE TITLE
第一章 里 session的操作会报错

### ISSUE THREAD

**Issue by freezen** [nswbmw/N-blog#86]
在路由文件夹里，index.js这个文件中，在注册时，如果使用get方法，那这一行代码：
     req.session.user = user;//用户信息存入 session
会暴req.session.user -> undefined 这个错误，作者能解释一下吗？谢谢

**Comment by iamiota** [comment]
在app.use(cookieParser());
前面加上app.use(cookieParser(settings.cookieSecret));
如果还报错，调整顺序如下:
app.use(session({......}))
app.use(flash());
routes(app);

**Comment by jcpplus** [comment]
谢谢，我的出错了是因为把`app.use(flash());`放在了 `routes(app);`后面
