### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by xiaocongWang** [nswbmw/N-blog#88]
User.prototype.save 中，mongodb.open函数中最后的callback调用callback(null,user[0]) , 有bug。
一开始我试了callback(null,user)  发现在注册后，发表文章，不能显示作者的名字。
后来我发现应该改成callback(null,user.ops[0])，是正确的。

**Comment by yangjunjun** [comment]
我也遇到了同样的问题， 原因是作者用的是 **1.4.15** 的 ` node-mongodb-native`, 你用的是 **2.x.x** ，API 接口已经大不相同了。
