### ISSUE TITLE
能不能写一个koa的教程

### ISSUE THREAD

**Issue by yuu2lee4** [nswbmw/N-blog#89]
把koa单独拿出来 写一个教程 可以么

**Comment by nswbmw** [comment]
马上会有的 :)

**Comment by yuu2lee4** [comment]
真是太感谢了 以前学express就是看的你的文档

**Comment by kunl** [comment]
+1

**Comment by 413405872** [comment]
请问我在运行node app.js出现这个
D:\node\test\node_modules\mongodb\lib\server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect UNKNOWN
    at exports._errnoException (util.js:746:11)
    at connect (net.js:842:19)
    at net.js:955:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)


是什么原因呢？？网上也没找到解答，我之前在实验室的时候这个程序我都能正常跑了，但是现在我在自己笔记本上重新搞了个node和mongodb，然后一切都弄好了，结果运行有这个错误，想请教一下。感激不尽

**Comment by Jocs** [comment]
请问你的mongodb是在本地还是在网上呢？像百度开放云上面的mongodb，在本地就连接不上的。
如果是本地的数据库，看下数据库配置，端口是否正确呢？还有最后有代码能看到，这样容易
找到问题。

**Comment by 413405872** [comment]
这个是运行在本地的数据库，而且端口一切都正常，这个程序我在实验室的时候都能正常跑的，但是宿舍电脑就不行了

**Comment by yuu2lee4** [comment]
快11月份了。。。

**Comment by nswbmw** [comment]
@yuu2lee4 http://item.jd.com/1759405018.html ...

**Comment by yuu2lee4** [comment]
tks

**Comment by nswbmw** [comment]
http://nswbmw.github.io/N-club/
