### ISSUE TITLE
第一章关于npm install 和package.json

### ISSUE THREAD

**Issue by Foonemo** [nswbmw/N-blog#90]
关于第一章添加package：
先在package.json中添加dependency，之后再使用 `npm install` 是否和直接使用 `npm install <package name> --save` 效果是一样的？后者可以不用指定版本，默认安装最新的可以更方便？刚接触nodeJS不久，以上只是我的一点见解，非常感谢你的教程，帮助我解决了很多困惑。

**Comment by llp0574** [comment]
添加dependency不指定版本号也可以默认安装最新的

**Comment by Jocs** [comment]
也可以像这样写：{"socket.io":"latest"}

**Comment by nswbmw** [comment]
npm install <package name> --save 安装最新版本（如果指定版本安装指定版本）并写 package.json的dependency，省事些
