### ISSUE TITLE
DEBUG=blog node ./bin/www 無法執行

### ISSUE THREAD

**Issue by EasonWang01** [nswbmw/N-blog#92]
分別在win7跟ubuntu執行win7為找不到dir     ubuntu為跑十秒後無反應

請問是有套件沒安裝還是?

**Comment by EasonWang01** [comment]
使用win7
輸入DEBUG=blog node ./bin/www
顯示 file not found

**Comment by FatDonkey** [comment]
教程有啊，这个不行就用npm start这个命令

**Comment by EasonWang01** [comment]
呵，好久以前，目前已找到答案，
for windows
```
set DEBUG=express:* & node index.js
```
源自https://www.npmjs.com/package/debug
http://expressjs.com/zh-tw/guide/debugging.html
