### ISSUE TITLE
新手求学

### ISSUE THREAD

**Issue by zhongDZ** [nswbmw/N-blog#94]
is:issue is:open 你好，想请问，在第一章中的安装MongoDB,然后进入到 bin 目录下（是指进入到项目的bin文件夹下面吗？）还有这个地方 MongoDB 解压换名之后是放在哪个目录下面呢？

**Comment by jcpplus** [comment]
1：是的
2：随便放哪个目录下都可以，我是直接放在D盘根目录。 `d:\mongodb`

**Comment by zhongDZ** [comment]
好的，谢谢
