### ISSUE TITLE
关于第三章的文件上传

### ISSUE THREAD

**Issue by crazyf297** [nswbmw/N-blog#98]
我参照你的代码，在进行文件上传的时候没有成功将文件上传到指定的文件夹，但是前端已经显示上传成功且没有脚本错，控制台提示 302 Moved Temporarily  已经检查了所有的代码逻辑，实在找不出问题所在。
还有一个问题就是为什么版本号为1.0.6的multer无法正常调用，无法被识别为中间件？

谢谢你为我解惑。

**Comment by TimePower** [comment]
multer 使用方式发生了变化
<pre><code>
var multer  = require('multer');
app.post('/upload', upload.single('avatar'), function (req, res, next) {
})
<form method="POST" enctype="multipart/form-data" action="/upload">
    <input type="file" name="avatar"/><br/>
    <input type="submit">
</form>
</pre></code>
得这样用
https://github.com/expressjs/multer

**Comment by yinzSE** [comment]
```javascript
var upload = multer({
  dest: 'public/images',
});

app.use(upload.any());
```
