### ISSUE TITLE
关于第一章注册用户的时候提示req.session为undefined

### ISSUE THREAD

**Issue by kaerhasnoballs** [nswbmw/N-blog#99]
TypeError: Cannot set property 'user' of undefined
    at D:\monkey\workspace\blog\routes\index.js:44:26
    ...
debug发现req.session一直是undefined，才开始学node，不知道什么原因

**Comment by Lapsec** [comment]
不贴代码怎么知道问题在哪

**Comment by kylezhang** [comment]
估计是body解析中间件没有required

**Comment by nswbmw** [comment]
看看 express-session 中间件是否引入
